In [126]:
import requests
from bs4 import BeautifulSoup
import timeit
import re
import pandas as pd
import numpy as np

In [51]:
url = 'https://www.worldometers.info/coronavirus/'
response = requests.get(url)
soup = BeautifulSoup(response.content, "html.parser")

In [52]:
# You now can query the `soup` object!
soup.title.string

'Coronavirus Update (Live): 107,350,771 Cases and 2,347,925 Deaths from COVID-19 Virus Pandemic - Worldometer'

In [53]:
td = soup.find_all('td')
td

[<td></td>,
 <td style="text-align:left;">
 <nobr>North America</nobr>
 </td>,
 <td>31,789,405</td>,
 <td>+84,753</td>,
 <td>691,100</td>,
 <td>+3,147</td>,
 <td>20,848,676</td>,
 <td>+113,011</td>,
 <td>10,249,629</td>,
 <td>29,178</td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td data-continent="North America" style="display:none;">North America</td>,
 <td>
 </td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td style="text-align:left;">
 <nobr>Asia</nobr>
 </td>,
 <td>23,707,979</td>,
 <td>+66,628</td>,
 <td>381,332</td>,
 <td>+887</td>,
 <td>22,211,431</td>,
 <td>+67,315</td>,
 <td>1,115,216</td>,
 <td>22,604</td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td data-continent="Asia" style="display:none;">Asia</td>,
 <td>
 </td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td style="text-align:left;">
 <nobr>South America</nobr>
 </td>,
 <td>16,539,469</td>,
 <td>+60,815</td>,
 <td>431,947</td>,
 <td>+1,674</td>,
 <td>14,868,435</td>,
 <td>+95,756</td>,
 <td>1,239,087</td>,
 <td>19,844</td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td data-continent="South America" style="display:none;">South America</td>,
 <td>
 </td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td style="text-align:left;">
 <nobr>Europe</nobr>
 </td>,
 <td>31,551,853</td>,
 <td>+119,709</td>,
 <td>746,159</td>,
 <td>+5,475</td>,
 <td>18,199,991</td>,
 <td>+136,570</td>,
 <td>12,605,703</td>,
 <td>28,419</td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td data-continent="Europe" style="display:none;">Europe</td>,
 <td>
 </td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td style="text-align:left;">
 <nobr>Africa</nobr>
 </td>,
 <td>3,710,916</td>,
 <td>+9,626</td>,
 <td>96,292</td>,
 <td>+644</td>,
 <td>3,232,445</td>,
 <td>+12,330</td>,
 <td>382,179</td>,
 <td>2,559</td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td data-continent="Africa" style="display:none;">Africa</td>,
 <td>
 </td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td style="text-align:left;">
 <nobr>Oceania</nobr>
 </td>,
 <td>50,428</td>,
 <td>+6</td>,
 <td>1,080</td>,
 <td></td>,
 <td>34,137</td>,
 <td>+9</td>,
 <td>15,211</td>,
 <td>5</td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td data-continent="Australia/Oceania" style="display:none;">Australia/Oceania</td>,
 <td>
 </td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td style="text-align:left;">
 <nobr></nobr>
 </td>,
 <td>721</td>,
 <td></td>,
 <td>15</td>,
 <td></td>,
 <td>706</td>,
 <td></td>,
 <td>0</td>,
 <td>0</td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td data-continent="" style="display:none;"></td>,
 <td>
 </td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td style="text-align:left;">World</td>,
 <td>107,350,771</td>,
 <td>+341,537</td>,
 <td>2,347,925</td>,
 <td>+11,827</td>,
 <td>79,395,821</td>,
 <td>+424,991</td>,
 <td>25,607,025</td>,
 <td>102,609</td>,
 <td>13,772</td>,
 <td>301.2</td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td data-continent="all" style="display:none">All</td>,
 <td>
 </td>,
 <td></td>,
 <td></td>,
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">1</td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/us/">USA</a></td>,
 <td style="font-weight: bold; text-align:right">27,778,684</td>,
 <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+75,057</td>,
 <td style="font-weight: bold; text-align:right;">478,967 </td>,
 <td style="font-weight: bold;
                                     text-align:right;background-color:red; color:white">+2,459</td>,
 <td style="font-weight: bold; text-align:right">17,607,437</td>,
 <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+94,617</td>,
 <td style="text-align:right;font-weight:bold;">9,692,280</td>,
 <td style="font-weight: bold; text-align:right">21,447</td>,
 <td style="font-weight: bold; text-align:right">83,625</td>,
 <td style="font-weight: bold; text-align:right">1,442</td>,
 <td style="font-weight: bold; text-align:right">326,902,996</td>,
 <td style="font-weight: bold; text-align:right">984,106</td>,
 <td style="font-weight: bold; text-align:right"><a href="/world-population/us-population/">332,182,690</a> </td>,
 <td data-continent="North America" style="display:none">North America</td>,
 <td>12</td>,
 <td>694</td>,
 <td>1</td>,
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">2</td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/india/">India</a></td>,
 <td style="font-weight: bold; text-align:right">10,858,300</td>,
 <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+10,510</td>,
 <td style="font-weight: bold; text-align:right;">155,280 </td>,
 <td style="font-weight: bold;
                                     text-align:right;background-color:red; color:white">+85</td>,
 <td style="font-weight: bold; text-align:right">10,559,604</td>,
 <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+12,699</td>,
 <td style="text-align:right;font-weight:bold;">143,416</td>,
 <td style="font-weight: bold; text-align:right">8,944</td>,
 <td style="font-weight: bold; text-align:right">7,822</td>,
 <td style="font-weight: bold; text-align:right">112</td>,
 <td style="font-weight: bold; text-align:right">201,900,614</td>,
 <td style="font-weight: bold; text-align:right">145,437</td>,
 <td style="font-weight: bold; text-align:right"><a href="/world-population/india-population/">1,388,234,493</a> </td>,
 <td data-continent="Asia" style="display:none">Asia</td>,
 <td>128</td>,
 <td>8,940</td>,
 <td>7</td>,
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">3</td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/brazil/">Brazil</a></td>,
 <td style="font-weight: bold; text-align:right">9,599,565</td>,
 <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+49,264</td>,
 <td style="font-weight: bold; text-align:right;">233,520 </td>,
 <td style="font-weight: bold;
                                     text-align:right;background-color:red; color:white">+1,272</td>,
 <td style="font-weight: bold; text-align:right">8,523,462</td>,
 <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+75,817</td>,
 <td style="text-align:right;font-weight:bold;">842,583</td>,
 <td style="font-weight: bold; text-align:right">8,318</td>,
 <td style="font-weight: bold; text-align:right">44,968</td>,
 <td style="font-weight: bold; text-align:right">1,094</td>,
 <td style="font-weight: bold; text-align:right">28,600,000</td>,
 <td style="font-weight: bold; text-align:right">133,972</td>,
 <td style="font-weight: bold; text-align:right"><a href="/world-population/brazil-population/">213,477,384</a> </td>,
 <td data-continent="South America" style="display:none">South America</td>,
 <td>22</td>,
 <td>914</td>,
 <td>7</td>,
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">4</td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/russia/">Russia</a></td>,
 <td style="font-weight: bold; text-align:right">3,998,216</td>,
 <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+15,019</td>,
 <td style="font-weight: bold; text-align:right;">77,598 </td>,
 <td style="font-weight: bold;
                                     text-align:right;background-color:red; color:white">+530</td>,
 <td style="font-weight: bold; text-align:right">3,493,886</td>,
 <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+21,795</td>,
 <td style="text-align:right;font-weight:bold;">426,732</td>,
 <td style="font-weight: bold; text-align:right">2,300</td>,
 <td style="font-weight: bold; text-align:right">27,390</td>,
 <td style="font-weight: bold; text-align:right">532</td>,
 <td style="font-weight: bold; text-align:right">105,000,000</td>,
 <td style="font-weight: bold; text-align:right">719,313</td>,
 <td style="font-weight: bold; text-align:right"><a href="/world-population/russia-population/">145,972,616</a> </td>,
 <td data-continent="Europe" style="display:none">Europe</td>,
 <td>37</td>,
 <td>1,881</td>,
 <td>1</td>,
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">5</td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/uk/">UK</a></td>,
 <td style="font-weight: bold; text-align:right">3,972,148</td>,
 <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+12,364</td>,
 <td style="font-weight: bold; text-align:right;">113,850 </td>,
 <td style="font-weight: bold;
                                     text-align:right;background-color:red; color:white">+1,052</td>,
 <td style="font-weight: bold; text-align:right">1,983,650</td>,
 <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+32,764</td>,
 <td style="text-align:right;font-weight:bold;">1,874,648</td>,
 <td style="font-weight: bold; text-align:right">3,230</td>,
 <td style="font-weight: bold; text-align:right">58,326</td>,
 <td style="font-weight: bold; text-align:right">1,672</td>,
 <td style="font-weight: bold; text-align:right">78,860,651</td>,
 <td style="font-weight: bold; text-align:right">1,157,963</td>,
 <td style="font-weight: bold; text-align:right"><a href="/world-population/uk-population/">68,102,885</a> </td>,
 <td data-continent="Europe" style="display:none">Europe</td>,
 <td>17</td>,
 <td>598</td>,
 <td>1</td>,
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">6</td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/france/">France</a></td>,
 <td style="font-weight: bold; text-align:right">3,360,235</td>,
 <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+18,870</td>,
 <td style="font-weight: bold; text-align:right;">80,147 </td>,
 <td style="font-weight: bold;
                                     text-align:right;background-color:red; color:white">+508</td>,
 <td style="font-weight: bold; text-align:right">235,717</td>,
 <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+1,724</td>,
 <td style="text-align:right;font-weight:bold;">3,044,371</td>,
 <td style="font-weight: bold; text-align:right">3,342</td>,
 <td style="font-weight: bold; text-align:right">51,410</td>,
 <td style="font-weight: bold; text-align:right">1,226</td>,
 <td style="font-weight: bold; text-align:right">46,980,527</td>,
 <td style="font-weight: bold; text-align:right">718,780</td>,
 <td style="font-weight: bold; text-align:right"><a href="/world-population/france-population/">65,361,495</a> </td>,
 <td data-continent="Europe" style="display:none">Europe</td>,
 <td>19</td>,
 <td>816</td>,
 <td>1</td>,
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">7</td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/spain/">Spain</a></td>,
 <td style="font-weight: bold; text-align:right">3,005,487</td>,
 <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+16,402</td>,
 <td style="font-weight: bold; text-align:right;">63,061 </td>,
 <td style="font-weight: bold;
                                     text-align:right;background-color:red; color:white">+766</td>,
 <td style="font-weight: bold; text-align:right">N/A</td>,
 <td style="font-weight: bold; text-align:right;">N/A</td>,
 <td style="text-align:right;font-weight:bold;">N/A</td>,
 <td style="font-weight: bold; text-align:right">4,594</td>,
 <td style="font-weight: bold; text-align:right">64,267</td>,
 <td style="font-weight: bold; text-align:right">1,348</td>,
 <td style="font-weight: bold; text-align:right">35,782,465</td>,
 <td style="font-weight: bold; text-align:right">765,141</td>,
 <td style="font-weight: bold; text-align:right"><a href="/world-population/spain-population/">46,765,820</a> </td>,
 <td data-continent="Europe" style="display:none">Europe</td>,
 <td>16</td>,
 <td>742</td>,
 <td>1</td>,
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">8</td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/italy/">Italy</a></td>,
 <td style="font-weight: bold; text-align:right">2,655,319</td>,
 <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+10,630</td>,
 <td style="font-weight: bold; text-align:right;">92,002 </td>,
 <td style="font-weight: bold;
                                     text-align:right;background-color:red; color:white">+422</td>,
 <td style="font-weight: bold; text-align:right">2,149,350</td>,
 <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+15,827</td>,
 <td style="text-align:right;font-weight:bold;">413,967</td>,
 <td style="font-weight: bold; text-align:right">2,143</td>,
 <td style="font-weight: bold; text-align:right">43,957</td>,
 <td style="font-weight: bold; text-align:right">1,523</td>,
 <td style="font-weight: bold; text-align:right">34,781,259</td>,
 <td style="font-weight: bold; text-align:right">575,777</td>,
 <td style="font-weight: bold; text-align:right"><a href="/world-population/italy-population/">60,407,564</a> </td>,
 <td data-continent="Europe" style="display:none">Europe</td>,
 <td>23</td>,
 <td>657</td>,
 <td>2</td>,
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">9</td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/turkey/">Turkey</a></td>,
 <td style="font-weight: bold; text-align:right">2,548,195</td>,
 <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+8,636</td>,
 <td style="font-weight: bold; text-align:right;">26,998 </td>,
 <td style="font-weight: bold;
                                     text-align:right;background-color:red; color:white">+98</td>,
 <td style="font-weight: bold; text-align:right">2,437,382</td>,
 <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+8,109</td>,
 <td style="text-align:right;font-weight:bold;">83,815</td>,
 <td style="font-weight: bold; text-align:right">1,310</td>,
 <td style="font-weight: bold; text-align:right">30,018</td>,
 <td style="font-weight: bold; text-align:right">318</td>,
 <td style="font-weight: bold; text-align:right">30,893,496</td>,
 <td style="font-weight: bold; text-align:right">363,927</td>,
 <td style="font-weight: bold; text-align:right"><a href="/world-population/turkey-population/">84,889,277</a> </td>,
 <td data-continent="Asia" style="display:none">Asia</td>,
 <td>33</td>,
 <td>3,144</td>,
 <td>3</td>,
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">10</td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/germany/">Germany</a></td>,
 <td style="font-weight: bold; text-align:right">2,302,051</td>,
 <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+5,725</td>,
 <td style="font-weight: bold; text-align:right;">63,271 </td>,
 <td style="font-weight: bold;
                                     text-align:right;background-color:red; color:white">+674</td>,
 <td style="font-weight: bold; text-align:right">2,057,300</td>,
 <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+16,000</td>,
 <td style="text-align:right;font-weight:bold;">181,480</td>,
 <td style="font-weight: bold; text-align:right">3,957</td>,
 <td style="font-weight: bold; text-align:right">27,423</td>,
 <td style="font-weight: bold; text-align:right">754</td>,
 <td style="font-weight: bold; text-align:right">40,705,522</td>,
 <td style="font-weight: bold; text-align:right">484,895</td>,
 <td style="font-weight: bold; text-align:right"><a href="/world-population/germany-population/">83,947,051</a> </td>,
 <td data-continent="Europe" style="display:none">Europe</td>,
 <td>36</td>,
 <td>1,327</td>,
 <td>2</td>,
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">11</td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/colombia/">Colombia</a></td>,
 <td style="font-weight: bold; text-align:right">2,166,904</td>,
 <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+5,442</td>,
 <td style="font-weight: bold; text-align:right;">56,507 </td>,
 <td style="font-weight: bold;
                                     text-align:right;background-color:red; color:white">+217</td>,
 <td style="font-weight: bold; text-align:right">2,048,292</td>,
 <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+14,064</td>,
 <td style="text-align:right;font-weight:bold;">62,105</td>,
 <td style="font-weight: bold; text-align:right">3,482</td>,
 <td style="font-weight: bold; text-align:right">42,313</td>,
 <td style="font-weight: bold; text-align:right">1,103</td>,
 <td style="font-weight: bold; text-align:right">10,601,650</td>,
 <td style="font-weight: bold; text-align:right">207,016</td>,
 <td style="font-weight: bold; text-align:right"><a href="/world-population/colombia-population/">51,211,717</a> </td>,
 <td data-continent="South America" style="display:none">South America</td>,
 <td>24</td>,
 <td>906</td>,
 <td>5</td>,
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">12</td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/argentina/">Argentina</a></td>,
 <td style="font-weight: bold; text-align:right">1,985,501</td>,
 <td style="font-weight: bold; text-align:right;"></td>,
 <td style="font-weight: bold; text-align:right;">49,398 </td>,
 <td style="font-weight: bold;
                                     text-align:right;"></td>,
 <td style="font-weight: bold; text-align:right">1,786,178</td>,
 <td style="font-weight: bold; text-align:right;"></td>,
 <td style="text-align:right;font-weight:bold;">149,925</td>,
 <td style="font-weight: bold; text-align:right">3,526</td>,
 <td style="font-weight: bold; text-align:right">43,688</td>,
 <td style="font-weight: bold; text-align:right">1,087</td>,
 <td style="font-weight: bold; text-align:right">6,538,865</td>,
 <td style="font-weight: bold; text-align:right">143,878</td>,
 <td style="font-weight: bold; text-align:right"><a href="/world-population/argentina-population/">45,447,441</a> </td>,
 <td data-continent="South America" style="display:none">South America</td>,
 <td>23</td>,
 <td>920</td>,
 <td>7</td>,
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">13</td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/mexico/">Mexico</a></td>,
 <td style="font-weight: bold; text-align:right">1,936,013</td>,
 <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+3,868</td>,
 <td style="font-weight: bold; text-align:right;">166,731 </td>,
 <td style="font-weight: bold;
                                     text-align:right;background-color:red; color:white">+531</td>,
 <td style="font-weight: bold; text-align:right">1,501,580</td>,
 <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+11,503</td>,
 <td style="text-align:right;font-weight:bold;">267,702</td>,
 <td style="font-weight: bold; text-align:right">5,692</td>,
 <td style="font-weight: bold; text-align:right">14,921</td>,
 <td style="font-weight: bold; text-align:right">1,285</td>,
 <td style="font-weight: bold; text-align:right">4,902,400</td>,
 <td style="font-weight: bold; text-align:right">37,782</td>,

# get the name of the countries!

In [54]:
%%time
names = soup.find_all('td', style="font-weight: bold; font-size:15px; text-align:left;" )

Wall time: 176 ms

In [55]:
names

[<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/us/">USA</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/india/">India</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/brazil/">Brazil</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/russia/">Russia</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/uk/">UK</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/france/">France</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/spain/">Spain</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/italy/">Italy</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/turkey/">Turkey</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/germany/">Germany</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/colombia/">Colombia</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/argentina/">Argentina</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/mexico/">Mexico</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/poland/">Poland</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/iran/">Iran</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/south-africa/">South Africa</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/ukraine/">Ukraine</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/peru/">Peru</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/indonesia/">Indonesia</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/czech-republic/">Czechia</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/netherlands/">Netherlands</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/canada/">Canada</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/portugal/">Portugal</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/chile/">Chile</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/romania/">Romania</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/belgium/">Belgium</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/israel/">Israel</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/iraq/">Iraq</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/sweden/">Sweden</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/pakistan/">Pakistan</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/philippines/">Philippines</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/bangladesh/">Bangladesh</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/switzerland/">Switzerland</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/morocco/">Morocco</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/austria/">Austria</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/serbia/">Serbia</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/japan/">Japan</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/hungary/">Hungary</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/saudi-arabia/">Saudi Arabia</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/jordan/">Jordan</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/united-arab-emirates/">UAE</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/panama/">Panama</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/lebanon/">Lebanon</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/nepal/">Nepal</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/slovakia/">Slovakia</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/georgia/">Georgia</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/belarus/">Belarus</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/ecuador/">Ecuador</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/malaysia/">Malaysia</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/croatia/">Croatia</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/azerbaijan/">Azerbaijan</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/bolivia/">Bolivia</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/bulgaria/">Bulgaria</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/dominican-republic/">Dominican Republic</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/tunisia/">Tunisia</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/ireland/">Ireland</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/denmark/">Denmark</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/costa-rica/">Costa Rica</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/kazakhstan/">Kazakhstan</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/lithuania/">Lithuania</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/slovenia/">Slovenia</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/kuwait/">Kuwait</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/egypt/">Egypt</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/armenia/">Armenia</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/greece/">Greece</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/moldova/">Moldova</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/guatemala/">Guatemala</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/state-of-palestine/">Palestine</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/honduras/">Honduras</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/qatar/">Qatar</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/ethiopia/">Ethiopia</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/myanmar/">Myanmar</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/nigeria/">Nigeria</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/paraguay/">Paraguay</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/oman/">Oman</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/venezuela/">Venezuela</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/libya/">Libya</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/bosnia-and-herzegovina/">Bosnia and Herzegovina</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/algeria/">Algeria</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/bahrain/">Bahrain</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/kenya/">Kenya</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/macedonia/">North Macedonia</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/albania/">Albania</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/kyrgyzstan/">Kyrgyzstan</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/south-korea/">S. Korea</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/uzbekistan/">Uzbekistan</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/ghana/">Ghana</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/latvia/">Latvia</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/sri-lanka/">Sri Lanka</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/montenegro/">Montenegro</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/norway/">Norway</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/zambia/">Zambia</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/singapore/">Singapore</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/el-salvador/">El Salvador</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/afghanistan/">Afghanistan</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/luxembourg/">Luxembourg</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/estonia/">Estonia</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/finland/">Finland</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/mozambique/">Mozambique</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/uruguay/">Uruguay</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/uganda/">Uganda</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/namibia/">Namibia</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/zimbabwe/">Zimbabwe</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/cuba/">Cuba</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/cyprus/">Cyprus</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/cameroon/">Cameroon</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/cote-d-ivoire/">Ivory Coast</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/senegal/">Senegal</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/australia/">Australia</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/malawi/">Malawi</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/sudan/">Sudan</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/botswana/">Botswana</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/democratic-republic-of-the-congo/">DRC</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/thailand/">Thailand</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/angola/">Angola</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/madagascar/">Madagascar</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/malta/">Malta</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/french-polynesia/">French Polynesia</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/jamaica/">Jamaica</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/maldives/">Maldives</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/mauritania/">Mauritania</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/rwanda/">Rwanda</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/french-guiana/">French Guiana</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/swaziland/">Eswatini</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/guinea/">Guinea</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/syria/">Syria</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/cabo-verde/">Cabo Verde</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/tajikistan/">Tajikistan</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/belize/">Belize</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/haiti/">Haiti</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/gabon/">Gabon</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/mayotte/">Mayotte</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/burkina-faso/">Burkina Faso</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/china-hong-kong-sar/">Hong Kong</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/reunion/">Réunion</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/andorra/">Andorra</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/lesotho/">Lesotho</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/guadeloupe/">Guadeloupe</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/suriname/">Suriname</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/bahamas/">Bahamas</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/mali/">Mali</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/congo/">Congo</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/guyana/">Guyana</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/trinidad-and-tobago/">Trinidad and Tobago</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/aruba/">Aruba</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/martinique/">Martinique</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/nicaragua/">Nicaragua</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/iceland/">Iceland</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/djibouti/">Djibouti</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/equatorial-guinea/">Equatorial Guinea</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/togo/">Togo</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/central-african-republic/">CAR</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/somalia/">Somalia</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/south-sudan/">South Sudan</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/niger/">Niger</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/curacao/">Curaçao</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/gambia/">Gambia</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/benin/">Benin</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/gibraltar/">Gibraltar</a></td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/channel-islands/">Channel Islands</a></td>,

In [56]:
countries = [i.string for i in names]

-----------------------

# get the indices of each nation in the list

In [57]:
for i in enumerate(td):
    print(i)

(0, <td></td>)
(1, <td style="text-align:left;">
<nobr>North America</nobr>
</td>)
(2, <td>31,789,405</td>)
(3, <td>+84,753</td>)
(4, <td>691,100</td>)
(5, <td>+3,147</td>)
(6, <td>20,848,676</td>)
(7, <td>+113,011</td>)
(8, <td>10,249,629</td>)
(9, <td>29,178</td>)
(10, <td></td>)
(11, <td></td>)
(12, <td></td>)
(13, <td></td>)
(14, <td></td>)
(15, <td data-continent="North America" style="display:none;">North America</td>)
(16, <td>
</td>)
(17, <td></td>)
(18, <td></td>)
(19, <td></td>)
(20, <td style="text-align:left;">
<nobr>Asia</nobr>
</td>)
(21, <td>23,707,979</td>)
(22, <td>+66,628</td>)
(23, <td>381,332</td>)
(24, <td>+887</td>)
(25, <td>22,211,431</td>)
(26, <td>+67,315</td>)
(27, <td>1,115,216</td>)
(28, <td>22,604</td>)
(29, <td></td>)
(30, <td></td>)
(31, <td></td>)
(32, <td></td>)
(33, <td></td>)
(34, <td data-continent="Asia" style="display:none;">Asia</td>)
(35, <td>
</td>)
(36, <td></td>)
(37, <td></td>)
(38, <td></td>)
(39, <td style="text-align:left;">
<nobr>South America</nobr>
</td>)
(40, <td>16,539,469</td>)
(41, <td>+60,815</td>)
(42, <td>431,947</td>)
(43, <td>+1,674</td>)
(44, <td>14,868,435</td>)
(45, <td>+95,756</td>)
(46, <td>1,239,087</td>)
(47, <td>19,844</td>)
(48, <td></td>)
(49, <td></td>)
(50, <td></td>)
(51, <td></td>)
(52, <td></td>)
(53, <td data-continent="South America" style="display:none;">South America</td>)
(54, <td>
</td>)
(55, <td></td>)
(56, <td></td>)
(57, <td></td>)
(58, <td style="text-align:left;">
<nobr>Europe</nobr>
</td>)
(59, <td>31,551,853</td>)
(60, <td>+119,709</td>)
(61, <td>746,159</td>)
(62, <td>+5,475</td>)
(63, <td>18,199,991</td>)
(64, <td>+136,570</td>)
(65, <td>12,605,703</td>)
(66, <td>28,419</td>)
(67, <td></td>)
(68, <td></td>)
(69, <td></td>)
(70, <td></td>)
(71, <td></td>)
(72, <td data-continent="Europe" style="display:none;">Europe</td>)
(73, <td>
</td>)
(74, <td></td>)
(75, <td></td>)
(76, <td></td>)
(77, <td style="text-align:left;">
<nobr>Africa</nobr>
</td>)
(78, <td>3,710,916</td>)
(79, <td>+9,626</td>)
(80, <td>96,292</td>)
(81, <td>+644</td>)
(82, <td>3,232,445</td>)
(83, <td>+12,330</td>)
(84, <td>382,179</td>)
(85, <td>2,559</td>)
(86, <td></td>)
(87, <td></td>)
(88, <td></td>)
(89, <td></td>)
(90, <td></td>)
(91, <td data-continent="Africa" style="display:none;">Africa</td>)
(92, <td>
</td>)
(93, <td></td>)
(94, <td></td>)
(95, <td></td>)
(96, <td style="text-align:left;">
<nobr>Oceania</nobr>
</td>)
(97, <td>50,428</td>)
(98, <td>+6</td>)
(99, <td>1,080</td>)
(100, <td></td>)
(101, <td>34,137</td>)
(102, <td>+9</td>)
(103, <td>15,211</td>)
(104, <td>5</td>)
(105, <td></td>)
(106, <td></td>)
(107, <td></td>)
(108, <td></td>)
(109, <td></td>)
(110, <td data-continent="Australia/Oceania" style="display:none;">Australia/Oceania</td>)
(111, <td>
</td>)
(112, <td></td>)
(113, <td></td>)
(114, <td></td>)
(115, <td style="text-align:left;">
<nobr></nobr>
</td>)
(116, <td>721</td>)
(117, <td></td>)
(118, <td>15</td>)
(119, <td></td>)
(120, <td>706</td>)
(121, <td></td>)
(122, <td>0</td>)
(123, <td>0</td>)
(124, <td></td>)
(125, <td></td>)
(126, <td></td>)
(127, <td></td>)
(128, <td></td>)
(129, <td data-continent="" style="display:none;"></td>)
(130, <td>
</td>)
(131, <td></td>)
(132, <td></td>)
(133, <td></td>)
(134, <td style="text-align:left;">World</td>)
(135, <td>107,350,771</td>)
(136, <td>+341,537</td>)
(137, <td>2,347,925</td>)
(138, <td>+11,827</td>)
(139, <td>79,395,821</td>)
(140, <td>+424,991</td>)
(141, <td>25,607,025</td>)
(142, <td>102,609</td>)
(143, <td>13,772</td>)
(144, <td>301.2</td>)
(145, <td></td>)
(146, <td></td>)
(147, <td></td>)
(148, <td data-continent="all" style="display:none">All</td>)
(149, <td>
</td>)
(150, <td></td>)
(151, <td></td>)
(152, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">1</td>)
(153, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/us/">USA</a></td>)
(154, <td style="font-weight: bold; text-align:right">27,778,684</td>)
(155, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+75,057</td>)
(156, <td style="font-weight: bold; text-align:right;">478,967 </td>)
(157, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+2,459</td>)
(158, <td style="font-weight: bold; text-align:right">17,607,437</td>)
(159, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+94,617</td>)
(160, <td style="text-align:right;font-weight:bold;">9,692,280</td>)
(161, <td style="font-weight: bold; text-align:right">21,447</td>)
(162, <td style="font-weight: bold; text-align:right">83,625</td>)
(163, <td style="font-weight: bold; text-align:right">1,442</td>)
(164, <td style="font-weight: bold; text-align:right">326,902,996</td>)
(165, <td style="font-weight: bold; text-align:right">984,106</td>)
(166, <td style="font-weight: bold; text-align:right"><a href="/world-population/us-population/">332,182,690</a> </td>)
(167, <td data-continent="North America" style="display:none">North America</td>)
(168, <td>12</td>)
(169, <td>694</td>)
(170, <td>1</td>)
(171, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">2</td>)
(172, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/india/">India</a></td>)
(173, <td style="font-weight: bold; text-align:right">10,858,300</td>)
(174, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+10,510</td>)
(175, <td style="font-weight: bold; text-align:right;">155,280 </td>)
(176, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+85</td>)
(177, <td style="font-weight: bold; text-align:right">10,559,604</td>)
(178, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+12,699</td>)
(179, <td style="text-align:right;font-weight:bold;">143,416</td>)
(180, <td style="font-weight: bold; text-align:right">8,944</td>)
(181, <td style="font-weight: bold; text-align:right">7,822</td>)
(182, <td style="font-weight: bold; text-align:right">112</td>)
(183, <td style="font-weight: bold; text-align:right">201,900,614</td>)
(184, <td style="font-weight: bold; text-align:right">145,437</td>)
(185, <td style="font-weight: bold; text-align:right"><a href="/world-population/india-population/">1,388,234,493</a> </td>)
(186, <td data-continent="Asia" style="display:none">Asia</td>)
(187, <td>128</td>)
(188, <td>8,940</td>)
(189, <td>7</td>)
(190, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">3</td>)
(191, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/brazil/">Brazil</a></td>)
(192, <td style="font-weight: bold; text-align:right">9,599,565</td>)
(193, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+49,264</td>)
(194, <td style="font-weight: bold; text-align:right;">233,520 </td>)
(195, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+1,272</td>)
(196, <td style="font-weight: bold; text-align:right">8,523,462</td>)
(197, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+75,817</td>)
(198, <td style="text-align:right;font-weight:bold;">842,583</td>)
(199, <td style="font-weight: bold; text-align:right">8,318</td>)
(200, <td style="font-weight: bold; text-align:right">44,968</td>)
(201, <td style="font-weight: bold; text-align:right">1,094</td>)
(202, <td style="font-weight: bold; text-align:right">28,600,000</td>)
(203, <td style="font-weight: bold; text-align:right">133,972</td>)
(204, <td style="font-weight: bold; text-align:right"><a href="/world-population/brazil-population/">213,477,384</a> </td>)
(205, <td data-continent="South America" style="display:none">South America</td>)
(206, <td>22</td>)
(207, <td>914</td>)
(208, <td>7</td>)
(209, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">4</td>)
(210, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/russia/">Russia</a></td>)
(211, <td style="font-weight: bold; text-align:right">3,998,216</td>)
(212, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+15,019</td>)
(213, <td style="font-weight: bold; text-align:right;">77,598 </td>)
(214, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+530</td>)
(215, <td style="font-weight: bold; text-align:right">3,493,886</td>)
(216, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+21,795</td>)
(217, <td style="text-align:right;font-weight:bold;">426,732</td>)
(218, <td style="font-weight: bold; text-align:right">2,300</td>)
(219, <td style="font-weight: bold; text-align:right">27,390</td>)
(220, <td style="font-weight: bold; text-align:right">532</td>)
(221, <td style="font-weight: bold; text-align:right">105,000,000</td>)
(222, <td style="font-weight: bold; text-align:right">719,313</td>)
(223, <td style="font-weight: bold; text-align:right"><a href="/world-population/russia-population/">145,972,616</a> </td>)
(224, <td data-continent="Europe" style="display:none">Europe</td>)
(225, <td>37</td>)
(226, <td>1,881</td>)
(227, <td>1</td>)
(228, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">5</td>)
(229, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/uk/">UK</a></td>)
(230, <td style="font-weight: bold; text-align:right">3,972,148</td>)
(231, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+12,364</td>)
(232, <td style="font-weight: bold; text-align:right;">113,850 </td>)
(233, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+1,052</td>)
(234, <td style="font-weight: bold; text-align:right">1,983,650</td>)
(235, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+32,764</td>)
(236, <td style="text-align:right;font-weight:bold;">1,874,648</td>)
(237, <td style="font-weight: bold; text-align:right">3,230</td>)
(238, <td style="font-weight: bold; text-align:right">58,326</td>)
(239, <td style="font-weight: bold; text-align:right">1,672</td>)
(240, <td style="font-weight: bold; text-align:right">78,860,651</td>)
(241, <td style="font-weight: bold; text-align:right">1,157,963</td>)
(242, <td style="font-weight: bold; text-align:right"><a href="/world-population/uk-population/">68,102,885</a> </td>)
(243, <td data-continent="Europe" style="display:none">Europe</td>)
(244, <td>17</td>)
(245, <td>598</td>)
(246, <td>1</td>)
(247, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">6</td>)
(248, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/france/">France</a></td>)
(249, <td style="font-weight: bold; text-align:right">3,360,235</td>)
(250, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+18,870</td>)
(251, <td style="font-weight: bold; text-align:right;">80,147 </td>)
(252, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+508</td>)
(253, <td style="font-weight: bold; text-align:right">235,717</td>)
(254, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+1,724</td>)
(255, <td style="text-align:right;font-weight:bold;">3,044,371</td>)
(256, <td style="font-weight: bold; text-align:right">3,342</td>)
(257, <td style="font-weight: bold; text-align:right">51,410</td>)
(258, <td style="font-weight: bold; text-align:right">1,226</td>)
(259, <td style="font-weight: bold; text-align:right">46,980,527</td>)
(260, <td style="font-weight: bold; text-align:right">718,780</td>)
(261, <td style="font-weight: bold; text-align:right"><a href="/world-population/france-population/">65,361,495</a> </td>)
(262, <td data-continent="Europe" style="display:none">Europe</td>)
(263, <td>19</td>)
(264, <td>816</td>)
(265, <td>1</td>)
(266, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">7</td>)
(267, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/spain/">Spain</a></td>)
(268, <td style="font-weight: bold; text-align:right">3,005,487</td>)
(269, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+16,402</td>)
(270, <td style="font-weight: bold; text-align:right;">63,061 </td>)
(271, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+766</td>)
(272, <td style="font-weight: bold; text-align:right">N/A</td>)
(273, <td style="font-weight: bold; text-align:right;">N/A</td>)
(274, <td style="text-align:right;font-weight:bold;">N/A</td>)
(275, <td style="font-weight: bold; text-align:right">4,594</td>)
(276, <td style="font-weight: bold; text-align:right">64,267</td>)
(277, <td style="font-weight: bold; text-align:right">1,348</td>)
(278, <td style="font-weight: bold; text-align:right">35,782,465</td>)
(279, <td style="font-weight: bold; text-align:right">765,141</td>)
(280, <td style="font-weight: bold; text-align:right"><a href="/world-population/spain-population/">46,765,820</a> </td>)
(281, <td data-continent="Europe" style="display:none">Europe</td>)
(282, <td>16</td>)
(283, <td>742</td>)
(284, <td>1</td>)
(285, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">8</td>)
(286, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/italy/">Italy</a></td>)
(287, <td style="font-weight: bold; text-align:right">2,655,319</td>)
(288, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+10,630</td>)
(289, <td style="font-weight: bold; text-align:right;">92,002 </td>)
(290, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+422</td>)
(291, <td style="font-weight: bold; text-align:right">2,149,350</td>)
(292, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+15,827</td>)
(293, <td style="text-align:right;font-weight:bold;">413,967</td>)
(294, <td style="font-weight: bold; text-align:right">2,143</td>)
(295, <td style="font-weight: bold; text-align:right">43,957</td>)
(296, <td style="font-weight: bold; text-align:right">1,523</td>)
(297, <td style="font-weight: bold; text-align:right">34,781,259</td>)
(298, <td style="font-weight: bold; text-align:right">575,777</td>)
(299, <td style="font-weight: bold; text-align:right"><a href="/world-population/italy-population/">60,407,564</a> </td>)
(300, <td data-continent="Europe" style="display:none">Europe</td>)
(301, <td>23</td>)
(302, <td>657</td>)
(303, <td>2</td>)
(304, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">9</td>)
(305, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/turkey/">Turkey</a></td>)
(306, <td style="font-weight: bold; text-align:right">2,548,195</td>)
(307, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+8,636</td>)
(308, <td style="font-weight: bold; text-align:right;">26,998 </td>)
(309, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+98</td>)
(310, <td style="font-weight: bold; text-align:right">2,437,382</td>)
(311, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+8,109</td>)
(312, <td style="text-align:right;font-weight:bold;">83,815</td>)
(313, <td style="font-weight: bold; text-align:right">1,310</td>)
(314, <td style="font-weight: bold; text-align:right">30,018</td>)
(315, <td style="font-weight: bold; text-align:right">318</td>)
(316, <td style="font-weight: bold; text-align:right">30,893,496</td>)
(317, <td style="font-weight: bold; text-align:right">363,927</td>)
(318, <td style="font-weight: bold; text-align:right"><a href="/world-population/turkey-population/">84,889,277</a> </td>)
(319, <td data-continent="Asia" style="display:none">Asia</td>)
(320, <td>33</td>)
(321, <td>3,144</td>)
(322, <td>3</td>)
(323, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">10</td>)
(324, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/germany/">Germany</a></td>)
(325, <td style="font-weight: bold; text-align:right">2,302,051</td>)
(326, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+5,725</td>)
(327, <td style="font-weight: bold; text-align:right;">63,271 </td>)
(328, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+674</td>)
(329, <td style="font-weight: bold; text-align:right">2,057,300</td>)
(330, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+16,000</td>)
(331, <td style="text-align:right;font-weight:bold;">181,480</td>)
(332, <td style="font-weight: bold; text-align:right">3,957</td>)
(333, <td style="font-weight: bold; text-align:right">27,423</td>)
(334, <td style="font-weight: bold; text-align:right">754</td>)
(335, <td style="font-weight: bold; text-align:right">40,705,522</td>)
(336, <td style="font-weight: bold; text-align:right">484,895</td>)
(337, <td style="font-weight: bold; text-align:right"><a href="/world-population/germany-population/">83,947,051</a> </td>)
(338, <td data-continent="Europe" style="display:none">Europe</td>)
(339, <td>36</td>)
(340, <td>1,327</td>)
(341, <td>2</td>)
(342, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">11</td>)
(343, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/colombia/">Colombia</a></td>)
(344, <td style="font-weight: bold; text-align:right">2,166,904</td>)
(345, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+5,442</td>)
(346, <td style="font-weight: bold; text-align:right;">56,507 </td>)
(347, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+217</td>)
(348, <td style="font-weight: bold; text-align:right">2,048,292</td>)
(349, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+14,064</td>)
(350, <td style="text-align:right;font-weight:bold;">62,105</td>)
(351, <td style="font-weight: bold; text-align:right">3,482</td>)
(352, <td style="font-weight: bold; text-align:right">42,313</td>)
(353, <td style="font-weight: bold; text-align:right">1,103</td>)
(354, <td style="font-weight: bold; text-align:right">10,601,650</td>)
(355, <td style="font-weight: bold; text-align:right">207,016</td>)
(356, <td style="font-weight: bold; text-align:right"><a href="/world-population/colombia-population/">51,211,717</a> </td>)
(357, <td data-continent="South America" style="display:none">South America</td>)
(358, <td>24</td>)
(359, <td>906</td>)
(360, <td>5</td>)
(361, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">12</td>)
(362, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/argentina/">Argentina</a></td>)
(363, <td style="font-weight: bold; text-align:right">1,985,501</td>)
(364, <td style="font-weight: bold; text-align:right;"></td>)
(365, <td style="font-weight: bold; text-align:right;">49,398 </td>)
(366, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(367, <td style="font-weight: bold; text-align:right">1,786,178</td>)
(368, <td style="font-weight: bold; text-align:right;"></td>)
(369, <td style="text-align:right;font-weight:bold;">149,925</td>)

(1813, <td style="text-align:right;font-weight:bold;">10,708</td>)
(1814, <td style="font-weight: bold; text-align:right">97</td>)
(1815, <td style="font-weight: bold; text-align:right">38,896</td>)
(1816, <td style="font-weight: bold; text-align:right">728</td>)
(1817, <td style="font-weight: bold; text-align:right">1,259,370</td>)
(1818, <td style="font-weight: bold; text-align:right">672,234</td>)
(1819, <td style="font-weight: bold; text-align:right"><a href="/world-population/latvia-population/">1,873,410</a> </td>)
(1820, <td data-continent="Europe" style="display:none">Europe</td>)
(1821, <td>26</td>)
(1822, <td>1,374</td>)
(1823, <td>1</td>)
(1824, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">89</td>)
(1825, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/sri-lanka/">Sri Lanka</a></td>)
(1826, <td style="font-weight: bold; text-align:right">71,211</td>)
(1827, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+976</td>)
(1828, <td style="font-weight: bold; text-align:right;">370 </td>)
(1829, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+5</td>)
(1830, <td style="font-weight: bold; text-align:right">65,053</td>)
(1831, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+912</td>)
(1832, <td style="text-align:right;font-weight:bold;">5,788</td>)
(1833, <td style="font-weight: bold; text-align:right"></td>)
(1834, <td style="font-weight: bold; text-align:right">3,317</td>)
(1835, <td style="font-weight: bold; text-align:right">17</td>)
(1836, <td style="font-weight: bold; text-align:right">1,831,420</td>)
(1837, <td style="font-weight: bold; text-align:right">85,310</td>)
(1838, <td style="font-weight: bold; text-align:right"><a href="/world-population/sri-lanka-population/">21,467,883</a> </td>)
(1839, <td data-continent="Asia" style="display:none">Asia</td>)
(1840, <td>301</td>)
(1841, <td>58,021</td>)
(1842, <td>12</td>)
(1843, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">90</td>)
(1844, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/montenegro/">Montenegro</a></td>)
(1845, <td style="font-weight: bold; text-align:right">66,234</td>)
(1846, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+577</td>)
(1847, <td style="font-weight: bold; text-align:right;">852 </td>)
(1848, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+10</td>)
(1849, <td style="font-weight: bold; text-align:right">57,423</td>)
(1850, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+330</td>)
(1851, <td style="text-align:right;font-weight:bold;">7,959</td>)
(1852, <td style="font-weight: bold; text-align:right">68</td>)
(1853, <td style="font-weight: bold; text-align:right">105,449</td>)
(1854, <td style="font-weight: bold; text-align:right">1,356</td>)
(1855, <td style="font-weight: bold; text-align:right">244,916</td>)
(1856, <td style="font-weight: bold; text-align:right">389,923</td>)
(1857, <td style="font-weight: bold; text-align:right"><a href="/world-population/montenegro-population/">628,114</a> </td>)
(1858, <td data-continent="Europe" style="display:none">Europe</td>)
(1859, <td>9</td>)
(1860, <td>737</td>)
(1861, <td>3</td>)
(1862, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">91</td>)
(1863, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/norway/">Norway</a></td>)
(1864, <td style="font-weight: bold; text-align:right">65,252</td>)
(1865, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+134</td>)
(1866, <td style="font-weight: bold; text-align:right;">583 </td>)
(1867, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+1</td>)
(1868, <td style="font-weight: bold; text-align:right">57,004</td>)
(1869, <td style="font-weight: bold; text-align:right;"></td>)
(1870, <td style="text-align:right;font-weight:bold;">7,665</td>)
(1871, <td style="font-weight: bold; text-align:right">20</td>)
(1872, <td style="font-weight: bold; text-align:right">11,979</td>)
(1873, <td style="font-weight: bold; text-align:right">107</td>)
(1874, <td style="font-weight: bold; text-align:right">3,540,037</td>)
(1875, <td style="font-weight: bold; text-align:right">649,908</td>)
(1876, <td style="font-weight: bold; text-align:right"><a href="/world-population/norway-population/">5,446,985</a> </td>)
(1877, <td data-continent="Europe" style="display:none">Europe</td>)
(1878, <td>83</td>)
(1879, <td>9,343</td>)
(1880, <td>2</td>)
(1881, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">92</td>)
(1882, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/zambia/">Zambia</a></td>)
(1883, <td style="font-weight: bold; text-align:right">64,610</td>)
(1884, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+1,037</td>)
(1885, <td style="font-weight: bold; text-align:right;">881 </td>)
(1886, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+12</td>)
(1887, <td style="font-weight: bold; text-align:right">58,319</td>)
(1888, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+1,990</td>)
(1889, <td style="text-align:right;font-weight:bold;">5,410</td>)
(1890, <td style="font-weight: bold; text-align:right">395</td>)
(1891, <td style="font-weight: bold; text-align:right">3,456</td>)
(1892, <td style="font-weight: bold; text-align:right">47</td>)
(1893, <td style="font-weight: bold; text-align:right">985,221</td>)
(1894, <td style="font-weight: bold; text-align:right">52,706</td>)
(1895, <td style="font-weight: bold; text-align:right"><a href="/world-population/zambia-population/">18,692,789</a> </td>)
(1896, <td data-continent="Africa" style="display:none">Africa</td>)
(1897, <td>289</td>)
(1898, <td>21,218</td>)
(1899, <td>19</td>)
(1900, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">93</td>)
(1901, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/singapore/">Singapore</a></td>)
(1902, <td style="font-weight: bold; text-align:right">59,732</td>)
(1903, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+11</td>)
(1904, <td style="font-weight: bold; text-align:right;">29 </td>)
(1905, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(1906, <td style="font-weight: bold; text-align:right">59,506</td>)
(1907, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+22</td>)
(1908, <td style="text-align:right;font-weight:bold;">197</td>)
(1909, <td style="font-weight: bold; text-align:right">1</td>)
(1910, <td style="font-weight: bold; text-align:right">10,161</td>)
(1911, <td style="font-weight: bold; text-align:right">5</td>)
(1912, <td style="font-weight: bold; text-align:right">6,799,834</td>)
(1913, <td style="font-weight: bold; text-align:right">1,156,772</td>)
(1914, <td style="font-weight: bold; text-align:right"><a href="/world-population/singapore-population/">5,878,283</a> </td>)
(1915, <td data-continent="Asia" style="display:none">Asia</td>)
(1916, <td>98</td>)
(1917, <td>202,699</td>)
(1918, <td>1</td>)
(1919, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">94</td>)
(1920, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/el-salvador/">El Salvador</a></td>)
(1921, <td style="font-weight: bold; text-align:right">56,653</td>)
(1922, <td style="font-weight: bold; text-align:right;"></td>)
(1923, <td style="font-weight: bold; text-align:right;">1,701 </td>)
(1924, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+9</td>)
(1925, <td style="font-weight: bold; text-align:right">50,999</td>)
(1926, <td style="font-weight: bold; text-align:right;"></td>)
(1927, <td style="text-align:right;font-weight:bold;">3,953</td>)
(1928, <td style="font-weight: bold; text-align:right">68</td>)
(1929, <td style="font-weight: bold; text-align:right">8,708</td>)
(1930, <td style="font-weight: bold; text-align:right">261</td>)
(1931, <td style="font-weight: bold; text-align:right">717,882</td>)
(1932, <td style="font-weight: bold; text-align:right">110,340</td>)
(1933, <td style="font-weight: bold; text-align:right"><a href="/world-population/el-salvador-population/">6,506,111</a> </td>)
(1934, <td data-continent="North America" style="display:none">North America</td>)
(1935, <td>115</td>)
(1936, <td>3,825</td>)
(1937, <td>9</td>)
(1938, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">95</td>)
(1939, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/afghanistan/">Afghanistan</a></td>)
(1940, <td style="font-weight: bold; text-align:right">55,402</td>)
(1941, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+16</td>)
(1942, <td style="font-weight: bold; text-align:right;">2,418 </td>)
(1943, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+4</td>)
(1944, <td style="font-weight: bold; text-align:right">48,109</td>)
(1945, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+67</td>)
(1946, <td style="text-align:right;font-weight:bold;">4,875</td>)
(1947, <td style="font-weight: bold; text-align:right">982</td>)
(1948, <td style="font-weight: bold; text-align:right">1,404</td>)
(1949, <td style="font-weight: bold; text-align:right">61</td>)
(1950, <td style="font-weight: bold; text-align:right">266,733</td>)
(1951, <td style="font-weight: bold; text-align:right">6,760</td>)
(1952, <td style="font-weight: bold; text-align:right"><a href="/world-population/afghanistan-population/">39,456,074</a> </td>)
(1953, <td data-continent="Asia" style="display:none">Asia</td>)
(1954, <td>712</td>)
(1955, <td>16,318</td>)
(1956, <td>148</td>)
(1957, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">96</td>)
(1958, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/luxembourg/">Luxembourg</a></td>)
(1959, <td style="font-weight: bold; text-align:right">52,022</td>)
(1960, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+143</td>)
(1961, <td style="font-weight: bold; text-align:right;">600 </td>)
(1962, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+3</td>)
(1963, <td style="font-weight: bold; text-align:right">48,853</td>)
(1964, <td style="font-weight: bold; text-align:right;"></td>)
(1965, <td style="text-align:right;font-weight:bold;">2,569</td>)
(1966, <td style="font-weight: bold; text-align:right">15</td>)
(1967, <td style="font-weight: bold; text-align:right">82,296</td>)
(1968, <td style="font-weight: bold; text-align:right">949</td>)
(1969, <td style="font-weight: bold; text-align:right">1,969,824</td>)
(1970, <td style="font-weight: bold; text-align:right">3,116,159</td>)
(1971, <td style="font-weight: bold; text-align:right"><a href="/world-population/luxembourg-population/">632,132</a> </td>)
(1972, <td data-continent="Europe" style="display:none">Europe</td>)
(1973, <td>12</td>)
(1974, <td>1,054</td>)
(1975, <td>0</td>)
(1976, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">97</td>)
(1977, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/estonia/">Estonia</a></td>)
(1978, <td style="font-weight: bold; text-align:right">48,809</td>)
(1979, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+542</td>)
(1980, <td style="font-weight: bold; text-align:right;">474 </td>)
(1981, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+8</td>)
(1982, <td style="font-weight: bold; text-align:right">38,730</td>)
(1983, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+822</td>)
(1984, <td style="text-align:right;font-weight:bold;">9,605</td>)
(1985, <td style="font-weight: bold; text-align:right">33</td>)
(1986, <td style="font-weight: bold; text-align:right">36,779</td>)
(1987, <td style="font-weight: bold; text-align:right">357</td>)
(1988, <td style="font-weight: bold; text-align:right">815,743</td>)
(1989, <td style="font-weight: bold; text-align:right">614,691</td>)
(1990, <td style="font-weight: bold; text-align:right"><a href="/world-population/estonia-population/">1,327,079</a> </td>)
(1991, <td data-continent="Europe" style="display:none">Europe</td>)
(1992, <td>27</td>)
(1993, <td>2,800</td>)
(1994, <td>2</td>)
(1995, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">98</td>)
(1996, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/finland/">Finland</a></td>)
(1997, <td style="font-weight: bold; text-align:right">48,407</td>)
(1998, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+438</td>)
(1999, <td style="font-weight: bold; text-align:right;">703 </td>)
(2000, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+2</td>)
(2001, <td style="font-weight: bold; text-align:right">31,000</td>)
(2002, <td style="font-weight: bold; text-align:right;"></td>)
(2003, <td style="text-align:right;font-weight:bold;">16,704</td>)
(2004, <td style="font-weight: bold; text-align:right">15</td>)
(2005, <td style="font-weight: bold; text-align:right">8,728</td>)
(2006, <td style="font-weight: bold; text-align:right">127</td>)
(2007, <td style="font-weight: bold; text-align:right">2,985,401</td>)
(2008, <td style="font-weight: bold; text-align:right">538,301</td>)
(2009, <td style="font-weight: bold; text-align:right"><a href="/world-population/finland-population/">5,545,965</a> </td>)
(2010, <td data-continent="Europe" style="display:none">Europe</td>)
(2011, <td>115</td>)
(2012, <td>7,889</td>)
(2013, <td>2</td>)
(2014, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">99</td>)
(2015, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/mozambique/">Mozambique</a></td>)
(2016, <td style="font-weight: bold; text-align:right">45,785</td>)
(2017, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+873</td>)
(2018, <td style="font-weight: bold; text-align:right;">480 </td>)
(2019, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+15</td>)
(2020, <td style="font-weight: bold; text-align:right">27,814</td>)
(2021, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+376</td>)
(2022, <td style="text-align:right;font-weight:bold;">17,491</td>)
(2023, <td style="font-weight: bold; text-align:right"></td>)
(2024, <td style="font-weight: bold; text-align:right">1,441</td>)
(2025, <td style="font-weight: bold; text-align:right">15</td>)
(2026, <td style="font-weight: bold; text-align:right">367,994</td>)
(2027, <td style="font-weight: bold; text-align:right">11,579</td>)
(2028, <td style="font-weight: bold; text-align:right"><a href="/world-population/mozambique-population/">31,780,697</a> </td>)
(2029, <td data-continent="Africa" style="display:none">Africa</td>)
(2030, <td>694</td>)
(2031, <td>66,210</td>)
(2032, <td>86</td>)
(2033, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">100</td>)
(2034, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/uruguay/">Uruguay</a></td>)
(2035, <td style="font-weight: bold; text-align:right">45,650</td>)
(2036, <td style="font-weight: bold; text-align:right;"></td>)
(2037, <td style="font-weight: bold; text-align:right;">497 </td>)
(2038, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(2039, <td style="font-weight: bold; text-align:right">39,677</td>)
(2040, <td style="font-weight: bold; text-align:right;"></td>)
(2041, <td style="text-align:right;font-weight:bold;">5,476</td>)
(2042, <td style="font-weight: bold; text-align:right">75</td>)
(2043, <td style="font-weight: bold; text-align:right">13,114</td>)
(2044, <td style="font-weight: bold; text-align:right">143</td>)
(2045, <td style="font-weight: bold; text-align:right">894,791</td>)
(2046, <td style="font-weight: bold; text-align:right">257,046</td>)
(2047, <td style="font-weight: bold; text-align:right"><a href="/world-population/uruguay-population/">3,481,059</a> </td>)
(2048, <td data-continent="South America" style="display:none">South America</td>)
(2049, <td>76</td>)
(2050, <td>7,004</td>)
(2051, <td>4</td>)
(2052, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">101</td>)
(2053, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/uganda/">Uganda</a></td>)
(2054, <td style="font-weight: bold; text-align:right">39,883</td>)
(2055, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+23</td>)
(2056, <td style="font-weight: bold; text-align:right;">327 </td>)
(2057, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(2058, <td style="font-weight: bold; text-align:right">14,440</td>)
(2059, <td style="font-weight: bold; text-align:right;"></td>)
(2060, <td style="text-align:right;font-weight:bold;">25,116</td>)
(2061, <td style="font-weight: bold; text-align:right"></td>)
(2062, <td style="font-weight: bold; text-align:right">856</td>)
(2063, <td style="font-weight: bold; text-align:right">7</td>)
(2064, <td style="font-weight: bold; text-align:right">845,566</td>)
(2065, <td style="font-weight: bold; text-align:right">18,143</td>)
(2066, <td style="font-weight: bold; text-align:right"><a href="/world-population/uganda-population/">46,605,509</a> </td>)
(2067, <td data-continent="Africa" style="display:none">Africa</td>)
(2068, <td>1,169</td>)
(2069, <td>142,524</td>)
(2070, <td>55</td>)
(2071, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">102</td>)
(2072, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/namibia/">Namibia</a></td>)
(2073, <td style="font-weight: bold; text-align:right">35,201</td>)
(2074, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+131</td>)
(2075, <td style="font-weight: bold; text-align:right;">377 </td>)
(2076, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+2</td>)
(2077, <td style="font-weight: bold; text-align:right">33,675</td>)
(2078, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+102</td>)
(2079, <td style="text-align:right;font-weight:bold;">1,149</td>)
(2080, <td style="font-weight: bold; text-align:right">14</td>)
(2081, <td style="font-weight: bold; text-align:right">13,704</td>)
(2082, <td style="font-weight: bold; text-align:right">147</td>)
(2083, <td style="font-weight: bold; text-align:right">276,865</td>)
(2084, <td style="font-weight: bold; text-align:right">107,785</td>)
(2085, <td style="font-weight: bold; text-align:right"><a href="/world-population/namibia-population/">2,568,680</a> </td>)

(3541, <td style="font-weight: bold; text-align:right;"></td>)
(3542, <td style="text-align:right;font-weight:bold;">390</td>)
(3543, <td style="font-weight: bold; text-align:right"></td>)
(3544, <td style="font-weight: bold; text-align:right">15,955</td>)
(3545, <td style="font-weight: bold; text-align:right">71</td>)
(3546, <td style="font-weight: bold; text-align:right">5,200</td>)
(3547, <td style="font-weight: bold; text-align:right">52,676</td>)
(3548, <td style="font-weight: bold; text-align:right"><a href="/world-population/seychelles-population/">98,717</a> </td>)
(3549, <td data-continent="Africa" style="display:none">Africa</td>)
(3550, <td>63</td>)
(3551, <td>14,102</td>)
(3552, <td>19</td>)
(3553, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">180</td>)
(3554, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/sao-tome-and-principe/">Sao Tome and Principe</a></td>)
(3555, <td style="font-weight: bold; text-align:right">1,385</td>)
(3556, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+30</td>)
(3557, <td style="font-weight: bold; text-align:right;">18 </td>)
(3558, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(3559, <td style="font-weight: bold; text-align:right">1,077</td>)
(3560, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+10</td>)
(3561, <td style="text-align:right;font-weight:bold;">290</td>)
(3562, <td style="font-weight: bold; text-align:right"></td>)
(3563, <td style="font-weight: bold; text-align:right">6,250</td>)
(3564, <td style="font-weight: bold; text-align:right">81</td>)
(3565, <td style="font-weight: bold; text-align:right">11,592</td>)
(3566, <td style="font-weight: bold; text-align:right">52,307</td>)
(3567, <td style="font-weight: bold; text-align:right"><a href="/world-population/sao-tome-and-principe-population/">221,615</a> </td>)
(3568, <td data-continent="Africa" style="display:none">Africa</td>)
(3569, <td>160</td>)
(3570, <td>12,312</td>)
(3571, <td>19</td>)
(3572, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">181</td>)
(3573, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/saint-vincent-and-the-grenadines/">St. Vincent Grenadines</a></td>)
(3574, <td style="font-weight: bold; text-align:right">1,283</td>)
(3575, <td style="font-weight: bold; text-align:right;"></td>)
(3576, <td style="font-weight: bold; text-align:right;">4 </td>)
(3577, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(3578, <td style="font-weight: bold; text-align:right">415</td>)
(3579, <td style="font-weight: bold; text-align:right;"></td>)
(3580, <td style="text-align:right;font-weight:bold;">864</td>)
(3581, <td style="font-weight: bold; text-align:right">2</td>)
(3582, <td style="font-weight: bold; text-align:right">11,542</td>)
(3583, <td style="font-weight: bold; text-align:right">36</td>)
(3584, <td style="font-weight: bold; text-align:right">31,013</td>)
(3585, <td style="font-weight: bold; text-align:right">279,007</td>)
(3586, <td style="font-weight: bold; text-align:right"><a href="/world-population/saint-vincent-and-the-grenadines-population/">111,155</a> </td>)
(3587, <td data-continent="North America" style="display:none">North America</td>)
(3588, <td>87</td>)
(3589, <td>27,789</td>)
(3590, <td>4</td>)
(3591, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">182</td>)
(3592, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/saint-martin/">Saint Martin</a></td>)
(3593, <td style="font-weight: bold; text-align:right">1,234</td>)
(3594, <td style="font-weight: bold; text-align:right;"></td>)
(3595, <td style="font-weight: bold; text-align:right;">12 </td>)
(3596, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(3597, <td style="font-weight: bold; text-align:right">1,050</td>)
(3598, <td style="font-weight: bold; text-align:right;"></td>)
(3599, <td style="text-align:right;font-weight:bold;">172</td>)
(3600, <td style="font-weight: bold; text-align:right">7</td>)
(3601, <td style="font-weight: bold; text-align:right">31,589</td>)
(3602, <td style="font-weight: bold; text-align:right">307</td>)
(3603, <td style="font-weight: bold; text-align:right">12,433</td>)
(3604, <td style="font-weight: bold; text-align:right">318,273</td>)
(3605, <td style="font-weight: bold; text-align:right"><a href="/world-population/saint-martin-population/">39,064</a> </td>)
(3606, <td data-continent="North America" style="display:none">North America</td>)
(3607, <td>32</td>)
(3608, <td>3,255</td>)
(3609, <td>3</td>)
(3610, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">183</td>)
(3611, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/taiwan/">Taiwan</a></td>)
(3612, <td style="font-weight: bold; text-align:right">933</td>)
(3613, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+5</td>)
(3614, <td style="font-weight: bold; text-align:right;">9 </td>)
(3615, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(3616, <td style="font-weight: bold; text-align:right">850</td>)
(3617, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+2</td>)
(3618, <td style="text-align:right;font-weight:bold;">74</td>)
(3619, <td style="font-weight: bold; text-align:right"></td>)
(3620, <td style="font-weight: bold; text-align:right">39</td>)
(3621, <td style="font-weight: bold; text-align:right">0.4</td>)
(3622, <td style="font-weight: bold; text-align:right">165,840</td>)
(3623, <td style="font-weight: bold; text-align:right">6,955</td>)
(3624, <td style="font-weight: bold; text-align:right"><a href="/world-population/taiwan-population/">23,843,040</a> </td>)
(3625, <td data-continent="Asia" style="display:none">Asia</td>)
(3626, <td>25,555</td>)
(3627, <td>2,649,227</td>)
(3628, <td>144</td>)
(3629, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">184</td>)
(3630, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/papua-new-guinea/">Papua New Guinea</a></td>)
(3631, <td style="font-weight: bold; text-align:right">900</td>)
(3632, <td style="font-weight: bold; text-align:right;"></td>)
(3633, <td style="font-weight: bold; text-align:right;">9 </td>)
(3634, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(3635, <td style="font-weight: bold; text-align:right">846</td>)
(3636, <td style="font-weight: bold; text-align:right;"></td>)
(3637, <td style="text-align:right;font-weight:bold;">45</td>)
(3638, <td style="font-weight: bold; text-align:right"></td>)
(3639, <td style="font-weight: bold; text-align:right">99</td>)
(3640, <td style="font-weight: bold; text-align:right">1.0</td>)
(3641, <td style="font-weight: bold; text-align:right">43,728</td>)
(3642, <td style="font-weight: bold; text-align:right">4,832</td>)
(3643, <td style="font-weight: bold; text-align:right"><a href="/world-population/papua-new-guinea-population/">9,049,270</a> </td>)
(3644, <td data-continent="Australia/Oceania" style="display:none">Australia/Oceania</td>)
(3645, <td>10,055</td>)
(3646, <td>1,005,474</td>)
(3647, <td>207</td>)
(3648, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">185</td>)
(3649, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/bhutan/">Bhutan</a></td>)
(3650, <td style="font-weight: bold; text-align:right">861</td>)
(3651, <td style="font-weight: bold; text-align:right;"></td>)
(3652, <td style="font-weight: bold; text-align:right;">1 </td>)
(3653, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(3654, <td style="font-weight: bold; text-align:right">854</td>)
(3655, <td style="font-weight: bold; text-align:right;"></td>)
(3656, <td style="text-align:right;font-weight:bold;">6</td>)
(3657, <td style="font-weight: bold; text-align:right"></td>)
(3658, <td style="font-weight: bold; text-align:right">1,108</td>)
(3659, <td style="font-weight: bold; text-align:right">1</td>)
(3660, <td style="font-weight: bold; text-align:right">490,461</td>)
(3661, <td style="font-weight: bold; text-align:right">631,421</td>)
(3662, <td style="font-weight: bold; text-align:right"><a href="/world-population/bhutan-population/">776,758</a> </td>)
(3663, <td data-continent="Asia" style="display:none">Asia</td>)
(3664, <td>902</td>)
(3665, <td>776,758</td>)
(3666, <td>2</td>)
(3667, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">186</td>)
(3668, <td style="font-weight: bold; font-size:15px; text-align:left;"><span style="color:#00B5F0; font-style:italic; ">Diamond Princess</span></td>)
(3669, <td style="font-weight: bold; text-align:right">712</td>)
(3670, <td style="font-weight: bold; text-align:right;"></td>)
(3671, <td style="font-weight: bold; text-align:right;">13 </td>)
(3672, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(3673, <td style="font-weight: bold; text-align:right">699</td>)
(3674, <td style="font-weight: bold; text-align:right;"></td>)
(3675, <td style="text-align:right;font-weight:bold;">0</td>)
(3676, <td style="font-weight: bold; text-align:right"></td>)
(3677, <td style="font-weight: bold; text-align:right"></td>)
(3678, <td style="font-weight: bold; text-align:right"></td>)
(3679, <td style="font-weight: bold; text-align:right"></td>)
(3680, <td style="font-weight: bold; text-align:right"></td>)
(3681, <td style="font-weight: bold; text-align:right"> </td>)
(3682, <td data-continent="" style="display:none"></td>)
(3683, <td></td>)
(3684, <td></td>)
(3685, <td></td>)
(3686, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">187</td>)
(3687, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/bermuda/">Bermuda</a></td>)
(3688, <td style="font-weight: bold; text-align:right">694</td>)
(3689, <td style="font-weight: bold; text-align:right;"></td>)
(3690, <td style="font-weight: bold; text-align:right;">12 </td>)
(3691, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(3692, <td style="font-weight: bold; text-align:right">671</td>)
(3693, <td style="font-weight: bold; text-align:right;"></td>)
(3694, <td style="text-align:right;font-weight:bold;">11</td>)
(3695, <td style="font-weight: bold; text-align:right">5</td>)
(3696, <td style="font-weight: bold; text-align:right">11,169</td>)
(3697, <td style="font-weight: bold; text-align:right">193</td>)
(3698, <td style="font-weight: bold; text-align:right">167,337</td>)
(3699, <td style="font-weight: bold; text-align:right">2,693,033</td>)
(3700, <td style="font-weight: bold; text-align:right"><a href="/world-population/bermuda-population/">62,137</a> </td>)
(3701, <td data-continent="North America" style="display:none">North America</td>)
(3702, <td>90</td>)
(3703, <td>5,178</td>)
(3704, <td>0</td>)
(3705, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">188</td>)
(3706, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/faeroe-islands/">Faeroe Islands</a></td>)
(3707, <td style="font-weight: bold; text-align:right">657</td>)
(3708, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+1</td>)
(3709, <td style="font-weight: bold; text-align:right;">1 </td>)
(3710, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(3711, <td style="font-weight: bold; text-align:right">652</td>)
(3712, <td style="font-weight: bold; text-align:right;"></td>)
(3713, <td style="text-align:right;font-weight:bold;">4</td>)
(3714, <td style="font-weight: bold; text-align:right">1</td>)
(3715, <td style="font-weight: bold; text-align:right">13,415</td>)
(3716, <td style="font-weight: bold; text-align:right">20</td>)
(3717, <td style="font-weight: bold; text-align:right">225,163</td>)
(3718, <td style="font-weight: bold; text-align:right">4,597,415</td>)
(3719, <td style="font-weight: bold; text-align:right"><a href="/world-population/faeroe-islands-population/">48,976</a> </td>)
(3720, <td data-continent="Europe" style="display:none">Europe</td>)
(3721, <td>75</td>)
(3722, <td>48,976</td>)
(3723, <td>0</td>)
(3724, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">189</td>)
(3725, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/mauritius/">Mauritius</a></td>)
(3726, <td style="font-weight: bold; text-align:right">593</td>)
(3727, <td style="font-weight: bold; text-align:right;"></td>)
(3728, <td style="font-weight: bold; text-align:right;">10 </td>)
(3729, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(3730, <td style="font-weight: bold; text-align:right">543</td>)
(3731, <td style="font-weight: bold; text-align:right;"></td>)
(3732, <td style="text-align:right;font-weight:bold;">40</td>)
(3733, <td style="font-weight: bold; text-align:right"></td>)
(3734, <td style="font-weight: bold; text-align:right">466</td>)
(3735, <td style="font-weight: bold; text-align:right">8</td>)
(3736, <td style="font-weight: bold; text-align:right">289,552</td>)
(3737, <td style="font-weight: bold; text-align:right">227,447</td>)
(3738, <td style="font-weight: bold; text-align:right"><a href="/world-population/mauritius-population/">1,273,054</a> </td>)
(3739, <td data-continent="Africa" style="display:none">Africa</td>)
(3740, <td>2,147</td>)
(3741, <td>127,305</td>)
(3742, <td>4</td>)
(3743, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">190</td>)
(3744, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/tanzania/">Tanzania</a></td>)
(3745, <td style="font-weight: bold; text-align:right">509</td>)
(3746, <td style="font-weight: bold; text-align:right;"></td>)
(3747, <td style="font-weight: bold; text-align:right;">21 </td>)
(3748, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(3749, <td style="font-weight: bold; text-align:right">183</td>)
(3750, <td style="font-weight: bold; text-align:right;"></td>)
(3751, <td style="text-align:right;font-weight:bold;">305</td>)
(3752, <td style="font-weight: bold; text-align:right">7</td>)
(3753, <td style="font-weight: bold; text-align:right">8</td>)
(3754, <td style="font-weight: bold; text-align:right">0.3</td>)
(3755, <td style="font-weight: bold; text-align:right"></td>)
(3756, <td style="font-weight: bold; text-align:right"></td>)
(3757, <td style="font-weight: bold; text-align:right"><a href="/world-population/tanzania-population/">60,754,500</a> </td>)
(3758, <td data-continent="Africa" style="display:none">Africa</td>)
(3759, <td>119,361</td>)
(3760, <td>2,893,071</td>)
(3761, <td></td>)
(3762, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">191</td>)
(3763, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/cambodia/">Cambodia</a></td>)
(3764, <td style="font-weight: bold; text-align:right">476</td>)
(3765, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+2</td>)
(3766, <td style="font-weight: bold; text-align:right;"> </td>)
(3767, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(3768, <td style="font-weight: bold; text-align:right">457</td>)
(3769, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+3</td>)
(3770, <td style="text-align:right;font-weight:bold;">19</td>)
(3771, <td style="font-weight: bold; text-align:right"></td>)
(3772, <td style="font-weight: bold; text-align:right">28</td>)
(3773, <td style="font-weight: bold; text-align:right"></td>)
(3774, <td style="font-weight: bold; text-align:right">421,701</td>)
(3775, <td style="font-weight: bold; text-align:right">25,013</td>)
(3776, <td style="font-weight: bold; text-align:right"><a href="/world-population/cambodia-population/">16,858,991</a> </td>)
(3777, <td data-continent="Asia" style="display:none">Asia</td>)
(3778, <td>35,418</td>)
(3779, <td></td>)
(3780, <td>40</td>)
(3781, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">192</td>)
(3782, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/isle-of-man/">Isle of Man</a></td>)
(3783, <td style="font-weight: bold; text-align:right">436</td>)
(3784, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+1</td>)
(3785, <td style="font-weight: bold; text-align:right;">25 </td>)
(3786, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(3787, <td style="font-weight: bold; text-align:right">406</td>)
(3788, <td style="font-weight: bold; text-align:right;"></td>)
(3789, <td style="text-align:right;font-weight:bold;">5</td>)
(3790, <td style="font-weight: bold; text-align:right"></td>)
(3791, <td style="font-weight: bold; text-align:right">5,111</td>)
(3792, <td style="font-weight: bold; text-align:right">293</td>)
(3793, <td style="font-weight: bold; text-align:right">29,307</td>)
(3794, <td style="font-weight: bold; text-align:right">343,547</td>)
(3795, <td style="font-weight: bold; text-align:right"><a href="/world-population/isle-of-man-population/">85,307</a> </td>)
(3796, <td data-continent="Europe" style="display:none">Europe</td>)
(3797, <td>196</td>)
(3798, <td>3,412</td>)
(3799, <td>3</td>)
(3800, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">193</td>)
(3801, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/cayman-islands/">Cayman Islands</a></td>)
(3802, <td style="font-weight: bold; text-align:right">408</td>)
(3803, <td style="font-weight: bold; text-align:right;"></td>)
(3804, <td style="font-weight: bold; text-align:right;">2 </td>)
(3805, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(3806, <td style="font-weight: bold; text-align:right">370</td>)
(3807, <td style="font-weight: bold; text-align:right;"></td>)
(3808, <td style="text-align:right;font-weight:bold;">36</td>)
(3809, <td style="font-weight: bold; text-align:right">1</td>)
(3810, <td style="font-weight: bold; text-align:right">6,164</td>)
(3811, <td style="font-weight: bold; text-align:right">30</td>)
(3812, <td style="font-weight: bold; text-align:right">69,003</td>)
(3813, <td style="font-weight: bold; text-align:right">1,042,499</td>)
(3814, <td style="font-weight: bold; text-align:right"><a href="/world-population/cayman-islands-population/">66,190</a> </td>)
(3815, <td data-continent="North America" style="display:none">North America</td>)
(3816, <td>162</td>)
(3817, <td>33,095</td>)
(3818, <td>1</td>)
(3819, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">194</td>)
(3820, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/caribbean-netherlands/">Caribbean Netherlands</a></td>)
(3821, <td style="font-weight: bold; text-align:right">360</td>)
(3822, <td style="font-weight: bold; text-align:right;"></td>)
(3823, <td style="font-weight: bold; text-align:right;">3 </td>)
(3824, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(3825, <td style="font-weight: bold; text-align:right">244</td>)
(3826, <td style="font-weight: bold; text-align:right;"></td>)

(5011, <td style="font-weight: bold; text-align:right"><a href="/world-population/peru-population/">33,249,795</a> </td>)
(5012, <td data-continent="South America" style="display:none">South America</td>)
(5013, <td>28</td>)
(5014, <td>783</td>)
(5015, <td>5</td>)
(5016, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">20</td>)
(5017, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/indonesia/">Indonesia</a></td>)
(5018, <td style="font-weight: bold; text-align:right">1,166,079</td>)
(5019, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+8,242</td>)
(5020, <td style="font-weight: bold; text-align:right;">31,763 </td>)
(5021, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+207</td>)
(5022, <td style="font-weight: bold; text-align:right">963,028</td>)
(5023, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+13,038</td>)
(5024, <td style="text-align:right;font-weight:bold;">171,288</td>)
(5025, <td style="font-weight: bold; text-align:right"></td>)
(5026, <td style="font-weight: bold; text-align:right">4,236</td>)
(5027, <td style="font-weight: bold; text-align:right">115</td>)
(5028, <td style="font-weight: bold; text-align:right">9,724,040</td>)
(5029, <td style="font-weight: bold; text-align:right">35,325</td>)
(5030, <td style="font-weight: bold; text-align:right"><a href="/world-population/indonesia-population/">275,277,348</a> </td>)
(5031, <td data-continent="Asia" style="display:none">Asia</td>)
(5032, <td>236</td>)
(5033, <td>8,667</td>)
(5034, <td>28</td>)
(5035, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">21</td>)
(5036, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/czech-republic/">Czechia</a></td>)
(5037, <td style="font-weight: bold; text-align:right">1,037,469</td>)
(5038, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+2,449</td>)
(5039, <td style="font-weight: bold; text-align:right;">17,430 </td>)
(5040, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+107</td>)
(5041, <td style="font-weight: bold; text-align:right">931,681</td>)
(5042, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+299</td>)
(5043, <td style="text-align:right;font-weight:bold;">88,358</td>)
(5044, <td style="font-weight: bold; text-align:right">986</td>)
(5045, <td style="font-weight: bold; text-align:right">96,769</td>)
(5046, <td style="font-weight: bold; text-align:right">1,626</td>)
(5047, <td style="font-weight: bold; text-align:right">6,569,337</td>)
(5048, <td style="font-weight: bold; text-align:right">612,749</td>)
(5049, <td style="font-weight: bold; text-align:right"><a href="/world-population/czech-republic-population/">10,721,086</a> </td>)
(5050, <td data-continent="Europe" style="display:none">Europe</td>)
(5051, <td>10</td>)
(5052, <td>615</td>)
(5053, <td>2</td>)
(5054, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">22</td>)
(5055, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/netherlands/">Netherlands</a></td>)
(5056, <td style="font-weight: bold; text-align:right">1,007,981</td>)
(5057, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+2,221</td>)
(5058, <td style="font-weight: bold; text-align:right;">14,428 </td>)
(5059, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+25</td>)
(5060, <td style="font-weight: bold; text-align:right">N/A</td>)
(5061, <td style="font-weight: bold; text-align:right;">N/A</td>)
(5062, <td style="text-align:right;font-weight:bold;">N/A</td>)
(5063, <td style="font-weight: bold; text-align:right">542</td>)
(5064, <td style="font-weight: bold; text-align:right">58,747</td>)
(5065, <td style="font-weight: bold; text-align:right">841</td>)
(5066, <td style="font-weight: bold; text-align:right">6,970,400</td>)
(5067, <td style="font-weight: bold; text-align:right">406,249</td>)
(5068, <td style="font-weight: bold; text-align:right"><a href="/world-population/netherlands-population/">17,157,967</a> </td>)
(5069, <td data-continent="Europe" style="display:none">Europe</td>)
(5070, <td>17</td>)
(5071, <td>1,189</td>)
(5072, <td>2</td>)
(5073, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">23</td>)
(5074, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/canada/">Canada</a></td>)
(5075, <td style="font-weight: bold; text-align:right">808,120</td>)
(5076, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+3,860</td>)
(5077, <td style="font-weight: bold; text-align:right;">20,835 </td>)
(5078, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+68</td>)
(5079, <td style="font-weight: bold; text-align:right">747,110</td>)
(5080, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+8,344</td>)
(5081, <td style="text-align:right;font-weight:bold;">40,175</td>)
(5082, <td style="font-weight: bold; text-align:right">713</td>)
(5083, <td style="font-weight: bold; text-align:right">21,298</td>)
(5084, <td style="font-weight: bold; text-align:right">549</td>)
(5085, <td style="font-weight: bold; text-align:right">22,340,714</td>)
(5086, <td style="font-weight: bold; text-align:right">588,797</td>)
(5087, <td style="font-weight: bold; text-align:right"><a href="/world-population/canada-population/">37,943,010</a> </td>)
(5088, <td data-continent="North America" style="display:none">North America</td>)
(5089, <td>47</td>)
(5090, <td>1,821</td>)
(5091, <td>2</td>)
(5092, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">24</td>)
(5093, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/portugal/">Portugal</a></td>)
(5094, <td style="font-weight: bold; text-align:right">767,919</td>)
(5095, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+2,505</td>)
(5096, <td style="font-weight: bold; text-align:right;">14,354 </td>)
(5097, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+196</td>)
(5098, <td style="font-weight: bold; text-align:right">612,921</td>)
(5099, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+6,755</td>)
(5100, <td style="text-align:right;font-weight:bold;">140,644</td>)
(5101, <td style="font-weight: bold; text-align:right">877</td>)
(5102, <td style="font-weight: bold; text-align:right">75,445</td>)
(5103, <td style="font-weight: bold; text-align:right">1,410</td>)
(5104, <td style="font-weight: bold; text-align:right">7,624,184</td>)
(5105, <td style="font-weight: bold; text-align:right">749,044</td>)
(5106, <td style="font-weight: bold; text-align:right"><a href="/world-population/portugal-population/">10,178,550</a> </td>)
(5107, <td data-continent="Europe" style="display:none">Europe</td>)
(5108, <td>13</td>)
(5109, <td>709</td>)
(5110, <td>1</td>)
(5111, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">25</td>)
(5112, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/chile/">Chile</a></td>)
(5113, <td style="font-weight: bold; text-align:right">755,350</td>)
(5114, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+3,464</td>)
(5115, <td style="font-weight: bold; text-align:right;">19,056 </td>)
(5116, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+82</td>)
(5117, <td style="font-weight: bold; text-align:right">713,711</td>)
(5118, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+3,682</td>)
(5119, <td style="text-align:right;font-weight:bold;">22,583</td>)
(5120, <td style="font-weight: bold; text-align:right">1,506</td>)
(5121, <td style="font-weight: bold; text-align:right">39,309</td>)
(5122, <td style="font-weight: bold; text-align:right">992</td>)
(5123, <td style="font-weight: bold; text-align:right">8,439,282</td>)
(5124, <td style="font-weight: bold; text-align:right">439,184</td>)
(5125, <td style="font-weight: bold; text-align:right"><a href="/world-population/chile-population/">19,215,810</a> </td>)
(5126, <td data-continent="South America" style="display:none">South America</td>)
(5127, <td>25</td>)
(5128, <td>1,008</td>)
(5129, <td>2</td>)
(5130, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">26</td>)
(5131, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/romania/">Romania</a></td>)
(5132, <td style="font-weight: bold; text-align:right">746,637</td>)
(5133, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+1,319</td>)
(5134, <td style="font-weight: bold; text-align:right;">18,961 </td>)
(5135, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+80</td>)
(5136, <td style="font-weight: bold; text-align:right">692,681</td>)
(5137, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+1,304</td>)
(5138, <td style="text-align:right;font-weight:bold;">34,995</td>)
(5139, <td style="font-weight: bold; text-align:right">958</td>)
(5140, <td style="font-weight: bold; text-align:right">38,970</td>)
(5141, <td style="font-weight: bold; text-align:right">990</td>)
(5142, <td style="font-weight: bold; text-align:right">5,587,941</td>)
(5143, <td style="font-weight: bold; text-align:right">291,659</td>)
(5144, <td style="font-weight: bold; text-align:right"><a href="/world-population/romania-population/">19,159,162</a> </td>)
(5145, <td data-continent="Europe" style="display:none">Europe</td>)
(5146, <td>26</td>)
(5147, <td>1,010</td>)
(5148, <td>3</td>)
(5149, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">27</td>)
(5150, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/belgium/">Belgium</a></td>)
(5151, <td style="font-weight: bold; text-align:right">725,610</td>)
(5152, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+1,740</td>)
(5153, <td style="font-weight: bold; text-align:right;">21,389 </td>)
(5154, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+37</td>)
(5155, <td style="font-weight: bold; text-align:right">49,911</td>)
(5156, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+174</td>)
(5157, <td style="text-align:right;font-weight:bold;">654,310</td>)
(5158, <td style="font-weight: bold; text-align:right">292</td>)
(5159, <td style="font-weight: bold; text-align:right">62,443</td>)
(5160, <td style="font-weight: bold; text-align:right">1,841</td>)
(5161, <td style="font-weight: bold; text-align:right">8,599,012</td>)
(5162, <td style="font-weight: bold; text-align:right">739,998</td>)
(5163, <td style="font-weight: bold; text-align:right"><a href="/world-population/belgium-population/">11,620,313</a> </td>)
(5164, <td data-continent="Europe" style="display:none">Europe</td>)
(5165, <td>16</td>)
(5166, <td>543</td>)
(5167, <td>1</td>)
(5168, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">28</td>)
(5169, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/israel/">Israel</a></td>)
(5170, <td style="font-weight: bold; text-align:right">696,528</td>)
(5171, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+7,189</td>)
(5172, <td style="font-weight: bold; text-align:right;">5,171 </td>)
(5173, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+58</td>)
(5174, <td style="font-weight: bold; text-align:right">623,313</td>)
(5175, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+4,987</td>)
(5176, <td style="text-align:right;font-weight:bold;">68,044</td>)
(5177, <td style="font-weight: bold; text-align:right">1,097</td>)
(5178, <td style="font-weight: bold; text-align:right">75,729</td>)
(5179, <td style="font-weight: bold; text-align:right">562</td>)
(5180, <td style="font-weight: bold; text-align:right">11,029,383</td>)
(5181, <td style="font-weight: bold; text-align:right">1,199,160</td>)
(5182, <td style="font-weight: bold; text-align:right">9,197,590 </td>)
(5183, <td data-continent="Asia" style="display:none">Asia</td>)
(5184, <td>13</td>)
(5185, <td>1,779</td>)
(5186, <td>1</td>)
(5187, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">29</td>)
(5188, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/iraq/">Iraq</a></td>)
(5189, <td style="font-weight: bold; text-align:right">630,263</td>)
(5190, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+1,713</td>)
(5191, <td style="font-weight: bold; text-align:right;">13,126 </td>)
(5192, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+6</td>)
(5193, <td style="font-weight: bold; text-align:right">601,041</td>)
(5194, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+848</td>)
(5195, <td style="text-align:right;font-weight:bold;">16,096</td>)
(5196, <td style="font-weight: bold; text-align:right">195</td>)
(5197, <td style="font-weight: bold; text-align:right">15,461</td>)
(5198, <td style="font-weight: bold; text-align:right">322</td>)
(5199, <td style="font-weight: bold; text-align:right">5,974,504</td>)
(5200, <td style="font-weight: bold; text-align:right">146,557</td>)
(5201, <td style="font-weight: bold; text-align:right"><a href="/world-population/iraq-population/">40,765,829</a> </td>)
(5202, <td data-continent="Asia" style="display:none">Asia</td>)
(5203, <td>65</td>)
(5204, <td>3,106</td>)
(5205, <td>7</td>)
(5206, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">30</td>)
(5207, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/sweden/">Sweden</a></td>)
(5208, <td style="font-weight: bold; text-align:right">596,174</td>)
(5209, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+1,512</td>)
(5210, <td style="font-weight: bold; text-align:right;">12,148 </td>)
(5211, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+2</td>)
(5212, <td style="font-weight: bold; text-align:right">N/A</td>)
(5213, <td style="font-weight: bold; text-align:right;">N/A</td>)
(5214, <td style="text-align:right;font-weight:bold;">N/A</td>)
(5215, <td style="font-weight: bold; text-align:right">237</td>)
(5216, <td style="font-weight: bold; text-align:right">58,809</td>)
(5217, <td style="font-weight: bold; text-align:right">1,198</td>)
(5218, <td style="font-weight: bold; text-align:right">5,499,317</td>)
(5219, <td style="font-weight: bold; text-align:right">542,470</td>)
(5220, <td style="font-weight: bold; text-align:right"><a href="/world-population/sweden-population/">10,137,542</a> </td>)
(5221, <td data-continent="Europe" style="display:none">Europe</td>)
(5222, <td>17</td>)
(5223, <td>835</td>)
(5224, <td>2</td>)
(5225, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">31</td>)
(5226, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/pakistan/">Pakistan</a></td>)
(5227, <td style="font-weight: bold; text-align:right">555,511</td>)
(5228, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+1,037</td>)
(5229, <td style="font-weight: bold; text-align:right;">12,026 </td>)
(5230, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+59</td>)
(5231, <td style="font-weight: bold; text-align:right">511,502</td>)
(5232, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+1,260</td>)
(5233, <td style="text-align:right;font-weight:bold;">31,983</td>)
(5234, <td style="font-weight: bold; text-align:right">1,828</td>)
(5235, <td style="font-weight: bold; text-align:right">2,486</td>)
(5236, <td style="font-weight: bold; text-align:right">54</td>)
(5237, <td style="font-weight: bold; text-align:right">8,224,869</td>)
(5238, <td style="font-weight: bold; text-align:right">36,804</td>)
(5239, <td style="font-weight: bold; text-align:right"><a href="/world-population/pakistan-population/">223,479,174</a> </td>)
(5240, <td data-continent="Asia" style="display:none">Asia</td>)
(5241, <td>402</td>)
(5242, <td>18,583</td>)
(5243, <td>27</td>)
(5244, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">32</td>)
(5245, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/philippines/">Philippines</a></td>)
(5246, <td style="font-weight: bold; text-align:right">538,992</td>)
(5247, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+1,687</td>)
(5248, <td style="font-weight: bold; text-align:right;">11,231 </td>)
(5249, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+52</td>)
(5250, <td style="font-weight: bold; text-align:right">499,711</td>)
(5251, <td style="font-weight: bold; text-align:right;"></td>)
(5252, <td style="text-align:right;font-weight:bold;">28,050</td>)
(5253, <td style="font-weight: bold; text-align:right">807</td>)
(5254, <td style="font-weight: bold; text-align:right">4,879</td>)
(5255, <td style="font-weight: bold; text-align:right">102</td>)
(5256, <td style="font-weight: bold; text-align:right">8,104,575</td>)
(5257, <td style="font-weight: bold; text-align:right">73,368</td>)
(5258, <td style="font-weight: bold; text-align:right"><a href="/world-population/philippines-population/">110,463,998</a> </td>)
(5259, <td data-continent="Asia" style="display:none">Asia</td>)
(5260, <td>205</td>)
(5261, <td>9,836</td>)
(5262, <td>14</td>)
(5263, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">33</td>)
(5264, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/bangladesh/">Bangladesh</a></td>)
(5265, <td style="font-weight: bold; text-align:right">538,378</td>)
(5266, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+316</td>)
(5267, <td style="font-weight: bold; text-align:right;">8,221 </td>)
(5268, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+16</td>)
(5269, <td style="font-weight: bold; text-align:right">483,931</td>)
(5270, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+559</td>)
(5271, <td style="text-align:right;font-weight:bold;">46,226</td>)
(5272, <td style="font-weight: bold; text-align:right"></td>)
(5273, <td style="font-weight: bold; text-align:right">3,249</td>)
(5274, <td style="font-weight: bold; text-align:right">50</td>)
(5275, <td style="font-weight: bold; text-align:right">3,762,774</td>)
(5276, <td style="font-weight: bold; text-align:right">22,710</td>)
(5277, <td style="font-weight: bold; text-align:right"><a href="/world-population/bangladesh-population/">165,684,589</a> </td>)

(6848, <td style="text-align:right;font-weight:bold;">1,041</td>)
(6849, <td style="font-weight: bold; text-align:right">9</td>)
(6850, <td style="font-weight: bold; text-align:right">601</td>)
(6851, <td style="font-weight: bold; text-align:right">14</td>)
(6852, <td style="font-weight: bold; text-align:right">176,910</td>)
(6853, <td style="font-weight: bold; text-align:right">5,284</td>)
(6854, <td style="font-weight: bold; text-align:right"><a href="/world-population/angola-population/">33,478,303</a> </td>)
(6855, <td data-continent="Africa" style="display:none">Africa</td>)
(6856, <td>1,665</td>)
(6857, <td>70,481</td>)
(6858, <td>189</td>)
(6859, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">117</td>)
(6860, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/madagascar/">Madagascar</a></td>)
(6861, <td style="font-weight: bold; text-align:right">19,360</td>)
(6862, <td style="font-weight: bold; text-align:right;"></td>)
(6863, <td style="font-weight: bold; text-align:right;">285 </td>)
(6864, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(6865, <td style="font-weight: bold; text-align:right">18,490</td>)
(6866, <td style="font-weight: bold; text-align:right;"></td>)
(6867, <td style="text-align:right;font-weight:bold;">585</td>)
(6868, <td style="font-weight: bold; text-align:right">16</td>)
(6869, <td style="font-weight: bold; text-align:right">689</td>)
(6870, <td style="font-weight: bold; text-align:right">10</td>)
(6871, <td style="font-weight: bold; text-align:right">114,282</td>)
(6872, <td style="font-weight: bold; text-align:right">4,064</td>)
(6873, <td style="font-weight: bold; text-align:right"><a href="/world-population/madagascar-population/">28,118,662</a> </td>)
(6874, <td data-continent="Africa" style="display:none">Africa</td>)
(6875, <td>1,452</td>)
(6876, <td>98,662</td>)
(6877, <td>246</td>)
(6878, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">118</td>)
(6879, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/malta/">Malta</a></td>)
(6880, <td style="font-weight: bold; text-align:right">18,813</td>)
(6881, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+137</td>)
(6882, <td style="font-weight: bold; text-align:right;">282 </td>)
(6883, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(6884, <td style="font-weight: bold; text-align:right">16,179</td>)
(6885, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+126</td>)
(6886, <td style="text-align:right;font-weight:bold;">2,352</td>)
(6887, <td style="font-weight: bold; text-align:right">18</td>)
(6888, <td style="font-weight: bold; text-align:right">42,538</td>)
(6889, <td style="font-weight: bold; text-align:right">638</td>)
(6890, <td style="font-weight: bold; text-align:right">636,729</td>)
(6891, <td style="font-weight: bold; text-align:right">1,439,720</td>)
(6892, <td style="font-weight: bold; text-align:right"><a href="/world-population/malta-population/">442,259</a> </td>)
(6893, <td data-continent="Europe" style="display:none">Europe</td>)
(6894, <td>24</td>)
(6895, <td>1,568</td>)
(6896, <td>1</td>)
(6897, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">119</td>)
(6898, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/french-polynesia/">French Polynesia</a></td>)
(6899, <td style="font-weight: bold; text-align:right">18,206</td>)
(6900, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+21</td>)
(6901, <td style="font-weight: bold; text-align:right;">135 </td>)
(6902, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+2</td>)
(6903, <td style="font-weight: bold; text-align:right">4,842</td>)
(6904, <td style="font-weight: bold; text-align:right;"></td>)
(6905, <td style="text-align:right;font-weight:bold;">13,229</td>)
(6906, <td style="font-weight: bold; text-align:right">5</td>)
(6907, <td style="font-weight: bold; text-align:right">64,584</td>)
(6908, <td style="font-weight: bold; text-align:right">479</td>)
(6909, <td style="font-weight: bold; text-align:right">26,355</td>)
(6910, <td style="font-weight: bold; text-align:right">93,492</td>)
(6911, <td style="font-weight: bold; text-align:right"><a href="/world-population/french-polynesia-population/">281,895</a> </td>)
(6912, <td data-continent="Australia/Oceania" style="display:none">Australia/Oceania</td>)
(6913, <td>15</td>)
(6914, <td>2,088</td>)
(6915, <td>11</td>)
(6916, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">120</td>)
(6917, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/jamaica/">Jamaica</a></td>)
(6918, <td style="font-weight: bold; text-align:right">17,298</td>)
(6919, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+213</td>)
(6920, <td style="font-weight: bold; text-align:right;">358 </td>)
(6921, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(6922, <td style="font-weight: bold; text-align:right">12,318</td>)
(6923, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+47</td>)
(6924, <td style="text-align:right;font-weight:bold;">4,622</td>)
(6925, <td style="font-weight: bold; text-align:right">16</td>)
(6926, <td style="font-weight: bold; text-align:right">5,826</td>)
(6927, <td style="font-weight: bold; text-align:right">121</td>)
(6928, <td style="font-weight: bold; text-align:right">176,807</td>)
(6929, <td style="font-weight: bold; text-align:right">59,550</td>)
(6930, <td style="font-weight: bold; text-align:right"><a href="/world-population/jamaica-population/">2,969,031</a> </td>)
(6931, <td data-continent="North America" style="display:none">North America</td>)
(6932, <td>172</td>)
(6933, <td>8,293</td>)
(6934, <td>17</td>)
(6935, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">121</td>)
(6936, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/maldives/">Maldives</a></td>)
(6937, <td style="font-weight: bold; text-align:right">16,909</td>)
(6938, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+126</td>)
(6939, <td style="font-weight: bold; text-align:right;">55 </td>)
(6940, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(6941, <td style="font-weight: bold; text-align:right">14,772</td>)
(6942, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+168</td>)
(6943, <td style="text-align:right;font-weight:bold;">2,082</td>)
(6944, <td style="font-weight: bold; text-align:right">178</td>)
(6945, <td style="font-weight: bold; text-align:right">30,952</td>)
(6946, <td style="font-weight: bold; text-align:right">101</td>)
(6947, <td style="font-weight: bold; text-align:right">438,240</td>)
(6948, <td style="font-weight: bold; text-align:right">802,208</td>)
(6949, <td style="font-weight: bold; text-align:right"><a href="/world-population/maldives-population/">546,292</a> </td>)
(6950, <td data-continent="Asia" style="display:none">Asia</td>)
(6951, <td>32</td>)
(6952, <td>9,933</td>)
(6953, <td>1</td>)
(6954, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">122</td>)
(6955, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/mauritania/">Mauritania</a></td>)
(6956, <td style="font-weight: bold; text-align:right">16,827</td>)
(6957, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+20</td>)
(6958, <td style="font-weight: bold; text-align:right;">427 </td>)
(6959, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+1</td>)
(6960, <td style="font-weight: bold; text-align:right">16,041</td>)
(6961, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+36</td>)
(6962, <td style="text-align:right;font-weight:bold;">359</td>)
(6963, <td style="font-weight: bold; text-align:right">23</td>)
(6964, <td style="font-weight: bold; text-align:right">3,563</td>)
(6965, <td style="font-weight: bold; text-align:right">90</td>)
(6966, <td style="font-weight: bold; text-align:right">152,308</td>)
(6967, <td style="font-weight: bold; text-align:right">32,248</td>)
(6968, <td style="font-weight: bold; text-align:right"><a href="/world-population/mauritania-population/">4,723,050</a> </td>)
(6969, <td data-continent="Africa" style="display:none">Africa</td>)
(6970, <td>281</td>)
(6971, <td>11,061</td>)
(6972, <td>31</td>)
(6973, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">123</td>)
(6974, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/rwanda/">Rwanda</a></td>)
(6975, <td style="font-weight: bold; text-align:right">16,621</td>)
(6976, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+170</td>)
(6977, <td style="font-weight: bold; text-align:right;">223 </td>)
(6978, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+3</td>)
(6979, <td style="font-weight: bold; text-align:right">12,629</td>)
(6980, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+287</td>)
(6981, <td style="text-align:right;font-weight:bold;">3,769</td>)
(6982, <td style="font-weight: bold; text-align:right">21</td>)
(6983, <td style="font-weight: bold; text-align:right">1,264</td>)
(6984, <td style="font-weight: bold; text-align:right">17</td>)
(6985, <td style="font-weight: bold; text-align:right">921,282</td>)
(6986, <td style="font-weight: bold; text-align:right">70,085</td>)
(6987, <td style="font-weight: bold; text-align:right"><a href="/world-population/rwanda-population/">13,145,206</a> </td>)
(6988, <td data-continent="Africa" style="display:none">Africa</td>)
(6989, <td>791</td>)
(6990, <td>58,947</td>)
(6991, <td>14</td>)
(6992, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">124</td>)
(6993, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/french-guiana/">French Guiana</a></td>)
(6994, <td style="font-weight: bold; text-align:right">16,296</td>)
(6995, <td style="font-weight: bold; text-align:right;"></td>)
(6996, <td style="font-weight: bold; text-align:right;">79 </td>)
(6997, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(6998, <td style="font-weight: bold; text-align:right">9,995</td>)
(6999, <td style="font-weight: bold; text-align:right;"></td>)
(7000, <td style="text-align:right;font-weight:bold;">6,222</td>)
(7001, <td style="font-weight: bold; text-align:right">11</td>)
(7002, <td style="font-weight: bold; text-align:right">53,723</td>)
(7003, <td style="font-weight: bold; text-align:right">260</td>)
(7004, <td style="font-weight: bold; text-align:right">138,264</td>)
(7005, <td style="font-weight: bold; text-align:right">455,817</td>)
(7006, <td style="font-weight: bold; text-align:right"><a href="/world-population/french-guiana-population/">303,332</a> </td>)
(7007, <td data-continent="South America" style="display:none">South America</td>)
(7008, <td>19</td>)
(7009, <td>3,840</td>)
(7010, <td>2</td>)
(7011, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">125</td>)
(7012, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/swaziland/">Eswatini</a></td>)
(7013, <td style="font-weight: bold; text-align:right">16,234</td>)
(7014, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+30</td>)
(7015, <td style="font-weight: bold; text-align:right;">607 </td>)
(7016, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+3</td>)
(7017, <td style="font-weight: bold; text-align:right">11,719</td>)
(7018, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+105</td>)
(7019, <td style="text-align:right;font-weight:bold;">3,908</td>)
(7020, <td style="font-weight: bold; text-align:right">67</td>)
(7021, <td style="font-weight: bold; text-align:right">13,906</td>)
(7022, <td style="font-weight: bold; text-align:right">520</td>)
(7023, <td style="font-weight: bold; text-align:right">138,957</td>)
(7024, <td style="font-weight: bold; text-align:right">119,026</td>)
(7025, <td style="font-weight: bold; text-align:right"><a href="/world-population/swaziland-population/">1,167,448</a> </td>)
(7026, <td data-continent="Africa" style="display:none">Africa</td>)
(7027, <td>72</td>)
(7028, <td>1,923</td>)
(7029, <td>8</td>)
(7030, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">126</td>)
(7031, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/guinea/">Guinea</a></td>)
(7032, <td style="font-weight: bold; text-align:right">14,764</td>)
(7033, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+77</td>)
(7034, <td style="font-weight: bold; text-align:right;">84 </td>)
(7035, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(7036, <td style="font-weight: bold; text-align:right">14,372</td>)
(7037, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+27</td>)
(7038, <td style="text-align:right;font-weight:bold;">308</td>)
(7039, <td style="font-weight: bold; text-align:right">24</td>)
(7040, <td style="font-weight: bold; text-align:right">1,106</td>)
(7041, <td style="font-weight: bold; text-align:right">6</td>)
(7042, <td style="font-weight: bold; text-align:right">125,765</td>)
(7043, <td style="font-weight: bold; text-align:right">9,423</td>)
(7044, <td style="font-weight: bold; text-align:right"><a href="/world-population/guinea-population/">13,346,593</a> </td>)
(7045, <td data-continent="Africa" style="display:none">Africa</td>)
(7046, <td>904</td>)
(7047, <td>158,888</td>)
(7048, <td>106</td>)
(7049, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">127</td>)
(7050, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/syria/">Syria</a></td>)
(7051, <td style="font-weight: bold; text-align:right">14,551</td>)
(7052, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+74</td>)
(7053, <td style="font-weight: bold; text-align:right;">958 </td>)
(7054, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+6</td>)
(7055, <td style="font-weight: bold; text-align:right">8,213</td>)
(7056, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+79</td>)
(7057, <td style="text-align:right;font-weight:bold;">5,380</td>)
(7058, <td style="font-weight: bold; text-align:right"></td>)
(7059, <td style="font-weight: bold; text-align:right">819</td>)
(7060, <td style="font-weight: bold; text-align:right">54</td>)
(7061, <td style="font-weight: bold; text-align:right"></td>)
(7062, <td style="font-weight: bold; text-align:right"></td>)
(7063, <td style="font-weight: bold; text-align:right"><a href="/world-population/syria-population/">17,756,276</a> </td>)
(7064, <td data-continent="Asia" style="display:none">Asia</td>)
(7065, <td>1,220</td>)
(7066, <td>18,535</td>)
(7067, <td></td>)
(7068, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">128</td>)
(7069, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/cabo-verde/">Cabo Verde</a></td>)
(7070, <td style="font-weight: bold; text-align:right">14,451</td>)
(7071, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+28</td>)
(7072, <td style="font-weight: bold; text-align:right;">136 </td>)
(7073, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+1</td>)
(7074, <td style="font-weight: bold; text-align:right">13,851</td>)
(7075, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+128</td>)
(7076, <td style="text-align:right;font-weight:bold;">464</td>)
(7077, <td style="font-weight: bold; text-align:right">23</td>)
(7078, <td style="font-weight: bold; text-align:right">25,822</td>)
(7079, <td style="font-weight: bold; text-align:right">243</td>)
(7080, <td style="font-weight: bold; text-align:right">113,493</td>)
(7081, <td style="font-weight: bold; text-align:right">202,794</td>)
(7082, <td style="font-weight: bold; text-align:right"><a href="/world-population/cabo-verde-population/">559,648</a> </td>)
(7083, <td data-continent="Africa" style="display:none">Africa</td>)
(7084, <td>39</td>)
(7085, <td>4,115</td>)
(7086, <td>5</td>)
(7087, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">129</td>)
(7088, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/tajikistan/">Tajikistan</a></td>)
(7089, <td style="font-weight: bold; text-align:right">13,308</td>)
(7090, <td style="font-weight: bold; text-align:right;"></td>)
(7091, <td style="font-weight: bold; text-align:right;">90 </td>)
(7092, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(7093, <td style="font-weight: bold; text-align:right">13,218</td>)
(7094, <td style="font-weight: bold; text-align:right;"></td>)
(7095, <td style="text-align:right;font-weight:bold;">0</td>)
(7096, <td style="font-weight: bold; text-align:right"></td>)
(7097, <td style="font-weight: bold; text-align:right">1,377</td>)
(7098, <td style="font-weight: bold; text-align:right">9</td>)
(7099, <td style="font-weight: bold; text-align:right"></td>)
(7100, <td style="font-weight: bold; text-align:right"></td>)
(7101, <td style="font-weight: bold; text-align:right"><a href="/world-population/tajikistan-population/">9,666,599</a> </td>)
(7102, <td data-continent="Asia" style="display:none">Asia</td>)
(7103, <td>726</td>)
(7104, <td>107,407</td>)
(7105, <td></td>)
(7106, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">130</td>)
(7107, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/belize/">Belize</a></td>)
(7108, <td style="font-weight: bold; text-align:right">12,070</td>)
(7109, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+33</td>)
(7110, <td style="font-weight: bold; text-align:right;">307 </td>)
(7111, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+1</td>)
(7112, <td style="font-weight: bold; text-align:right">11,509</td>)
(7113, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+30</td>)
(7114, <td style="text-align:right;font-weight:bold;">254</td>)
(7115, <td style="font-weight: bold; text-align:right">2</td>)
(7116, <td style="font-weight: bold; text-align:right">30,026</td>)
(7117, <td style="font-weight: bold; text-align:right">764</td>)
(7118, <td style="font-weight: bold; text-align:right">74,914</td>)
(7119, <td style="font-weight: bold; text-align:right">186,360</td>)
(7120, <td style="font-weight: bold; text-align:right"><a href="/world-population/belize-population/">401,985</a> </td>)
(7121, <td data-continent="North America" style="display:none">North America</td>)
(7122, <td>33</td>)
(7123, <td>1,309</td>)

(8475, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/timor-leste/">Timor-Leste</a></td>)
(8476, <td style="font-weight: bold; text-align:right">80</td>)
(8477, <td style="font-weight: bold; text-align:right;"></td>)
(8478, <td style="font-weight: bold; text-align:right;"> </td>)
(8479, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(8480, <td style="font-weight: bold; text-align:right">61</td>)
(8481, <td style="font-weight: bold; text-align:right;"></td>)
(8482, <td style="text-align:right;font-weight:bold;">19</td>)
(8483, <td style="font-weight: bold; text-align:right"></td>)
(8484, <td style="font-weight: bold; text-align:right">60</td>)
(8485, <td style="font-weight: bold; text-align:right"></td>)
(8486, <td style="font-weight: bold; text-align:right">19,506</td>)
(8487, <td style="font-weight: bold; text-align:right">14,627</td>)
(8488, <td style="font-weight: bold; text-align:right"><a href="/world-population/timor-leste-population/">1,333,594</a> </td>)
(8489, <td data-continent="Asia" style="display:none">Asia</td>)
(8490, <td>16,670</td>)
(8491, <td></td>)
(8492, <td>68</td>)
(8493, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">203</td>)
(8494, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/fiji/">Fiji</a></td>)
(8495, <td style="font-weight: bold; text-align:right">56</td>)
(8496, <td style="font-weight: bold; text-align:right;"></td>)
(8497, <td style="font-weight: bold; text-align:right;">2 </td>)
(8498, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(8499, <td style="font-weight: bold; text-align:right">53</td>)
(8500, <td style="font-weight: bold; text-align:right;"></td>)
(8501, <td style="text-align:right;font-weight:bold;">1</td>)
(8502, <td style="font-weight: bold; text-align:right"></td>)
(8503, <td style="font-weight: bold; text-align:right">62</td>)
(8504, <td style="font-weight: bold; text-align:right">2</td>)
(8505, <td style="font-weight: bold; text-align:right">26,510</td>)
(8506, <td style="font-weight: bold; text-align:right">29,443</td>)
(8507, <td style="font-weight: bold; text-align:right"><a href="/world-population/fiji-population/">900,391</a> </td>)
(8508, <td data-continent="Australia/Oceania" style="display:none">Australia/Oceania</td>)
(8509, <td>16,078</td>)
(8510, <td>450,196</td>)
(8511, <td>34</td>)
(8512, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">204</td>)
(8513, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/new-caledonia/">New Caledonia</a></td>)
(8514, <td style="font-weight: bold; text-align:right">49</td>)
(8515, <td style="font-weight: bold; text-align:right;"></td>)
(8516, <td style="font-weight: bold; text-align:right;"> </td>)
(8517, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(8518, <td style="font-weight: bold; text-align:right">47</td>)
(8519, <td style="font-weight: bold; text-align:right;"></td>)
(8520, <td style="text-align:right;font-weight:bold;">2</td>)
(8521, <td style="font-weight: bold; text-align:right"></td>)
(8522, <td style="font-weight: bold; text-align:right">171</td>)
(8523, <td style="font-weight: bold; text-align:right"></td>)
(8524, <td style="font-weight: bold; text-align:right">21,148</td>)
(8525, <td style="font-weight: bold; text-align:right">73,645</td>)
(8526, <td style="font-weight: bold; text-align:right"><a href="/world-population/new-caledonia-population/">287,163</a> </td>)
(8527, <td data-continent="Australia/Oceania" style="display:none">Australia/Oceania</td>)
(8528, <td>5,860</td>)
(8529, <td></td>)
(8530, <td>14</td>)
(8531, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">205</td>)
(8532, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/china-macao-sar/">Macao</a></td>)
(8533, <td style="font-weight: bold; text-align:right">48</td>)
(8534, <td style="font-weight: bold; text-align:right;"></td>)
(8535, <td style="font-weight: bold; text-align:right;"> </td>)
(8536, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(8537, <td style="font-weight: bold; text-align:right">46</td>)
(8538, <td style="font-weight: bold; text-align:right;"></td>)
(8539, <td style="text-align:right;font-weight:bold;">2</td>)
(8540, <td style="font-weight: bold; text-align:right"></td>)
(8541, <td style="font-weight: bold; text-align:right">73</td>)
(8542, <td style="font-weight: bold; text-align:right"></td>)
(8543, <td style="font-weight: bold; text-align:right">4,369</td>)
(8544, <td style="font-weight: bold; text-align:right">6,673</td>)
(8545, <td style="font-weight: bold; text-align:right"><a href="/world-population/china-macao-sar-population/">654,692</a> </td>)
(8546, <td data-continent="Asia" style="display:none">Asia</td>)
(8547, <td>13,639</td>)
(8548, <td></td>)
(8549, <td>150</td>)
(8550, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">206</td>)
(8551, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/falkland-islands-malvinas/">Falkland Islands</a></td>)
(8552, <td style="font-weight: bold; text-align:right">45</td>)
(8553, <td style="font-weight: bold; text-align:right;"></td>)
(8554, <td style="font-weight: bold; text-align:right;"> </td>)
(8555, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(8556, <td style="font-weight: bold; text-align:right">36</td>)
(8557, <td style="font-weight: bold; text-align:right;"></td>)
(8558, <td style="text-align:right;font-weight:bold;">9</td>)
(8559, <td style="font-weight: bold; text-align:right"></td>)
(8560, <td style="font-weight: bold; text-align:right">12,708</td>)
(8561, <td style="font-weight: bold; text-align:right"></td>)
(8562, <td style="font-weight: bold; text-align:right">6,878</td>)
(8563, <td style="font-weight: bold; text-align:right">1,942,389</td>)
(8564, <td style="font-weight: bold; text-align:right"><a href="/world-population/falkland-islands-malvinas-population/">3,541</a> </td>)
(8565, <td data-continent="South America" style="display:none">South America</td>)
(8566, <td>79</td>)
(8567, <td></td>)
(8568, <td>1</td>)
(8569, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">207</td>)
(8570, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/laos/">Laos</a></td>)
(8571, <td style="font-weight: bold; text-align:right">45</td>)
(8572, <td style="font-weight: bold; text-align:right;"></td>)
(8573, <td style="font-weight: bold; text-align:right;"> </td>)
(8574, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(8575, <td style="font-weight: bold; text-align:right">41</td>)
(8576, <td style="font-weight: bold; text-align:right;"></td>)
(8577, <td style="text-align:right;font-weight:bold;">4</td>)
(8578, <td style="font-weight: bold; text-align:right"></td>)
(8579, <td style="font-weight: bold; text-align:right">6</td>)
(8580, <td style="font-weight: bold; text-align:right"></td>)
(8581, <td style="font-weight: bold; text-align:right">106,497</td>)
(8582, <td style="font-weight: bold; text-align:right">14,510</td>)
(8583, <td style="font-weight: bold; text-align:right"><a href="/world-population/laos-population/">7,339,425</a> </td>)
(8584, <td data-continent="Asia" style="display:none">Asia</td>)
(8585, <td>163,098</td>)
(8586, <td></td>)
(8587, <td>69</td>)
(8588, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">208</td>)
(8589, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/saint-kitts-and-nevis/">Saint Kitts and Nevis</a></td>)
(8590, <td style="font-weight: bold; text-align:right">40</td>)
(8591, <td style="font-weight: bold; text-align:right;"></td>)
(8592, <td style="font-weight: bold; text-align:right;"> </td>)
(8593, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(8594, <td style="font-weight: bold; text-align:right">36</td>)
(8595, <td style="font-weight: bold; text-align:right;"></td>)
(8596, <td style="text-align:right;font-weight:bold;">4</td>)
(8597, <td style="font-weight: bold; text-align:right"></td>)
(8598, <td style="font-weight: bold; text-align:right">749</td>)
(8599, <td style="font-weight: bold; text-align:right"></td>)
(8600, <td style="font-weight: bold; text-align:right">8,293</td>)
(8601, <td style="font-weight: bold; text-align:right">155,218</td>)
(8602, <td style="font-weight: bold; text-align:right"><a href="/world-population/saint-kitts-and-nevis-population/">53,428</a> </td>)
(8603, <td data-continent="North America" style="display:none">North America</td>)
(8604, <td>1,336</td>)
(8605, <td></td>)
(8606, <td>6</td>)
(8607, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">209</td>)
(8608, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/greenland/">Greenland</a></td>)
(8609, <td style="font-weight: bold; text-align:right">30</td>)
(8610, <td style="font-weight: bold; text-align:right;"></td>)
(8611, <td style="font-weight: bold; text-align:right;"> </td>)
(8612, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(8613, <td style="font-weight: bold; text-align:right">30</td>)
(8614, <td style="font-weight: bold; text-align:right;"></td>)
(8615, <td style="text-align:right;font-weight:bold;">0</td>)
(8616, <td style="font-weight: bold; text-align:right"></td>)
(8617, <td style="font-weight: bold; text-align:right">528</td>)
(8618, <td style="font-weight: bold; text-align:right"></td>)
(8619, <td style="font-weight: bold; text-align:right">17,382</td>)
(8620, <td style="font-weight: bold; text-align:right">305,860</td>)
(8621, <td style="font-weight: bold; text-align:right"><a href="/world-population/greenland-population/">56,830</a> </td>)
(8622, <td data-continent="North America" style="display:none">North America</td>)
(8623, <td>1,894</td>)
(8624, <td></td>)
(8625, <td>3</td>)
(8626, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">210</td>)
(8627, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/holy-see/">Vatican City</a></td>)
(8628, <td style="font-weight: bold; text-align:right">27</td>)
(8629, <td style="font-weight: bold; text-align:right;"></td>)
(8630, <td style="font-weight: bold; text-align:right;"> </td>)
(8631, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(8632, <td style="font-weight: bold; text-align:right">15</td>)
(8633, <td style="font-weight: bold; text-align:right;"></td>)
(8634, <td style="text-align:right;font-weight:bold;">12</td>)
(8635, <td style="font-weight: bold; text-align:right"></td>)
(8636, <td style="font-weight: bold; text-align:right">33,666</td>)
(8637, <td style="font-weight: bold; text-align:right"></td>)
(8638, <td style="font-weight: bold; text-align:right"></td>)
(8639, <td style="font-weight: bold; text-align:right"></td>)
(8640, <td style="font-weight: bold; text-align:right"><a href="/world-population/holy-see-population/">802</a> </td>)
(8641, <td data-continent="Europe" style="display:none">Europe</td>)
(8642, <td>30</td>)
(8643, <td></td>)
(8644, <td></td>)
(8645, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">211</td>)
(8646, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/saint-pierre-and-miquelon/">Saint Pierre Miquelon</a></td>)
(8647, <td style="font-weight: bold; text-align:right">24</td>)
(8648, <td style="font-weight: bold; text-align:right;"></td>)
(8649, <td style="font-weight: bold; text-align:right;"> </td>)
(8650, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(8651, <td style="font-weight: bold; text-align:right">16</td>)
(8652, <td style="font-weight: bold; text-align:right;"></td>)
(8653, <td style="text-align:right;font-weight:bold;">8</td>)
(8654, <td style="font-weight: bold; text-align:right"></td>)
(8655, <td style="font-weight: bold; text-align:right">4,154</td>)
(8656, <td style="font-weight: bold; text-align:right"></td>)
(8657, <td style="font-weight: bold; text-align:right">3,729</td>)
(8658, <td style="font-weight: bold; text-align:right">645,491</td>)
(8659, <td style="font-weight: bold; text-align:right"><a href="/world-population/saint-pierre-and-miquelon-population/">5,777</a> </td>)
(8660, <td data-continent="North America" style="display:none">North America</td>)
(8661, <td>241</td>)
(8662, <td></td>)
(8663, <td>2</td>)
(8664, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">212</td>)
(8665, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/montserrat/">Montserrat</a></td>)
(8666, <td style="font-weight: bold; text-align:right">18</td>)
(8667, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+1</td>)
(8668, <td style="font-weight: bold; text-align:right;">1 </td>)
(8669, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(8670, <td style="font-weight: bold; text-align:right">13</td>)
(8671, <td style="font-weight: bold; text-align:right;"></td>)
(8672, <td style="text-align:right;font-weight:bold;">4</td>)
(8673, <td style="font-weight: bold; text-align:right"></td>)
(8674, <td style="font-weight: bold; text-align:right">3,604</td>)
(8675, <td style="font-weight: bold; text-align:right">200</td>)
(8676, <td style="font-weight: bold; text-align:right">930</td>)
(8677, <td style="font-weight: bold; text-align:right">186,223</td>)
(8678, <td style="font-weight: bold; text-align:right"><a href="/world-population/montserrat-population/">4,994</a> </td>)
(8679, <td data-continent="North America" style="display:none">North America</td>)
(8680, <td>277</td>)
(8681, <td>4,994</td>)
(8682, <td>5</td>)
(8683, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">213</td>)
(8684, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/anguilla/">Anguilla</a></td>)
(8685, <td style="font-weight: bold; text-align:right">17</td>)
(8686, <td style="font-weight: bold; text-align:right;"></td>)
(8687, <td style="font-weight: bold; text-align:right;"> </td>)
(8688, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(8689, <td style="font-weight: bold; text-align:right">15</td>)
(8690, <td style="font-weight: bold; text-align:right;"></td>)
(8691, <td style="text-align:right;font-weight:bold;">2</td>)
(8692, <td style="font-weight: bold; text-align:right"></td>)
(8693, <td style="font-weight: bold; text-align:right">1,127</td>)
(8694, <td style="font-weight: bold; text-align:right"></td>)
(8695, <td style="font-weight: bold; text-align:right">7,326</td>)
(8696, <td style="font-weight: bold; text-align:right">485,680</td>)
(8697, <td style="font-weight: bold; text-align:right"><a href="/world-population/anguilla-population/">15,084</a> </td>)
(8698, <td data-continent="North America" style="display:none">North America</td>)
(8699, <td>887</td>)
(8700, <td></td>)
(8701, <td>2</td>)
(8702, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">214</td>)
(8703, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/solomon-islands/">Solomon Islands</a></td>)
(8704, <td style="font-weight: bold; text-align:right">17</td>)
(8705, <td style="font-weight: bold; text-align:right;"></td>)
(8706, <td style="font-weight: bold; text-align:right;"> </td>)
(8707, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(8708, <td style="font-weight: bold; text-align:right">10</td>)
(8709, <td style="font-weight: bold; text-align:right;"></td>)
(8710, <td style="text-align:right;font-weight:bold;">7</td>)
(8711, <td style="font-weight: bold; text-align:right"></td>)
(8712, <td style="font-weight: bold; text-align:right">24</td>)
(8713, <td style="font-weight: bold; text-align:right"></td>)
(8714, <td style="font-weight: bold; text-align:right">4,500</td>)
(8715, <td style="font-weight: bold; text-align:right">6,456</td>)
(8716, <td style="font-weight: bold; text-align:right"><a href="/world-population/solomon-islands-population/">697,010</a> </td>)
(8717, <td data-continent="Australia/Oceania" style="display:none">Australia/Oceania</td>)
(8718, <td>41,001</td>)
(8719, <td></td>)
(8720, <td>155</td>)
(8721, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">215</td>)
(8722, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/western-sahara/">Western Sahara</a></td>)
(8723, <td style="font-weight: bold; text-align:right">10</td>)
(8724, <td style="font-weight: bold; text-align:right;"></td>)
(8725, <td style="font-weight: bold; text-align:right;">1 </td>)
(8726, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(8727, <td style="font-weight: bold; text-align:right">8</td>)
(8728, <td style="font-weight: bold; text-align:right;"></td>)
(8729, <td style="text-align:right;font-weight:bold;">1</td>)
(8730, <td style="font-weight: bold; text-align:right"></td>)
(8731, <td style="font-weight: bold; text-align:right">16</td>)
(8732, <td style="font-weight: bold; text-align:right">2</td>)
(8733, <td style="font-weight: bold; text-align:right"></td>)
(8734, <td style="font-weight: bold; text-align:right"></td>)
(8735, <td style="font-weight: bold; text-align:right"><a href="/world-population/western-sahara-population/">606,168</a> </td>)
(8736, <td data-continent="Africa" style="display:none">Africa</td>)
(8737, <td>60,617</td>)
(8738, <td>606,168</td>)
(8739, <td></td>)
(8740, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">216</td>)
(8741, <td style="font-weight: bold; font-size:15px; text-align:left;"><span style="color:#00B5F0; font-style:italic; ">MS Zaandam</span></td>)
(8742, <td style="font-weight: bold; text-align:right">9</td>)
(8743, <td style="font-weight: bold; text-align:right;"></td>)
(8744, <td style="font-weight: bold; text-align:right;">2 </td>)
(8745, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(8746, <td style="font-weight: bold; text-align:right">7</td>)
(8747, <td style="font-weight: bold; text-align:right;"></td>)
(8748, <td style="text-align:right;font-weight:bold;">0</td>)
(8749, <td style="font-weight: bold; text-align:right"></td>)
(8750, <td style="font-weight: bold; text-align:right"></td>)
(8751, <td style="font-weight: bold; text-align:right"></td>)
(8752, <td style="font-weight: bold; text-align:right"></td>)
(8753, <td style="font-weight: bold; text-align:right"></td>)
(8754, <td style="font-weight: bold; text-align:right"> </td>)
(8755, <td data-continent="" style="display:none"></td>)
(8756, <td></td>)
(8757, <td></td>)
(8758, <td></td>)
(8759, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">217</td>)
(8760, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/wallis-and-futuna-islands/">Wallis and Futuna</a></td>)
(8761, <td style="font-weight: bold; text-align:right">9</td>)
(8762, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+4</td>)
(8763, <td style="font-weight: bold; text-align:right;"> </td>)
(8764, <td style="font-weight: bold;

(9802, <td>904</td>)
(9803, <td>2</td>)
(9804, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">35</td>)
(9805, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/morocco/">Morocco</a></td>)
(9806, <td style="font-weight: bold; text-align:right">475,355</td>)
(9807, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+389</td>)
(9808, <td style="font-weight: bold; text-align:right;">8,394 </td>)
(9809, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+13</td>)
(9810, <td style="font-weight: bold; text-align:right">454,504</td>)
(9811, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+583</td>)
(9812, <td style="text-align:right;font-weight:bold;">12,457</td>)
(9813, <td style="font-weight: bold; text-align:right">345</td>)
(9814, <td style="font-weight: bold; text-align:right">12,787</td>)
(9815, <td style="font-weight: bold; text-align:right">226</td>)
(9816, <td style="font-weight: bold; text-align:right">5,455,529</td>)
(9817, <td style="font-weight: bold; text-align:right">146,750</td>)
(9818, <td style="font-weight: bold; text-align:right"><a href="/world-population/morocco-population/">37,175,631</a> </td>)
(9819, <td data-continent="Africa" style="display:none">Africa</td>)
(9820, <td>78</td>)
(9821, <td>4,429</td>)
(9822, <td>7</td>)
(9823, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">36</td>)
(9824, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/austria/">Austria</a></td>)
(9825, <td style="font-weight: bold; text-align:right">423,839</td>)
(9826, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+1,317</td>)
(9827, <td style="font-weight: bold; text-align:right;">8,012 </td>)
(9828, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+18</td>)
(9829, <td style="font-weight: bold; text-align:right">402,053</td>)
(9830, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+1,202</td>)
(9831, <td style="text-align:right;font-weight:bold;">13,774</td>)
(9832, <td style="font-weight: bold; text-align:right">290</td>)
(9833, <td style="font-weight: bold; text-align:right">46,897</td>)
(9834, <td style="font-weight: bold; text-align:right">887</td>)
(9835, <td style="font-weight: bold; text-align:right">4,588,704</td>)
(9836, <td style="font-weight: bold; text-align:right">507,732</td>)
(9837, <td style="font-weight: bold; text-align:right"><a href="/world-population/austria-population/">9,037,643</a> </td>)
(9838, <td data-continent="Europe" style="display:none">Europe</td>)
(9839, <td>21</td>)
(9840, <td>1,128</td>)
(9841, <td>2</td>)
(9842, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">37</td>)
(9843, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/serbia/">Serbia</a></td>)
(9844, <td style="font-weight: bold; text-align:right">407,881</td>)
(9845, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+1,529</td>)
(9846, <td style="font-weight: bold; text-align:right;">4,126 </td>)
(9847, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+14</td>)
(9848, <td style="font-weight: bold; text-align:right">31,536</td>)
(9849, <td style="font-weight: bold; text-align:right;"></td>)
(9850, <td style="text-align:right;font-weight:bold;">372,219</td>)
(9851, <td style="font-weight: bold; text-align:right">135</td>)
(9852, <td style="font-weight: bold; text-align:right">46,798</td>)
(9853, <td style="font-weight: bold; text-align:right">473</td>)
(9854, <td style="font-weight: bold; text-align:right">2,693,265</td>)
(9855, <td style="font-weight: bold; text-align:right">309,007</td>)
(9856, <td style="font-weight: bold; text-align:right"><a href="/world-population/serbia-population/">8,715,863</a> </td>)
(9857, <td data-continent="Europe" style="display:none">Europe</td>)
(9858, <td>21</td>)
(9859, <td>2,112</td>)
(9860, <td>3</td>)
(9861, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">38</td>)
(9862, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/japan/">Japan</a></td>)
(9863, <td style="font-weight: bold; text-align:right">403,435</td>)
(9864, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+2,080</td>)
(9865, <td style="font-weight: bold; text-align:right;">6,338 </td>)
(9866, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+95</td>)
(9867, <td style="font-weight: bold; text-align:right">362,231</td>)
(9868, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+3,359</td>)
(9869, <td style="text-align:right;font-weight:bold;">34,866</td>)
(9870, <td style="font-weight: bold; text-align:right">795</td>)
(9871, <td style="font-weight: bold; text-align:right">3,196</td>)
(9872, <td style="font-weight: bold; text-align:right">50</td>)
(9873, <td style="font-weight: bold; text-align:right">7,221,664</td>)
(9874, <td style="font-weight: bold; text-align:right">57,206</td>)
(9875, <td style="font-weight: bold; text-align:right"><a href="/world-population/japan-population/">126,239,963</a> </td>)
(9876, <td data-continent="Asia" style="display:none">Asia</td>)
(9877, <td>313</td>)
(9878, <td>19,918</td>)
(9879, <td>17</td>)
(9880, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">39</td>)
(9881, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/hungary/">Hungary</a></td>)
(9882, <td style="font-weight: bold; text-align:right">376,495</td>)
(9883, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+1,370</td>)
(9884, <td style="font-weight: bold; text-align:right;">13,090 </td>)
(9885, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+64</td>)
(9886, <td style="font-weight: bold; text-align:right">279,763</td>)
(9887, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+1,814</td>)
(9888, <td style="text-align:right;font-weight:bold;">83,642</td>)
(9889, <td style="font-weight: bold; text-align:right">291</td>)
(9890, <td style="font-weight: bold; text-align:right">39,034</td>)
(9891, <td style="font-weight: bold; text-align:right">1,357</td>)
(9892, <td style="font-weight: bold; text-align:right">3,265,862</td>)
(9893, <td style="font-weight: bold; text-align:right">338,594</td>)
(9894, <td style="font-weight: bold; text-align:right"><a href="/world-population/hungary-population/">9,645,372</a> </td>)
(9895, <td data-continent="Europe" style="display:none">Europe</td>)
(9896, <td>26</td>)
(9897, <td>737</td>)
(9898, <td>3</td>)
(9899, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">40</td>)
(9900, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/saudi-arabia/">Saudi Arabia</a></td>)
(9901, <td style="font-weight: bold; text-align:right">370,278</td>)
(9902, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+317</td>)
(9903, <td style="font-weight: bold; text-align:right;">6,402 </td>)
(9904, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+5</td>)
(9905, <td style="font-weight: bold; text-align:right">361,515</td>)
(9906, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+278</td>)
(9907, <td style="text-align:right;font-weight:bold;">2,361</td>)
(9908, <td style="font-weight: bold; text-align:right">408</td>)
(9909, <td style="font-weight: bold; text-align:right">10,537</td>)
(9910, <td style="font-weight: bold; text-align:right">182</td>)
(9911, <td style="font-weight: bold; text-align:right">12,644,903</td>)
(9912, <td style="font-weight: bold; text-align:right">359,827</td>)
(9913, <td style="font-weight: bold; text-align:right"><a href="/world-population/saudi-arabia-population/">35,141,637</a> </td>)
(9914, <td data-continent="Asia" style="display:none">Asia</td>)
(9915, <td>95</td>)
(9916, <td>5,489</td>)
(9917, <td>3</td>)
(9918, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">41</td>)
(9919, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/jordan/">Jordan</a></td>)
(9920, <td style="font-weight: bold; text-align:right">335,154</td>)
(9921, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+1,299</td>)
(9922, <td style="font-weight: bold; text-align:right;">4,379 </td>)
(9923, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+10</td>)
(9924, <td style="font-weight: bold; text-align:right">320,335</td>)
(9925, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+845</td>)
(9926, <td style="text-align:right;font-weight:bold;">10,440</td>)
(9927, <td style="font-weight: bold; text-align:right">124</td>)
(9928, <td style="font-weight: bold; text-align:right">32,652</td>)
(9929, <td style="font-weight: bold; text-align:right">427</td>)
(9930, <td style="font-weight: bold; text-align:right">4,026,071</td>)
(9931, <td style="font-weight: bold; text-align:right">392,230</td>)
(9932, <td style="font-weight: bold; text-align:right"><a href="/world-population/jordan-population/">10,264,573</a> </td>)
(9933, <td data-continent="Asia" style="display:none">Asia</td>)
(9934, <td>31</td>)
(9935, <td>2,344</td>)
(9936, <td>3</td>)
(9937, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">42</td>)
(9938, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/panama/">Panama</a></td>)
(9939, <td style="font-weight: bold; text-align:right">327,091</td>)
(9940, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+627</td>)
(9941, <td style="font-weight: bold; text-align:right;">5,480 </td>)
(9942, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+25</td>)
(9943, <td style="font-weight: bold; text-align:right">292,302</td>)
(9944, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+2,178</td>)
(9945, <td style="text-align:right;font-weight:bold;">29,309</td>)
(9946, <td style="font-weight: bold; text-align:right">242</td>)
(9947, <td style="font-weight: bold; text-align:right">75,093</td>)
(9948, <td style="font-weight: bold; text-align:right">1,258</td>)
(9949, <td style="font-weight: bold; text-align:right">1,739,966</td>)
(9950, <td style="font-weight: bold; text-align:right">399,457</td>)
(9951, <td style="font-weight: bold; text-align:right"><a href="/world-population/panama-population/">4,355,825</a> </td>)
(9952, <td data-continent="North America" style="display:none">North America</td>)
(9953, <td>13</td>)
(9954, <td>795</td>)
(9955, <td>3</td>)
(9956, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">43</td>)
(9957, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/united-arab-emirates/">UAE</a></td>)
(9958, <td style="font-weight: bold; text-align:right">326,495</td>)
(9959, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+3,093</td>)
(9960, <td style="font-weight: bold; text-align:right;">921 </td>)
(9961, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+7</td>)
(9962, <td style="font-weight: bold; text-align:right">305,759</td>)
(9963, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+4,678</td>)
(9964, <td style="text-align:right;font-weight:bold;">19,815</td>)
(9965, <td style="font-weight: bold; text-align:right"></td>)
(9966, <td style="font-weight: bold; text-align:right">32,771</td>)
(9967, <td style="font-weight: bold; text-align:right">92</td>)
(9968, <td style="font-weight: bold; text-align:right">26,895,872</td>)
(9969, <td style="font-weight: bold; text-align:right">2,699,631</td>)
(9970, <td style="font-weight: bold; text-align:right"><a href="/world-population/united-arab-emirates-population/">9,962,794</a> </td>)
(9971, <td data-continent="Asia" style="display:none">Asia</td>)
(9972, <td>31</td>)
(9973, <td>10,817</td>)
(9974, <td>0</td>)
(9975, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">44</td>)
(9976, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/lebanon/">Lebanon</a></td>)
(9977, <td style="font-weight: bold; text-align:right">319,917</td>)
(9978, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+2,081</td>)
(9979, <td style="font-weight: bold; text-align:right;">3,616 </td>)
(9980, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+54</td>)
(9981, <td style="font-weight: bold; text-align:right">206,523</td>)
(9982, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+5,386</td>)
(9983, <td style="text-align:right;font-weight:bold;">109,778</td>)
(9984, <td style="font-weight: bold; text-align:right">902</td>)
(9985, <td style="font-weight: bold; text-align:right">47,000</td>)
(9986, <td style="font-weight: bold; text-align:right">531</td>)
(9987, <td style="font-weight: bold; text-align:right">2,695,481</td>)
(9988, <td style="font-weight: bold; text-align:right">396,000</td>)
(9989, <td style="font-weight: bold; text-align:right"><a href="/world-population/lebanon-population/">6,806,762</a> </td>)
(9990, <td data-continent="Asia" style="display:none">Asia</td>)
(9991, <td>21</td>)
(9992, <td>1,882</td>)
(9993, <td>3</td>)
(9994, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">45</td>)
(9995, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/nepal/">Nepal</a></td>)
(9996, <td style="font-weight: bold; text-align:right">271,925</td>)
(9997, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+119</td>)
(9998, <td style="font-weight: bold; text-align:right;">2,038 </td>)
(9999, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+3</td>)
(10000, <td style="font-weight: bold; text-align:right">268,072</td>)
(10001, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+260</td>)
(10002, <td style="text-align:right;font-weight:bold;">1,815</td>)
(10003, <td style="font-weight: bold; text-align:right"></td>)
(10004, <td style="font-weight: bold; text-align:right">9,232</td>)
(10005, <td style="font-weight: bold; text-align:right">69</td>)
(10006, <td style="font-weight: bold; text-align:right">2,093,417</td>)
(10007, <td style="font-weight: bold; text-align:right">71,076</td>)
(10008, <td style="font-weight: bold; text-align:right"><a href="/world-population/nepal-population/">29,453,152</a> </td>)
(10009, <td data-continent="Asia" style="display:none">Asia</td>)
(10010, <td>108</td>)
(10011, <td>14,452</td>)
(10012, <td>14</td>)
(10013, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">46</td>)
(10014, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/slovakia/">Slovakia</a></td>)
(10015, <td style="font-weight: bold; text-align:right">263,326</td>)
(10016, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+1,552</td>)
(10017, <td style="font-weight: bold; text-align:right;">5,199 </td>)
(10018, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+64</td>)
(10019, <td style="font-weight: bold; text-align:right">241,686</td>)
(10020, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+3,465</td>)
(10021, <td style="text-align:right;font-weight:bold;">16,441</td>)
(10022, <td style="font-weight: bold; text-align:right">567</td>)
(10023, <td style="font-weight: bold; text-align:right">48,217</td>)
(10024, <td style="font-weight: bold; text-align:right">952</td>)
(10025, <td style="font-weight: bold; text-align:right">1,833,024</td>)
(10026, <td style="font-weight: bold; text-align:right">335,642</td>)
(10027, <td style="font-weight: bold; text-align:right"><a href="/world-population/slovakia-population/">5,461,254</a> </td>)
(10028, <td data-continent="Europe" style="display:none">Europe</td>)
(10029, <td>21</td>)
(10030, <td>1,050</td>)
(10031, <td>3</td>)
(10032, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">47</td>)
(10033, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/georgia/">Georgia</a></td>)
(10034, <td style="font-weight: bold; text-align:right">262,024</td>)
(10035, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+404</td>)
(10036, <td style="font-weight: bold; text-align:right;">3,283 </td>)
(10037, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+14</td>)
(10038, <td style="font-weight: bold; text-align:right">253,614</td>)
(10039, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+799</td>)
(10040, <td style="text-align:right;font-weight:bold;">5,127</td>)
(10041, <td style="font-weight: bold; text-align:right"></td>)
(10042, <td style="font-weight: bold; text-align:right">65,761</td>)
(10043, <td style="font-weight: bold; text-align:right">824</td>)
(10044, <td style="font-weight: bold; text-align:right">2,317,577</td>)
(10045, <td style="font-weight: bold; text-align:right">581,649</td>)
(10046, <td style="font-weight: bold; text-align:right"><a href="/world-population/georgia-population/">3,984,492</a> </td>)
(10047, <td data-continent="Asia" style="display:none">Asia</td>)
(10048, <td>15</td>)
(10049, <td>1,214</td>)
(10050, <td>2</td>)
(10051, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">48</td>)
(10052, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/belarus/">Belarus</a></td>)
(10053, <td style="font-weight: bold; text-align:right">258,691</td>)
(10054, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+1,732</td>)
(10055, <td style="font-weight: bold; text-align:right;">1,783 </td>)
(10056, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+10</td>)
(10057, <td style="font-weight: bold; text-align:right">247,177</td>)
(10058, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+2,236</td>)
(10059, <td style="text-align:right;font-weight:bold;">9,731</td>)
(10060, <td style="font-weight: bold; text-align:right"></td>)
(10061, <td style="font-weight: bold; text-align:right">27,382</td>)
(10062, <td style="font-weight: bold; text-align:right">189</td>)
(10063, <td style="font-weight: bold; text-align:right">4,577,305</td>)
(10064, <td style="font-weight: bold; text-align:right">484,503</td>)
(10065, <td style="font-weight: bold; text-align:right"><a href="/world-population/belarus-population/">9,447,427</a> </td>)
(10066, <td data-continent="Europe" style="display:none">Europe</td>)
(10067, <td>37</td>)
(10068, <td>5,299</td>)

                                    text-align:right;"></td>)
(11900, <td style="font-weight: bold; text-align:right">7,266</td>)
(11901, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+11</td>)
(11902, <td style="text-align:right;font-weight:bold;">215</td>)
(11903, <td style="font-weight: bold; text-align:right">2</td>)
(11904, <td style="font-weight: bold; text-align:right">5,431</td>)
(11905, <td style="font-weight: bold; text-align:right">96</td>)
(11906, <td style="font-weight: bold; text-align:right">86,726</td>)
(11907, <td style="font-weight: bold; text-align:right">61,848</td>)
(11908, <td style="font-weight: bold; text-align:right"><a href="/world-population/trinidad-and-tobago-population/">1,402,247</a> </td>)
(11909, <td data-continent="North America" style="display:none">North America</td>)
(11910, <td>184</td>)
(11911, <td>10,387</td>)
(11912, <td>16</td>)
(11913, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">146</td>)
(11914, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/aruba/">Aruba</a></td>)
(11915, <td style="font-weight: bold; text-align:right">7,223</td>)
(11916, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+21</td>)
(11917, <td style="font-weight: bold; text-align:right;">62 </td>)
(11918, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(11919, <td style="font-weight: bold; text-align:right">6,834</td>)
(11920, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+38</td>)
(11921, <td style="text-align:right;font-weight:bold;">327</td>)
(11922, <td style="font-weight: bold; text-align:right">11</td>)
(11923, <td style="font-weight: bold; text-align:right">67,478</td>)
(11924, <td style="font-weight: bold; text-align:right">579</td>)
(11925, <td style="font-weight: bold; text-align:right">90,512</td>)
(11926, <td style="font-weight: bold; text-align:right">845,575</td>)
(11927, <td style="font-weight: bold; text-align:right"><a href="/world-population/aruba-population/">107,042</a> </td>)
(11928, <td data-continent="North America" style="display:none">North America</td>)
(11929, <td>15</td>)
(11930, <td>1,726</td>)
(11931, <td>1</td>)
(11932, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">147</td>)
(11933, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/martinique/">Martinique</a></td>)
(11934, <td style="font-weight: bold; text-align:right">6,484</td>)
(11935, <td style="font-weight: bold; text-align:right;"></td>)
(11936, <td style="font-weight: bold; text-align:right;">45 </td>)
(11937, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(11938, <td style="font-weight: bold; text-align:right">98</td>)
(11939, <td style="font-weight: bold; text-align:right;"></td>)
(11940, <td style="text-align:right;font-weight:bold;">6,341</td>)
(11941, <td style="font-weight: bold; text-align:right">3</td>)
(11942, <td style="font-weight: bold; text-align:right">17,287</td>)
(11943, <td style="font-weight: bold; text-align:right">120</td>)
(11944, <td style="font-weight: bold; text-align:right">90,204</td>)
(11945, <td style="font-weight: bold; text-align:right">240,488</td>)
(11946, <td style="font-weight: bold; text-align:right"><a href="/world-population/martinique-population/">375,087</a> </td>)
(11947, <td data-continent="North America" style="display:none">North America</td>)
(11948, <td>58</td>)
(11949, <td>8,335</td>)
(11950, <td>4</td>)
(11951, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">148</td>)
(11952, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/nicaragua/">Nicaragua</a></td>)
(11953, <td style="font-weight: bold; text-align:right">6,299</td>)
(11954, <td style="font-weight: bold; text-align:right;"></td>)
(11955, <td style="font-weight: bold; text-align:right;">170 </td>)
(11956, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(11957, <td style="font-weight: bold; text-align:right">4,225</td>)
(11958, <td style="font-weight: bold; text-align:right;"></td>)
(11959, <td style="text-align:right;font-weight:bold;">1,904</td>)
(11960, <td style="font-weight: bold; text-align:right"></td>)
(11961, <td style="font-weight: bold; text-align:right">944</td>)
(11962, <td style="font-weight: bold; text-align:right">25</td>)
(11963, <td style="font-weight: bold; text-align:right"></td>)
(11964, <td style="font-weight: bold; text-align:right"></td>)
(11965, <td style="font-weight: bold; text-align:right"><a href="/world-population/nicaragua-population/">6,672,306</a> </td>)
(11966, <td data-continent="North America" style="display:none">North America</td>)
(11967, <td>1,059</td>)
(11968, <td>39,249</td>)
(11969, <td></td>)
(11970, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">149</td>)
(11971, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/iceland/">Iceland</a></td>)
(11972, <td style="font-weight: bold; text-align:right">6,020</td>)
(11973, <td style="font-weight: bold; text-align:right;"></td>)
(11974, <td style="font-weight: bold; text-align:right;">29 </td>)
(11975, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(11976, <td style="font-weight: bold; text-align:right">5,959</td>)
(11977, <td style="font-weight: bold; text-align:right;"></td>)
(11978, <td style="text-align:right;font-weight:bold;">32</td>)
(11979, <td style="font-weight: bold; text-align:right"></td>)
(11980, <td style="font-weight: bold; text-align:right">17,572</td>)
(11981, <td style="font-weight: bold; text-align:right">85</td>)
(11982, <td style="font-weight: bold; text-align:right">482,554</td>)
(11983, <td style="font-weight: bold; text-align:right">1,408,551</td>)
(11984, <td style="font-weight: bold; text-align:right"><a href="/world-population/iceland-population/">342,589</a> </td>)
(11985, <td data-continent="Europe" style="display:none">Europe</td>)
(11986, <td>57</td>)
(11987, <td>11,813</td>)
(11988, <td>1</td>)
(11989, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">150</td>)
(11990, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/djibouti/">Djibouti</a></td>)
(11991, <td style="font-weight: bold; text-align:right">5,947</td>)
(11992, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+6</td>)
(11993, <td style="font-weight: bold; text-align:right;">63 </td>)
(11994, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(11995, <td style="font-weight: bold; text-align:right">5,852</td>)
(11996, <td style="font-weight: bold; text-align:right;"></td>)
(11997, <td style="text-align:right;font-weight:bold;">32</td>)
(11998, <td style="font-weight: bold; text-align:right"></td>)
(11999, <td style="font-weight: bold; text-align:right">5,967</td>)
(12000, <td style="font-weight: bold; text-align:right">63</td>)
(12001, <td style="font-weight: bold; text-align:right">110,138</td>)
(12002, <td style="font-weight: bold; text-align:right">110,504</td>)
(12003, <td style="font-weight: bold; text-align:right"><a href="/world-population/djibouti-population/">996,691</a> </td>)
(12004, <td data-continent="Africa" style="display:none">Africa</td>)
(12005, <td>168</td>)
(12006, <td>15,820</td>)
(12007, <td>9</td>)
(12008, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">151</td>)
(12009, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/equatorial-guinea/">Equatorial Guinea</a></td>)
(12010, <td style="font-weight: bold; text-align:right">5,578</td>)
(12011, <td style="font-weight: bold; text-align:right;"></td>)
(12012, <td style="font-weight: bold; text-align:right;">86 </td>)
(12013, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(12014, <td style="font-weight: bold; text-align:right">5,358</td>)
(12015, <td style="font-weight: bold; text-align:right;"></td>)
(12016, <td style="text-align:right;font-weight:bold;">134</td>)
(12017, <td style="font-weight: bold; text-align:right">4</td>)
(12018, <td style="font-weight: bold; text-align:right">3,899</td>)
(12019, <td style="font-weight: bold; text-align:right">60</td>)
(12020, <td style="font-weight: bold; text-align:right">90,460</td>)
(12021, <td style="font-weight: bold; text-align:right">63,235</td>)
(12022, <td style="font-weight: bold; text-align:right"><a href="/world-population/equatorial-guinea-population/">1,430,547</a> </td>)
(12023, <td data-continent="Africa" style="display:none">Africa</td>)
(12024, <td>256</td>)
(12025, <td>16,634</td>)
(12026, <td>16</td>)
(12027, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">152</td>)
(12028, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/togo/">Togo</a></td>)
(12029, <td style="font-weight: bold; text-align:right">5,483</td>)
(12030, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+47</td>)
(12031, <td style="font-weight: bold; text-align:right;">80 </td>)
(12032, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+1</td>)
(12033, <td style="font-weight: bold; text-align:right">4,550</td>)
(12034, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+15</td>)
(12035, <td style="text-align:right;font-weight:bold;">853</td>)
(12036, <td style="font-weight: bold; text-align:right"></td>)
(12037, <td style="font-weight: bold; text-align:right">653</td>)
(12038, <td style="font-weight: bold; text-align:right">10</td>)
(12039, <td style="font-weight: bold; text-align:right">213,812</td>)
(12040, <td style="font-weight: bold; text-align:right">25,468</td>)
(12041, <td style="font-weight: bold; text-align:right"><a href="/world-population/togo-population/">8,395,451</a> </td>)
(12042, <td data-continent="Africa" style="display:none">Africa</td>)
(12043, <td>1,531</td>)
(12044, <td>104,943</td>)
(12045, <td>39</td>)
(12046, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">153</td>)
(12047, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/central-african-republic/">CAR</a></td>)
(12048, <td style="font-weight: bold; text-align:right">4,989</td>)
(12049, <td style="font-weight: bold; text-align:right;"></td>)
(12050, <td style="font-weight: bold; text-align:right;">63 </td>)
(12051, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(12052, <td style="font-weight: bold; text-align:right">4,885</td>)
(12053, <td style="font-weight: bold; text-align:right;"></td>)
(12054, <td style="text-align:right;font-weight:bold;">41</td>)
(12055, <td style="font-weight: bold; text-align:right">2</td>)
(12056, <td style="font-weight: bold; text-align:right">1,022</td>)
(12057, <td style="font-weight: bold; text-align:right">13</td>)
(12058, <td style="font-weight: bold; text-align:right">35,523</td>)
(12059, <td style="font-weight: bold; text-align:right">7,279</td>)
(12060, <td style="font-weight: bold; text-align:right"><a href="/world-population/central-african-republic-population/">4,880,476</a> </td>)
(12061, <td data-continent="Africa" style="display:none">Africa</td>)
(12062, <td>978</td>)
(12063, <td>77,468</td>)
(12064, <td>137</td>)
(12065, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">154</td>)
(12066, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/somalia/">Somalia</a></td>)
(12067, <td style="font-weight: bold; text-align:right">4,862</td>)
(12068, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+8</td>)
(12069, <td style="font-weight: bold; text-align:right;">134 </td>)
(12070, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(12071, <td style="font-weight: bold; text-align:right">3,720</td>)
(12072, <td style="font-weight: bold; text-align:right;"></td>)
(12073, <td style="text-align:right;font-weight:bold;">1,008</td>)
(12074, <td style="font-weight: bold; text-align:right"></td>)
(12075, <td style="font-weight: bold; text-align:right">301</td>)
(12076, <td style="font-weight: bold; text-align:right">8</td>)
(12077, <td style="font-weight: bold; text-align:right"></td>)
(12078, <td style="font-weight: bold; text-align:right"></td>)
(12079, <td style="font-weight: bold; text-align:right"><a href="/world-population/somalia-population/">16,159,216</a> </td>)
(12080, <td data-continent="Africa" style="display:none">Africa</td>)
(12081, <td>3,324</td>)
(12082, <td>120,591</td>)
(12083, <td></td>)
(12084, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">155</td>)
(12085, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/curacao/">Curaçao</a></td>)
(12086, <td style="font-weight: bold; text-align:right">4,613</td>)
(12087, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+8</td>)
(12088, <td style="font-weight: bold; text-align:right;">21 </td>)
(12089, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(12090, <td style="font-weight: bold; text-align:right">4,535</td>)
(12091, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+5</td>)
(12092, <td style="text-align:right;font-weight:bold;">57</td>)
(12093, <td style="font-weight: bold; text-align:right">2</td>)
(12094, <td style="font-weight: bold; text-align:right">28,042</td>)
(12095, <td style="font-weight: bold; text-align:right">128</td>)
(12096, <td style="font-weight: bold; text-align:right">45,539</td>)
(12097, <td style="font-weight: bold; text-align:right">276,831</td>)
(12098, <td style="font-weight: bold; text-align:right"><a href="/world-population/curacao-population/">164,501</a> </td>)
(12099, <td data-continent="North America" style="display:none">North America</td>)
(12100, <td>36</td>)
(12101, <td>7,833</td>)
(12102, <td>4</td>)
(12103, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">156</td>)
(12104, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/niger/">Niger</a></td>)
(12105, <td style="font-weight: bold; text-align:right">4,612</td>)
(12106, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+14</td>)
(12107, <td style="font-weight: bold; text-align:right;">165 </td>)
(12108, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(12109, <td style="font-weight: bold; text-align:right">3,970</td>)
(12110, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+20</td>)
(12111, <td style="text-align:right;font-weight:bold;">477</td>)
(12112, <td style="font-weight: bold; text-align:right">3</td>)
(12113, <td style="font-weight: bold; text-align:right">186</td>)
(12114, <td style="font-weight: bold; text-align:right">7</td>)
(12115, <td style="font-weight: bold; text-align:right">75,832</td>)
(12116, <td style="font-weight: bold; text-align:right">3,066</td>)
(12117, <td style="font-weight: bold; text-align:right"><a href="/world-population/niger-population/">24,729,456</a> </td>)
(12118, <td data-continent="Africa" style="display:none">Africa</td>)
(12119, <td>5,362</td>)
(12120, <td>149,875</td>)
(12121, <td>326</td>)
(12122, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">157</td>)
(12123, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/south-sudan/">South Sudan</a></td>)
(12124, <td style="font-weight: bold; text-align:right">4,355</td>)
(12125, <td style="font-weight: bold; text-align:right;"></td>)
(12126, <td style="font-weight: bold; text-align:right;">66 </td>)
(12127, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(12128, <td style="font-weight: bold; text-align:right">3,663</td>)
(12129, <td style="font-weight: bold; text-align:right;"></td>)
(12130, <td style="text-align:right;font-weight:bold;">626</td>)
(12131, <td style="font-weight: bold; text-align:right">2</td>)
(12132, <td style="font-weight: bold; text-align:right">386</td>)
(12133, <td style="font-weight: bold; text-align:right">6</td>)
(12134, <td style="font-weight: bold; text-align:right">91,551</td>)
(12135, <td style="font-weight: bold; text-align:right">8,121</td>)
(12136, <td style="font-weight: bold; text-align:right"><a href="/world-population/south-sudan-population/">11,273,245</a> </td>)
(12137, <td data-continent="Africa" style="display:none">Africa</td>)
(12138, <td>2,589</td>)
(12139, <td>170,807</td>)
(12140, <td>123</td>)
(12141, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">158</td>)
(12142, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/gambia/">Gambia</a></td>)
(12143, <td style="font-weight: bold; text-align:right">4,237</td>)
(12144, <td style="font-weight: bold; text-align:right;"></td>)
(12145, <td style="font-weight: bold; text-align:right;">134 </td>)
(12146, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(12147, <td style="font-weight: bold; text-align:right">3,886</td>)
(12148, <td style="font-weight: bold; text-align:right;"></td>)
(12149, <td style="text-align:right;font-weight:bold;">217</td>)
(12150, <td style="font-weight: bold; text-align:right">1</td>)
(12151, <td style="font-weight: bold; text-align:right">1,724</td>)
(12152, <td style="font-weight: bold; text-align:right">55</td>)
(12153, <td style="font-weight: bold; text-align:right">37,251</td>)
(12154, <td style="font-weight: bold; text-align:right">15,159</td>)
(12155, <td style="font-weight: bold; text-align:right"><a href="/world-population/gambia-population/">2,457,391</a> </td>)
(12156, <td data-continent="Africa" style="display:none">Africa</td>)
(12157, <td>580</td>)
(12158, <td>18,339</td>)
(12159, <td>66</td>)
(12160, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">159</td>)
(12161, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/benin/">Benin</a></td>)
(12162, <td style="font-weight: bold; text-align:right">4,193</td>)
(12163, <td style="font-weight: bold; text-align:right;"></td>)
(12164, <td style="font-weight: bold; text-align:right;">55 </td>)
(12165, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(12166, <td style="font-weight: bold; text-align:right">3,563</td>)
(12167, <td style="font-weight: bold; text-align:right;"></td>)
(12168, <td style="text-align:right;font-weight:bold;">575</td>)
(12169, <td style="font-weight: bold; text-align:right"></td>)
(12170, <td style="font-weight: bold; text-align:right">341</td>)
(12171, <td style="font-weight: bold; text-align:right">4</td>)
(12172, <td style="font-weight: bold; text-align:right">434,422</td>)
(12173, <td style="font-weight: bold; text-align:right">35,279</td>)
(12174, <td style="font-weight: bold; text-align:right"><a href="/world-population/benin-population/">12,313,895</a> </td>)
(12175, <td data-continent="Africa" style="display:none">Africa</td>)
(12176, <td>2,937</td>)
(12177, <td>223,889</td>)
(12178, <td>28</td>)
(12179, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">160</td>)

(13243, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">216</td>)
(13244, <td style="font-weight: bold; font-size:15px; text-align:left;"><span style="color:#00B5F0; font-style:italic; ">MS Zaandam</span></td>)
(13245, <td style="font-weight: bold; text-align:right">9</td>)
(13246, <td style="font-weight: bold; text-align:right;"></td>)
(13247, <td style="font-weight: bold; text-align:right;">2 </td>)
(13248, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(13249, <td style="font-weight: bold; text-align:right">7</td>)
(13250, <td style="font-weight: bold; text-align:right;"></td>)
(13251, <td style="text-align:right;font-weight:bold;">0</td>)
(13252, <td style="font-weight: bold; text-align:right"></td>)
(13253, <td style="font-weight: bold; text-align:right"></td>)
(13254, <td style="font-weight: bold; text-align:right"></td>)
(13255, <td style="font-weight: bold; text-align:right"></td>)
(13256, <td style="font-weight: bold; text-align:right"></td>)
(13257, <td style="font-weight: bold; text-align:right"> </td>)
(13258, <td data-continent="" style="display:none"></td>)
(13259, <td></td>)
(13260, <td></td>)
(13261, <td></td>)
(13262, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">217</td>)
(13263, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/wallis-and-futuna-islands/">Wallis and Futuna</a></td>)
(13264, <td style="font-weight: bold; text-align:right">5</td>)
(13265, <td style="font-weight: bold; text-align:right;"></td>)
(13266, <td style="font-weight: bold; text-align:right;"> </td>)
(13267, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(13268, <td style="font-weight: bold; text-align:right">4</td>)
(13269, <td style="font-weight: bold; text-align:right;"></td>)
(13270, <td style="text-align:right;font-weight:bold;">1</td>)
(13271, <td style="font-weight: bold; text-align:right"></td>)
(13272, <td style="font-weight: bold; text-align:right">450</td>)
(13273, <td style="font-weight: bold; text-align:right"></td>)
(13274, <td style="font-weight: bold; text-align:right">1,202</td>)
(13275, <td style="font-weight: bold; text-align:right">108,113</td>)
(13276, <td style="font-weight: bold; text-align:right"><a href="/world-population/wallis-and-futuna-islands-population/">11,118</a> </td>)
(13277, <td data-continent="Australia/Oceania" style="display:none">Australia/Oceania</td>)
(13278, <td>2,224</td>)
(13279, <td></td>)
(13280, <td>9</td>)
(13281, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">218</td>)
(13282, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/marshall-islands/">Marshall Islands</a></td>)
(13283, <td style="font-weight: bold; text-align:right">4</td>)
(13284, <td style="font-weight: bold; text-align:right;"></td>)
(13285, <td style="font-weight: bold; text-align:right;"> </td>)
(13286, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(13287, <td style="font-weight: bold; text-align:right">4</td>)
(13288, <td style="font-weight: bold; text-align:right;"></td>)
(13289, <td style="text-align:right;font-weight:bold;">0</td>)
(13290, <td style="font-weight: bold; text-align:right"></td>)
(13291, <td style="font-weight: bold; text-align:right">67</td>)
(13292, <td style="font-weight: bold; text-align:right"></td>)
(13293, <td style="font-weight: bold; text-align:right"></td>)
(13294, <td style="font-weight: bold; text-align:right"></td>)
(13295, <td style="font-weight: bold; text-align:right"><a href="/world-population/marshall-islands-population/">59,433</a> </td>)
(13296, <td data-continent="Australia/Oceania" style="display:none">Australia/Oceania</td>)
(13297, <td>14,858</td>)
(13298, <td></td>)
(13299, <td></td>)
(13300, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">219</td>)
(13301, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/samoa/">Samoa</a></td>)
(13302, <td style="font-weight: bold; text-align:right">2</td>)
(13303, <td style="font-weight: bold; text-align:right;"></td>)
(13304, <td style="font-weight: bold; text-align:right;"> </td>)
(13305, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(13306, <td style="font-weight: bold; text-align:right">2</td>)
(13307, <td style="font-weight: bold; text-align:right;"></td>)
(13308, <td style="text-align:right;font-weight:bold;">0</td>)
(13309, <td style="font-weight: bold; text-align:right"></td>)
(13310, <td style="font-weight: bold; text-align:right">10</td>)
(13311, <td style="font-weight: bold; text-align:right"></td>)
(13312, <td style="font-weight: bold; text-align:right"></td>)
(13313, <td style="font-weight: bold; text-align:right"></td>)
(13314, <td style="font-weight: bold; text-align:right"><a href="/world-population/samoa-population/">199,215</a> </td>)
(13315, <td data-continent="Australia/Oceania" style="display:none">Australia/Oceania</td>)
(13316, <td>99,608</td>)
(13317, <td></td>)
(13318, <td></td>)
(13319, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">220</td>)
(13320, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/micronesia/">Micronesia</a></td>)
(13321, <td style="font-weight: bold; text-align:right">1</td>)
(13322, <td style="font-weight: bold; text-align:right;"></td>)
(13323, <td style="font-weight: bold; text-align:right;"> </td>)
(13324, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(13325, <td style="font-weight: bold; text-align:right">1</td>)
(13326, <td style="font-weight: bold; text-align:right;"></td>)
(13327, <td style="text-align:right;font-weight:bold;">0</td>)
(13328, <td style="font-weight: bold; text-align:right"></td>)
(13329, <td style="font-weight: bold; text-align:right">9</td>)
(13330, <td style="font-weight: bold; text-align:right"></td>)
(13331, <td style="font-weight: bold; text-align:right"></td>)
(13332, <td style="font-weight: bold; text-align:right"></td>)
(13333, <td style="font-weight: bold; text-align:right"><a href="/world-population/micronesia-population/">115,754</a> </td>)
(13334, <td data-continent="Australia/Oceania" style="display:none">Australia/Oceania</td>)
(13335, <td>115,754</td>)
(13336, <td></td>)
(13337, <td></td>)
(13338, <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">221</td>)
(13339, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/vanuatu/">Vanuatu</a></td>)
(13340, <td style="font-weight: bold; text-align:right">1</td>)
(13341, <td style="font-weight: bold; text-align:right;"></td>)
(13342, <td style="font-weight: bold; text-align:right;"> </td>)
(13343, <td style="font-weight: bold;
                                    text-align:right;"></td>)
(13344, <td style="font-weight: bold; text-align:right">1</td>)
(13345, <td style="font-weight: bold; text-align:right;"></td>)
(13346, <td style="text-align:right;font-weight:bold;">0</td>)
(13347, <td style="font-weight: bold; text-align:right"></td>)
(13348, <td style="font-weight: bold; text-align:right">3</td>)
(13349, <td style="font-weight: bold; text-align:right"></td>)
(13350, <td style="font-weight: bold; text-align:right">470</td>)
(13351, <td style="font-weight: bold; text-align:right">1,509</td>)
(13352, <td style="font-weight: bold; text-align:right"><a href="/world-population/vanuatu-population/">311,463</a> </td>)
(13353, <td data-continent="Australia/Oceania" style="display:none">Australia/Oceania</td>)
(13354, <td>311,463</td>)
(13355, <td></td>)
(13356, <td>663</td>)
(13357, <td></td>)
(13358, <td><strong>Total:</strong></td>)
(13359, <td>23,578,719</td>)
(13360, <td style="background-color:#FFEEAA; color:#000;">+64,377</td>)
(13361, <td>379,561</td>)
(13362, <td style="background-color:red; color:#fff">+863</td>)
(13363, <td>22,072,443</td>)
(13364, <td style="background-color:#c8e6c9; color:#000">+85,234</td>)
(13365, <td>1,126,715</td>)
(13366, <td>22,693</td>)
(13367, <td></td>)
(13368, <td></td>)
(13369, <td></td>)
(13370, <td></td>)
(13371, <td></td>)
(13372, <td data-continent="Asia" style="display:none;">Asia</td>)
(13373, <td> </td>)
(13374, <td></td>)
(13375, <td></td>)
(13376, <td></td>)
(13377, <td><strong>Total:</strong></td>)
(13378, <td>31,600,941</td>)
(13379, <td style="background-color:#FFEEAA; color:#000;">+112,147</td>)
(13380, <td>685,770</td>)
(13381, <td style="background-color:red; color:#fff">+2,999</td>)
(13382, <td>20,556,060</td>)
(13383, <td style="background-color:#c8e6c9; color:#000">+94,088</td>)
(13384, <td>10,359,111</td>)
(13385, <td>29,672</td>)
(13386, <td></td>)
(13387, <td></td>)
(13388, <td></td>)
(13389, <td></td>)
(13390, <td></td>)
(13391, <td data-continent="North America" style="display:none;">North America</td>)
(13392, <td> </td>)
(13393, <td></td>)
(13394, <td></td>)
(13395, <td></td>)
(13396, <td><strong>Total:</strong></td>)
(13397, <td>16,432,736</td>)
(13398, <td style="background-color:#FFEEAA; color:#000;">+50,472</td>)
(13399, <td>428,741</td>)
(13400, <td style="background-color:red; color:#fff">+1,227</td>)
(13401, <td>14,696,171</td>)
(13402, <td style="background-color:#c8e6c9; color:#000">+68,413</td>)
(13403, <td>1,307,824</td>)
(13404, <td>19,860</td>)
(13405, <td></td>)
(13406, <td></td>)
(13407, <td></td>)
(13408, <td></td>)
(13409, <td></td>)
(13410, <td data-continent="South America" style="display:none;">South America</td>)
(13411, <td> </td>)
(13412, <td></td>)
(13413, <td></td>)
(13414, <td></td>)
(13415, <td><strong>Total:</strong></td>)
(13416, <td>31,332,801</td>)
(13417, <td style="background-color:#FFEEAA; color:#000;">+123,432</td>)
(13418, <td>737,288</td>)
(13419, <td style="background-color:red; color:#fff">+2,761</td>)
(13420, <td>17,950,937</td>)
(13421, <td style="background-color:#c8e6c9; color:#000">+96,394</td>)
(13422, <td>12,644,576</td>)
(13423, <td>29,050</td>)
(13424, <td></td>)
(13425, <td></td>)
(13426, <td></td>)
(13427, <td></td>)
(13428, <td></td>)
(13429, <td data-continent="Europe" style="display:none;">Europe</td>)
(13430, <td> </td>)
(13431, <td></td>)
(13432, <td></td>)
(13433, <td></td>)
(13434, <td><strong>Total:</strong></td>)
(13435, <td>3,689,088</td>)
(13436, <td style="background-color:#FFEEAA; color:#000;">+11,572</td>)
(13437, <td>95,214</td>)
(13438, <td style="background-color:red; color:#fff">+355</td>)
(13439, <td>3,206,129</td>)
(13440, <td style="background-color:#c8e6c9; color:#000">+28,714</td>)
(13441, <td>387,745</td>)
(13442, <td>2,491</td>)
(13443, <td></td>)
(13444, <td></td>)
(13445, <td></td>)
(13446, <td></td>)
(13447, <td></td>)
(13448, <td data-continent="Africa" style="display:none;">Africa</td>)
(13449, <td> </td>)
(13450, <td></td>)
(13451, <td></td>)
(13452, <td></td>)
(13453, <td><strong>Total:</strong></td>)
(13454, <td>50,385</td>)
(13455, <td style="background-color:#FFEEAA; color:#000;">+11</td>)
(13456, <td>1,078</td>)
(13457, <td style=""></td>)
(13458, <td>34,125</td>)
(13459, <td style="background-color:#c8e6c9; color:#000"></td>)
(13460, <td>15,182</td>)
(13461, <td>8</td>)
(13462, <td></td>)
(13463, <td></td>)
(13464, <td></td>)
(13465, <td></td>)
(13466, <td></td>)
(13467, <td data-continent="Australia/Oceania" style="display:none;">Australia/Oceania</td>)
(13468, <td> </td>)
(13469, <td></td>)
(13470, <td></td>)
(13471, <td></td>)
(13472, <td><strong>Total:</strong></td>)
(13473, <td>721</td>)
(13474, <td style=""></td>)
(13475, <td>15</td>)
(13476, <td style=""></td>)
(13477, <td>706</td>)
(13478, <td style=""></td>)
(13479, <td>0</td>)
(13480, <td>0</td>)
(13481, <td></td>)
(13482, <td></td>)
(13483, <td></td>)
(13484, <td></td>)
(13485, <td></td>)
(13486, <td data-continent="" style="display:none;"></td>)
(13487, <td> </td>)
(13488, <td></td>)
(13489, <td></td>)
(13490, <td></td>)
(13491, <td><strong>Total:</strong></td>)
(13492, <td>106,685,391</td>)
(13493, <td style="background-color:#FFEEAA; color:#000;">+362,011</td>)
(13494, <td>2,327,667</td>)
(13495, <td style="background-color:red; color:#fff">+8,205</td>)
(13496, <td>78,516,571</td>)
(13497, <td style="background-color:#c8e6c9; color:#000">+372,865</td>)
(13498, <td>25,841,153</td>)
(13499, <td>103,774</td>)
(13500, <td>13,686.7</td>)
(13501, <td>298.6</td>)
(13502, <td></td>)
(13503, <td></td>)
(13504, <td></td>)
(13505, <td data-continent="all" style="display:none">All</td>)
(13506, <td>
</td>)
(13507, <td></td>)
(13508, <td></td>)

In [114]:
#here we find the index!

In [162]:
## %%time

countrylist = countries[0:4]
indexes  = {}
for i in countrylist:
    indexes[i] = 'Notfound'

for i in countrylist:
    j=0
    while indexes[i] != 'NotFound' and j <= len(td):
        if td[j].string == i:
            indexes[i] = j
            break
        else:
            j+=1

In [122]:
indexes

{'USA': 153, 'India': 172, 'Brazil': 191, 'Russia': 210}

## do the same for the world!

In [144]:
%%time
def world_stats(x):
    j=0
    while x[j].string != 'World':
        j+=1
    else:
        return j

world_index = world_stats(td)

Wall time: 0 ns

--------------

## found the indices, now find the list!

In [123]:
India = td[indexes['India'] : indexes['India']+15]

In [219]:
India#automatize this shit

[<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/india/">India</a></td>,
 <td style="font-weight: bold; text-align:right">10,858,300</td>,
 <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+10,510</td>,
 <td style="font-weight: bold; text-align:right;">155,280 </td>,
 <td style="font-weight: bold;
                                     text-align:right;background-color:red; color:white">+85</td>,
 <td style="font-weight: bold; text-align:right">10,559,604</td>,
 <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+12,699</td>,
 <td style="text-align:right;font-weight:bold;">143,416</td>,
 <td style="font-weight: bold; text-align:right">8,944</td>,
 <td style="font-weight: bold; text-align:right">7,822</td>,
 <td style="font-weight: bold; text-align:right">112</td>,
 <td style="font-weight: bold; text-align:right">201,900,614</td>,
 <td style="font-weight: bold; text-align:right">145,437</td>,
 <td style="font-weight: bold; text-align:right"><a href="/world-population/india-population/">1,388,234,493</a> </td>,
 <td data-continent="Asia" style="display:none">Asia</td>]

In [227]:
for i in India:
    print(i)

<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/india/">India</a></td>
<td style="font-weight: bold; text-align:right">10,858,300</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+10,510</td>
<td style="font-weight: bold; text-align:right;">155,280 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+85</td>
<td style="font-weight: bold; text-align:right">10,559,604</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+12,699</td>
<td style="text-align:right;font-weight:bold;">143,416</td>
<td style="font-weight: bold; text-align:right">8,944</td>
<td style="font-weight: bold; text-align:right">7,822</td>
<td style="font-weight: bold; text-align:right">112</td>
<td style="font-weight: bold; text-align:right">201,900,614</td>
<td style="font-weight: bold; text-align:right">145,437</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/india-population/">1,388,234,493</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>

In [301]:
td[world_index: world_index+15]

[<td style="text-align:left;">World</td>,
 <td>107,350,771</td>,
 <td>+341,537</td>,
 <td>2,347,925</td>,
 <td>+11,827</td>,
 <td>79,395,821</td>,
 <td>+424,991</td>,
 <td>25,607,025</td>,
 <td>102,609</td>,
 <td>13,772</td>,
 <td>301.2</td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td data-continent="all" style="display:none">All</td>]

In [302]:
%%time

statspd = pd.DataFrame(td[world_index: world_index+15])
statspd.applymap(lambda x: x.string)
#we will count the total population of the world later

Wall time: 4 ms

              0
0         World
1   107,350,771
2      +341,537
3     2,347,925
4       +11,827
5    79,395,821
6      +424,991
7    25,607,025
8       102,609
9        13,772
10        301.2
11         None
12         None
13         None
14          All

In [303]:
'''HERE WE ANNEX THE OTHER COUNTRIES'''
for i in indexes.keys():
    j = indexes[i]
    statspd[i] =td[j:j +15]

statspd = statspd.applymap(lambda x : x.string)

statspd.columns = statspd.iloc[0,:]

statspd.drop(index = 0, inplace = True)

In [304]:
statspd

0         World            USA        India         Brazil       Russia
1   107,350,771     27,778,684   10,858,300      9,599,565    3,998,216
2      +341,537        +75,057      +10,510        +49,264      +15,019
3     2,347,925       478,967      155,280        233,520       77,598
4       +11,827         +2,459          +85         +1,272         +530
5    79,395,821     17,607,437   10,559,604      8,523,462    3,493,886
6      +424,991        +94,617      +12,699        +75,817      +21,795
7    25,607,025      9,692,280      143,416        842,583      426,732
8       102,609         21,447        8,944          8,318        2,300
9        13,772         83,625        7,822         44,968       27,390
10        301.2          1,442          112          1,094          532
11         None    326,902,996  201,900,614     28,600,000  105,000,000
12         None        984,106      145,437        133,972      719,313
13         None           None         None           None         None
14          All  North America         Asia  South America       Europe

# trial 1

In [287]:
td[]

TypeError: list indices must be integers or slices, not NavigableString

In [286]:
for i in td:
    j = i.find('a')
    if j != None:
        print(j)

KeyError: 'World'

# niw with regex

In [ ]:
x_new= []
for i in x:
    #find = re.findall('>(\-*\+*.*)<', str(i))
    find = re.findall('[\++|0-9,]+',i)

    
    if find != [] and find != None:
        #print(find[-1])
        x_new.append(find[-1]) 
    else:
        x_new.append(i)
x_new

In [ ]:
x_new[0]= 'USA'

x_new[-1] =re.findall('>(.*)<',x[-1])[0]

x_new

# names

#  columns!

In [ ]:
categories