In [1]:
import requests
from bs4 import BeautifulSoup
import timeit
import re
import pandas as pd
import numpy as np

In [2]:
url = 'https://www.worldometers.info/coronavirus/'

In [3]:
%%time
def makesoup(url):
    ''' connect and get the soup from the page'''
    response = requests.get(url)
    soup= BeautifulSoup(response.content, "html.parser")
    return soup#.find_all('td')
soup = makesoup(url)

world_pop = makesoup('https://www.worldometers.info/world-population/#:~:text=7.8%20Billion%20(2021),currently%20living)%20of%20the%20world.')

Wall time: 3.56 s

In [50]:
def get_data(soup):
    return soup.find_all('td')

In [5]:
database = get_data(soup)

In [6]:
database

[<td></td>,
 <td style="text-align:left;">
 <nobr>North America</nobr>
 </td>,
 <td>34,096,943</td>,
 <td>+2,971</td>,
 <td>777,610</td>,
 <td>+266</td>,
 <td>23,984,380</td>,
 <td>+3,780</td>,
 <td>9,334,953</td>,
 <td>19,642</td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td data-continent="North America" style="display:none;">North America</td>,
 <td>
 </td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td style="text-align:left;">
 <nobr>Asia</nobr>
 </td>,
 <td>25,577,023</td>,
 <td>+27,510</td>,
 <td>404,660</td>,
 <td>+478</td>,
 <td>23,993,681</td>,
 <td>+25,620</td>,
 <td>1,178,682</td>,
 <td>22,260</td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td data-continent="Asia" style="display:none;">Asia</td>,
 <td>
 </td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td style="text-align:left;">
 <nobr>South America</nobr>
 </td>,
 <td>18,630,122</td>,
 <td>+323</td>,
 <td>481,492</td>,
 <td>+16</td>,
 <td>16,772,845</td>,
 <td>+809</td>,
 <td>1,375,785</td>,
 <td>18,835</td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td data-continent="South America" style="display:none;">South America</td>,
 <td>
 </td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td style="text-align:left;">
 <nobr>Europe</nobr>
 </td>,
 <td>35,164,007</td>,
 <td>+41,843</td>,
 <td>836,033</td>,
 <td>+958</td>,
 <td>24,689,856</td>,
 <td>+40,373</td>,
 <td>9,638,118</td>,
 <td>26,405</td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td data-continent="Europe" style="display:none;">Europe</td>,
 <td>
 </td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td style="text-align:left;">
 <nobr>Africa</nobr>
 </td>,
 <td>3,994,824</td>,
 <td>+1,162</td>,
 <td>105,927</td>,
 <td>+21</td>,
 <td>3,557,244</td>,
 <td>+1,348</td>,
 <td>331,653</td>,
 <td>2,497</td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td data-continent="Africa" style="display:none;">Africa</td>,
 <td>
 </td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td style="text-align:left;">
 <nobr>Oceania</nobr>
 </td>,
 <td>51,758</td>,
 <td>+113</td>,
 <td>1,093</td>,
 <td></td>,
 <td>34,328</td>,
 <td>+3</td>,
 <td>16,337</td>,
 <td>3</td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td data-continent="Australia/Oceania" style="display:none;">Australia/Oceania</td>,
 <td>
 </td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td style="text-align:left;">
 <nobr></nobr>
 </td>,
 <td>721</td>,
 <td></td>,
 <td>15</td>,
 <td></td>,
 <td>706</td>,
 <td></td>,
 <td>0</td>,
 <td>0</td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td data-continent="" style="display:none;"></td>,
 <td>
 </td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td style="text-align:left;">World</td>,
 <td>117,515,398</td>,
 <td>+73,922</td>,
 <td>2,606,830</td>,
 <td>+1,739</td>,
 <td>93,033,040</td>,
 <td>+71,933</td>,
 <td>21,875,528</td>,
 <td>89,642</td>,
 <td>15,076</td>,
 <td>334.4</td>,
 <td></td>,
 <td></td>,
 <td></td>,
 <td data-continent="all" style="display:none">All</td>,
 <td>
 </td>,
 <td></td>,
 <td></td>,
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">1</td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/us/">USA</a></td>,
 <td style="font-weight: bold; text-align:right">29,696,250</td>,
 <td style="font-weight: bold; text-align:right;"></td>,
 <td style="font-weight: bold; text-align:right;">537,838 </td>,
 <td style="font-weight: bold;
                                     text-align:right;"></td>,
 <td style="font-weight: bold; text-align:right">20,336,656</td>,
 <td style="font-weight: bold; text-align:right;"></td>,
 <td style="text-align:right;font-weight:bold;">8,821,756</td>,
 <td style="font-weight: bold; text-align:right">13,111</td>,
 <td style="font-weight: bold; text-align:right">89,359</td>,
 <td style="font-weight: bold; text-align:right">1,618</td>,
 <td style="font-weight: bold; text-align:right">369,210,234</td>,
 <td style="font-weight: bold; text-align:right">1,110,989</td>,
 <td style="font-weight: bold; text-align:right"><a href="/world-population/us-population/">332,325,610</a> </td>,
 <td data-continent="North America" style="display:none">North America</td>,
 <td>11</td>,
 <td>618</td>,
 <td>1</td>,
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">2</td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/india/">India</a></td>,
 <td style="font-weight: bold; text-align:right">11,229,398</td>,
 <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+127</td>,
 <td style="font-weight: bold; text-align:right;">157,890 </td>,
 <td style="font-weight: bold;
                                     text-align:right;"></td>,
 <td style="font-weight: bold; text-align:right">10,882,798</td>,
 <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+1,918</td>,
 <td style="text-align:right;font-weight:bold;">188,710</td>,
 <td style="font-weight: bold; text-align:right">8,944</td>,
 <td style="font-weight: bold; text-align:right">8,083</td>,
 <td style="font-weight: bold; text-align:right">114</td>,
 <td style="font-weight: bold; text-align:right">221,968,271</td>,
 <td style="font-weight: bold; text-align:right">159,777</td>,
 <td style="font-weight: bold; text-align:right"><a href="/world-population/india-population/">1,389,234,581</a> </td>,
 <td data-continent="Asia" style="display:none">Asia</td>,
 <td>124</td>,
 <td>8,799</td>,
 <td>6</td>,
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">3</td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/brazil/">Brazil</a></td>,
 <td style="font-weight: bold; text-align:right">11,019,344</td>,
 <td style="font-weight: bold; text-align:right;"></td>,
 <td style="font-weight: bold; text-align:right;">265,500 </td>,
 <td style="font-weight: bold;
                                     text-align:right;"></td>,
 <td style="font-weight: bold; text-align:right">9,757,178</td>,
 <td style="font-weight: bold; text-align:right;"></td>,
 <td style="text-align:right;font-weight:bold;">996,666</td>,
 <td style="font-weight: bold; text-align:right">8,318</td>,
 <td style="font-weight: bold; text-align:right">51,591</td>,
 <td style="font-weight: bold; text-align:right">1,243</td>,
 <td style="font-weight: bold; text-align:right">28,600,000</td>,
 <td style="font-weight: bold; text-align:right">133,902</td>,
 <td style="font-weight: bold; text-align:right"><a href="/world-population/brazil-population/">213,588,678</a> </td>,
 <td data-continent="South America" style="display:none">South America</td>,
 <td>19</td>,
 <td>804</td>,
 <td>7</td>,
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">4</td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/russia/">Russia</a></td>,
 <td style="font-weight: bold; text-align:right">4,333,029</td>,
 <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+10,253</td>,
 <td style="font-weight: bold; text-align:right;">89,473 </td>,
 <td style="font-weight: bold;
                                     text-align:right;background-color:red; color:white">+379</td>,
 <td style="font-weight: bold; text-align:right">3,922,246</td>,
 <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+10,322</td>,
 <td style="text-align:right;font-weight:bold;">321,310</td>,
 <td style="font-weight: bold; text-align:right">2,300</td>,
 <td style="font-weight: bold; text-align:right">29,683</td>,
 <td style="font-weight: bold; text-align:right">613</td>,
 <td style="font-weight: bold; text-align:right">113,500,000</td>,
 <td style="font-weight: bold; text-align:right">777,519</td>,
 <td style="font-weight: bold; text-align:right"><a href="/world-population/russia-population/">145,977,217</a> </td>,
 <td data-continent="Europe" style="display:none">Europe</td>,
 <td>34</td>,
 <td>1,632</td>,
 <td>1</td>,
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">5</td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/uk/">UK</a></td>,
 <td style="font-weight: bold; text-align:right">4,218,520</td>,
 <td style="font-weight: bold; text-align:right;"></td>,
 <td style="font-weight: bold; text-align:right;">124,501 </td>,
 <td style="font-weight: bold;
                                     text-align:right;"></td>,
 <td style="font-weight: bold; text-align:right">3,199,565</td>,
 <td style="font-weight: bold; text-align:right;"></td>,
 <td style="text-align:right;font-weight:bold;">894,454</td>,
 <td style="font-weight: bold; text-align:right">1,542</td>,
 <td style="font-weight: bold; text-align:right">61,919</td>,
 <td style="font-weight: bold; text-align:right">1,827</td>,
 <td style="font-weight: bold; text-align:right">94,197,029</td>,
 <td style="font-weight: bold; text-align:right">1,382,625</td>,
 <td style="font-weight: bold; text-align:right"><a href="/world-population/uk-population/">68,129,139</a> </td>,
 <td data-continent="Europe" style="display:none">Europe</td>,
 <td>16</td>,
 <td>547</td>,
 <td>1</td>,
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">6</td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/france/">France</a></td>,
 <td style="font-weight: bold; text-align:right">3,904,233</td>,
 <td style="font-weight: bold; text-align:right;"></td>,
 <td style="font-weight: bold; text-align:right;">88,574 </td>,
 <td style="font-weight: bold;
                                     text-align:right;"></td>,
 <td style="font-weight: bold; text-align:right">265,295</td>,
 <td style="font-weight: bold; text-align:right;"></td>,
 <td style="text-align:right;font-weight:bold;">3,550,364</td>,
 <td style="font-weight: bold; text-align:right">3,743</td>,
 <td style="font-weight: bold; text-align:right">59,723</td>,
 <td style="font-weight: bold; text-align:right">1,355</td>,
 <td style="font-weight: bold; text-align:right">54,979,855</td>,
 <td style="font-weight: bold; text-align:right">841,029</td>,
 <td style="font-weight: bold; text-align:right"><a href="/world-population/france-population/">65,372,120</a> </td>,
 <td data-continent="Europe" style="display:none">Europe</td>,
 <td>17</td>,
 <td>738</td>,
 <td>1</td>,
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">7</td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/spain/">Spain</a></td>,
 <td style="font-weight: bold; text-align:right">3,149,012</td>,
 <td style="font-weight: bold; text-align:right;"></td>,
 <td style="font-weight: bold; text-align:right;">71,138 </td>,
 <td style="font-weight: bold;
                                     text-align:right;"></td>,
 <td style="font-weight: bold; text-align:right">2,744,664</td>,
 <td style="font-weight: bold; text-align:right;"></td>,
 <td style="text-align:right;font-weight:bold;">333,210</td>,
 <td style="font-weight: bold; text-align:right">2,571</td>,
 <td style="font-weight: bold; text-align:right">67,334</td>,
 <td style="font-weight: bold; text-align:right">1,521</td>,
 <td style="font-weight: bold; text-align:right">39,313,189</td>,
 <td style="font-weight: bold; text-align:right">840,615</td>,
 <td style="font-weight: bold; text-align:right"><a href="/world-population/spain-population/">46,767,152</a> </td>,
 <td data-continent="Europe" style="display:none">Europe</td>,
 <td>15</td>,
 <td>657</td>,
 <td>1</td>,
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">8</td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/italy/">Italy</a></td>,
 <td style="font-weight: bold; text-align:right">3,067,486</td>,
 <td style="font-weight: bold; text-align:right;"></td>,
 <td style="font-weight: bold; text-align:right;">99,785 </td>,
 <td style="font-weight: bold;
                                     text-align:right;"></td>,
 <td style="font-weight: bold; text-align:right">2,494,839</td>,
 <td style="font-weight: bold; text-align:right;"></td>,
 <td style="text-align:right;font-weight:bold;">472,862</td>,
 <td style="font-weight: bold; text-align:right">2,605</td>,
 <td style="font-weight: bold; text-align:right">50,785</td>,
 <td style="font-weight: bold; text-align:right">1,652</td>,
 <td style="font-weight: bold; text-align:right">42,342,845</td>,
 <td style="font-weight: bold; text-align:right">701,029</td>,
 <td style="font-weight: bold; text-align:right"><a href="/world-population/italy-population/">60,401,031</a> </td>,
 <td data-continent="Europe" style="display:none">Europe</td>,
 <td>20</td>,
 <td>605</td>,
 <td>1</td>,
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">9</td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/turkey/">Turkey</a></td>,
 <td style="font-weight: bold; text-align:right">2,780,417</td>,
 <td style="font-weight: bold; text-align:right;"></td>,
 <td style="font-weight: bold; text-align:right;">29,030 </td>,
 <td style="font-weight: bold;
                                     text-align:right;"></td>,
 <td style="font-weight: bold; text-align:right">2,623,924</td>,
 <td style="font-weight: bold; text-align:right;"></td>,
 <td style="text-align:right;font-weight:bold;">127,463</td>,
 <td style="font-weight: bold; text-align:right">1,261</td>,
 <td style="font-weight: bold; text-align:right">32,728</td>,
 <td style="font-weight: bold; text-align:right">342</td>,
 <td style="font-weight: bold; text-align:right">34,122,851</td>,
 <td style="font-weight: bold; text-align:right">401,652</td>,
 <td style="font-weight: bold; text-align:right"><a href="/world-population/turkey-population/">84,956,188</a> </td>,
 <td data-continent="Asia" style="display:none">Asia</td>,
 <td>31</td>,
 <td>2,926</td>,
 <td>2</td>,
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">10</td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/germany/">Germany</a></td>,
 <td style="font-weight: bold; text-align:right">2,508,655</td>,
 <td style="font-weight: bold; text-align:right;"></td>,
 <td style="font-weight: bold; text-align:right;">72,532 </td>,
 <td style="font-weight: bold;
                                     text-align:right;"></td>,
 <td style="font-weight: bold; text-align:right">2,310,900</td>,
 <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+6,600</td>,
 <td style="text-align:right;font-weight:bold;">125,223</td>,
 <td style="font-weight: bold; text-align:right">2,848</td>,
 <td style="font-weight: bold; text-align:right">29,877</td>,
 <td style="font-weight: bold; text-align:right">864</td>,
 <td style="font-weight: bold; text-align:right">45,114,160</td>,
 <td style="font-weight: bold; text-align:right">537,286</td>,
 <td style="font-weight: bold; text-align:right"><a href="/world-population/germany-population/">83,966,763</a> </td>,
 <td data-continent="Europe" style="display:none">Europe</td>,
 <td>33</td>,
 <td>1,158</td>,
 <td>2</td>,
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">11</td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/colombia/">Colombia</a></td>,
 <td style="font-weight: bold; text-align:right">2,276,656</td>,
 <td style="font-weight: bold; text-align:right;"></td>,
 <td style="font-weight: bold; text-align:right;">60,503 </td>,
 <td style="font-weight: bold;
                                     text-align:right;"></td>,
 <td style="font-weight: bold; text-align:right">2,177,199</td>,
 <td style="font-weight: bold; text-align:right;"></td>,
 <td style="text-align:right;font-weight:bold;">38,954</td>,
 <td style="font-weight: bold; text-align:right">1,982</td>,
 <td style="font-weight: bold; text-align:right">44,421</td>,
 <td style="font-weight: bold; text-align:right">1,181</td>,
 <td style="font-weight: bold; text-align:right">11,717,598</td>,
 <td style="font-weight: bold; text-align:right">228,628</td>,
 <td style="font-weight: bold; text-align:right"><a href="/world-population/colombia-population/">51,251,703</a> </td>,
 <td data-continent="South America" style="display:none">South America</td>,
 <td>23</td>,
 <td>847</td>,
 <td>4</td>,
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">12</td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/argentina/">Argentina</a></td>,
 <td style="font-weight: bold; text-align:right">2,149,636</td>,
 <td style="font-weight: bold; text-align:right;"></td>,
 <td style="font-weight: bold; text-align:right;">52,880 </td>,
 <td style="font-weight: bold;
                                     text-align:right;"></td>,
 <td style="font-weight: bold; text-align:right">1,945,816</td>,
 <td style="font-weight: bold; text-align:right;"></td>,
 <td style="text-align:right;font-weight:bold;">150,940</td>,
 <td style="font-weight: bold; text-align:right">3,467</td>,
 <td style="font-weight: bold; text-align:right">47,268</td>,
 <td style="font-weight: bold; text-align:right">1,163</td>,
 <td style="font-weight: bold; text-align:right">7,720,598</td>,
 <td style="font-weight: bold; text-align:right">169,766</td>,
 <td style="font-weight: bold; text-align:right"><a href="/world-population/argentina-population/">45,478,006</a> </td>,
 <td data-continent="South America" style="display:none">South America</td>,
 <td>21</td>,
 <td>860</td>,
 <td>6</td>,
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">13</td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/mexico/">Mexico</a></td>,
 <td style="font-weight: bold; text-align:right">2,128,600</td>,
 <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+2,734</td>,
 <td style="font-weight: bold; text-align:right;">190,604 </td>,
 <td style="font-weight: bold;
                                     text-align:right;background-color:red; color:white">+247</td>,
 <td style="font-weight: bold; text-align:right">1,670,431</td>,
 <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+3,773</td>,
 <td style="text-align:right;font-weight:bold;">267,565</td>,
 <td style="font-weight: bold; text-align:right">4,798</td>,
 <td style="font-weight: bold; text-align:right">16,392</td>,
 <td style="font-weight: bold; text-align:right">1,468</td>,
 <td style="font-weight: bold; text-align:right">5,619,656</td>,
 <td style="font-weight: bold; text-align:right">43,277</td>,
 <td style="font-weight: bold; text-align:right"><a href="/world-population/mexico-population/">129,854,012</a> </td>,
 <td data-continent="North America" style="display:none">North America</td>,
 <td>61</td>,
 <td>681</td>,
 <td>23</td>,
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">14</td>,
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/poland/">Poland</a></td>,
 <td style="font-weight: bold; text-align:right">1,801,083</td>,
 <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+6,170</td>,
 <td style="font-weight: bold; text-align:right;">45,317 </td>,
 <td style="font-weight: bold;
                                     text-align:right;background-color:red; color:white">+32</td>,
 <td style="font-weight: bold; text-align:right">1,494,083</td>,
 <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+11,515</td>,
 <td style="text-align:right;font-weight:bold;">261,683</td>,

# get the name of the countries!

In [7]:
def get_country_names(soup):
    '''get all the names of the listed countries'''
    return [i.string for i in soup.find_all( style="font-weight: bold; font-size:15px; text-align:left;" )]

In [8]:
countries = get_country_names(soup)
countries

['USA',
 'India',
 'Brazil',
 'Russia',
 'UK',
 'France',
 'Spain',
 'Italy',
 'Turkey',
 'Germany',
 'Colombia',
 'Argentina',
 'Mexico',
 'Poland',
 'Iran',
 'South Africa',
 'Ukraine',
 'Indonesia',
 'Peru',
 'Czechia',
 'Netherlands',
 'Canada',
 'Chile',
 'Romania',
 'Portugal',
 'Israel',
 'Belgium',
 'Iraq',
 'Sweden',
 'Philippines',
 'Pakistan',
 'Switzerland',
 'Bangladesh',
 'Morocco',
 'Serbia',
 'Austria',
 'Hungary',
 'Japan',
 'Jordan',
 'UAE',
 'Lebanon',
 'Saudi Arabia',
 'Panama',
 'Slovakia',
 'Malaysia',
 'Belarus',
 'Ecuador',
 'Nepal',
 'Georgia',
 'Bulgaria',
 'Bolivia',
 'Croatia',
 'Dominican Republic',
 'Tunisia',
 'Azerbaijan',
 'Ireland',
 'Kazakhstan',
 'Denmark',
 'Costa Rica',
 'Greece',
 'Lithuania',
 'Kuwait',
 'Palestine',
 'Slovenia',
 'Moldova',
 'Egypt',
 'Guatemala',
 'Armenia',
 'Honduras',
 'Paraguay',
 'Qatar',
 'Ethiopia',
 'Nigeria',
 'Oman',
 'Venezuela',
 'Myanmar',
 'Libya',
 'Bosnia and Herzegovina',
 'Bahrain',
 'Algeria',
 'Albania',
 'Kenya',
 'North Macedonia',
 'S. Korea',
 'Latvia',
 'Kyrgyzstan',
 'Ghana',
 'Sri Lanka',
 'Zambia',
 'Uzbekistan',
 'Montenegro',
 'Estonia',
 'Norway',
 'Uruguay',
 'Finland',
 'Mozambique',
 'El Salvador',
 'Singapore',
 'Luxembourg',
 'Afghanistan',
 'Cuba',
 'Uganda',
 'Namibia',
 'Cyprus',
 'Zimbabwe',
 'Senegal',
 'Cameroon',
 'Ivory Coast',
 'Malawi',
 'Botswana',
 'Australia',
 'Sudan',
 'DRC',
 'Thailand',
 'Jamaica',
 'Malta',
 'Angola',
 'Maldives',
 'Madagascar',
 'Rwanda',
 'French Polynesia',
 'Mayotte',
 'Mauritania',
 'Eswatini',
 'French Guiana',
 'Guinea',
 'Syria',
 'Cabo Verde',
 'Gabon',
 'Tajikistan',
 'Réunion',
 'Haiti',
 'Belize',
 'Burkina Faso',
 'Hong Kong',
 'Andorra',
 'Lesotho',
 'Guadeloupe',
 'Congo',
 'Suriname',
 'Guyana',
 'South Sudan',
 'Bahamas',
 'Mali',
 'Somalia',
 'Aruba',
 'Trinidad and Tobago',
 'Togo',
 'Martinique',
 'Nicaragua',
 'Equatorial Guinea',
 'Benin',
 'Djibouti',
 'Iceland',
 'CAR',
 'Niger',
 'Curaçao',
 'Gambia',
 'Gibraltar',
 'Chad',
 'Channel Islands',
 'San Marino',
 'Sierra Leone',
 'Saint Lucia',
 'Comoros',
 'Mongolia',
 'Guinea-Bissau',
 'Barbados',
 'Seychelles',
 'Eritrea',
 'Liechtenstein',
 'Vietnam',
 'Yemen',
 'New Zealand',
 'Burundi',
 'Turks and Caicos',
 'Sint Maarten',
 'Liberia',
 'Monaco',
 'Sao Tome and Principe',
 'Papua New Guinea',
 'St. Vincent Grenadines',
 'Saint Martin',
 'Cambodia',
 'Taiwan',
 'Bhutan',
 'Antigua and Barbuda',
 'Isle of Man',
 'Bermuda',
 'Diamond Princess',
 'Faeroe Islands',
 'Mauritius',
 'St. Barth',
 'Caribbean Netherlands',
 'Tanzania',
 'Cayman Islands',
 'Brunei ',
 'British Virgin Islands',
 'Grenada',
 'Dominica',
 'Timor-Leste',
 'New Caledonia',
 'Fiji',
 'Falkland Islands',
 'Macao',
 'Laos',
 'Saint Kitts and Nevis',
 'Greenland',
 'Vatican City',
 'Saint Pierre Miquelon',
 'Montserrat',
 'Anguilla',
 'Solomon Islands',
 'Wallis and Futuna',
 'Western Sahara',
 'MS Zaandam',
 'Marshall Islands',
 'Samoa',
 'Vanuatu',
 'Micronesia',
 'China',
 'China',
 'USA',
 'India',
 'Brazil',
 'Russia',
 'UK',
 'France',
 'Spain',
 'Italy',
 'Turkey',
 'Germany',
 'Colombia',
 'Argentina',
 'Mexico',
 'Poland',
 'Iran',
 'South Africa',
 'Ukraine',
 'Indonesia',
 'Peru',
 'Czechia',
 'Netherlands',
 'Canada',
 'Chile',
 'Romania',
 'Portugal',
 'Israel',
 'Belgium',
 'Iraq',
 'Sweden',
 'Philippines',
 'Pakistan',
 'Switzerland',
 'Bangladesh',
 'Morocco',
 'Serbia',
 'Austria',
 'Hungary',
 'Japan',
 'Jordan',
 'UAE',
 'Lebanon',
 'Saudi Arabia',
 'Panama',
 'Slovakia',
 'Malaysia',
 'Belarus',
 'Ecuador',
 'Nepal',
 'Georgia',
 'Bulgaria',
 'Bolivia',
 'Croatia',
 'Dominican Republic',
 'Tunisia',
 'Azerbaijan',
 'Ireland',
 'Kazakhstan',
 'Denmark',
 'Costa Rica',
 'Greece',
 'Lithuania',
 'Kuwait',
 'Palestine',
 'Slovenia',
 'Moldova',
 'Egypt',
 'Guatemala',
 'Armenia',
 'Honduras',
 'Paraguay',
 'Qatar',
 'Ethiopia',
 'Nigeria',
 'Oman',
 'Venezuela',
 'Myanmar',
 'Libya',
 'Bosnia and Herzegovina',
 'Bahrain',
 'Algeria',
 'Albania',
 'Kenya',
 'North Macedonia',
 'S. Korea',
 'Latvia',
 'Kyrgyzstan',
 'Ghana',
 'Sri Lanka',
 'Zambia',
 'Uzbekistan',
 'Montenegro',
 'Estonia',
 'Norway',
 'Uruguay',
 'Mozambique',
 'Finland',
 'El Salvador',
 'Singapore',
 'Luxembourg',
 'Afghanistan',
 'Cuba',
 'Uganda',
 'Namibia',
 'Cyprus',
 'Zimbabwe',
 'Senegal',
 'Cameroon',
 'Ivory Coast',
 'Malawi',
 'Botswana',
 'Australia',
 'Sudan',
 'DRC',
 'Thailand',
 'Jamaica',
 'Malta',
 'Angola',
 'Maldives',
 'Madagascar',
 'Rwanda',
 'French Polynesia',
 'Mayotte',
 'Mauritania',
 'Eswatini',
 'French Guiana',
 'Guinea',
 'Syria',
 'Cabo Verde',
 'Gabon',
 'Tajikistan',
 'Réunion',
 'Haiti',
 'Belize',
 'Burkina Faso',
 'Hong Kong',
 'Andorra',
 'Lesotho',
 'Guadeloupe',
 'Congo',
 'Suriname',
 'Guyana',
 'South Sudan',
 'Bahamas',
 'Mali',
 'Somalia',
 'Aruba',
 'Trinidad and Tobago',
 'Togo',
 'Martinique',
 'Nicaragua',
 'Benin',
 'Equatorial Guinea',
 'Djibouti',
 'Iceland',
 'CAR',
 'Niger',
 'Curaçao',
 'Gambia',
 'Gibraltar',
 'Chad',
 'Channel Islands',
 'San Marino',
 'Sierra Leone',
 'Saint Lucia',
 'Comoros',
 'Guinea-Bissau',
 'Barbados',
 'Mongolia',
 'Seychelles',
 'Eritrea',
 'Liechtenstein',
 'Vietnam',
 'Yemen',
 'New Zealand',
 'Burundi',
 'Turks and Caicos',
 'Sint Maarten',
 'Liberia',
 'Monaco',
 'Sao Tome and Principe',
 'St. Vincent Grenadines',
 'Papua New Guinea',
 'Saint Martin',
 'Cambodia',
 'Taiwan',
 'Bhutan',
 'Antigua and Barbuda',
 'Isle of Man',
 'Bermuda',
 'Diamond Princess',
 'Faeroe Islands',
 'Mauritius',
 'St. Barth',
 'Caribbean Netherlands',
 'Tanzania',
 'Cayman Islands',
 'Brunei ',
 'British Virgin Islands',
 'Grenada',
 'Dominica',
 'Timor-Leste',
 'New Caledonia',
 'Fiji',
 'Falkland Islands',
 'Macao',
 'Laos',
 'Saint Kitts and Nevis',
 'Greenland',
 'Vatican City',
 'Saint Pierre Miquelon',
 'Montserrat',
 'Anguilla',
 'Solomon Islands',
 'Western Sahara',
 'Wallis and Futuna',
 'MS Zaandam',
 'Marshall Islands',
 'Samoa',
 'Micronesia',
 'Vanuatu',
 'China',
 'USA',
 'India',
 'Brazil',
 'Russia',
 'UK',
 'France',
 'Spain',
 'Italy',
 'Turkey',
 'Germany',
 'Colombia',
 'Argentina',
 'Mexico',
 'Poland',
 'Iran',
 'South Africa',
 'Ukraine',
 'Indonesia',
 'Peru',
 'Czechia',
 'Netherlands',
 'Canada',
 'Chile',
 'Romania',
 'Portugal',
 'Israel',
 'Belgium',
 'Iraq',
 'Sweden',
 'Philippines',
 'Pakistan',
 'Switzerland',
 'Bangladesh',
 'Morocco',
 'Serbia',
 'Austria',
 'Hungary',
 'Japan',
 'Jordan',
 'UAE',
 'Lebanon',
 'Saudi Arabia',
 'Panama',
 'Slovakia',
 'Malaysia',
 'Belarus',
 'Ecuador',
 'Nepal',
 'Georgia',
 'Bulgaria',
 'Bolivia',
 'Croatia',
 'Dominican Republic',
 'Tunisia',
 'Azerbaijan',
 'Ireland',
 'Kazakhstan',
 'Denmark',
 'Costa Rica',
 'Greece',
 'Lithuania',
 'Kuwait',
 'Slovenia',
 'Moldova',
 'Palestine',
 'Egypt',
 'Guatemala',
 'Armenia',
 'Honduras',
 'Paraguay',
 'Qatar',
 'Ethiopia',
 'Nigeria',
 'Oman',
 'Myanmar',
 'Venezuela',
 'Libya',
 'Bosnia and Herzegovina',
 'Bahrain',
 'Algeria',
 'Albania',
 'Kenya',
 'North Macedonia',
 'S. Korea',
 'Latvia',
 'Kyrgyzstan',
 'Ghana',
 'Sri Lanka',
 'Zambia',
 'Uzbekistan',
 'Montenegro',
 'Norway',
 'Estonia',
 'Uruguay',
 'Mozambique',
 'Finland',
 'El Salvador',
 'Singapore',
 'Luxembourg',
 'Afghanistan',
 'Cuba',
 'Uganda',
 'Namibia',
 'Cyprus',
 'Zimbabwe',
 'Cameroon',
 'Senegal',
 'Ivory Coast',
 'Malawi',
 'Botswana',
 'Australia',
 'Sudan',
 'DRC',
 'Thailand',
 'Jamaica',
 'Malta',
 'Angola',
 'Maldives',
 'Madagascar',
 'Rwanda',
 'French Polynesia',
 'Mayotte',
 'Mauritania',
 'Eswatini',
 'French Guiana',
 'Guinea',
 'Syria',
 'Cabo Verde',
 'Gabon',
 'Tajikistan',
 'Réunion',
 'Haiti',
 'Belize',
 'Burkina Faso',
 'Hong Kong',
 'Andorra',
 'Lesotho',
 'Guadeloupe',
 'Congo',
 'Suriname',
 'Guyana',
 'South Sudan',
 'Bahamas',
 'Mali',
 'Aruba',
 'Somalia',
 'Trinidad and Tobago',
 'Togo',
 'Martinique',
 'Nicaragua',
 'Benin',
 'Equatorial Guinea',
 'Djibouti',
 'Iceland',
 'CAR',
 'Niger',
 'Curaçao',
 'Gambia',
 'Gibraltar',
 'Chad',
 'Channel Islands',
 'San Marino',
 'Sierra Leone',
 'Saint Lucia',
 'Comoros',
 'Guinea-Bissau',
 'Barbados',
 'Mongolia',
 'Seychelles',
 'Eritrea',
 'Liechtenstein',
 'Vietnam',
 'Yemen',
 'New Zealand',
 'Burundi',
 'Turks and Caicos',
 'Sint Maarten',
 'Liberia',
 'Monaco',
 'Sao Tome and Principe',
 'St. Vincent Grenadines',
 'Saint Martin',
 'Papua New Guinea',
 'Taiwan',
 'Cambodia',
 'Bhutan',
 'Antigua and Barbuda',
 'Bermuda',
 'Diamond Princess',
 'Isle of Man',
 'Faeroe Islands',
 'Mauritius',
 'St. Barth',
 'Caribbean Netherlands',
 'Tanzania',
 'Cayman Islands',
 'Brunei ',
 'British Virgin Islands',
 'Grenada',
 'Dominica',
 'Timor-Leste',
 'Fiji',
 'New Caledonia',
 'Falkland Islands',
 'Macao',
 'Laos',
 'Saint Kitts and Nevis',
 'Greenland',
 'Vatican City',
 'Saint Pierre Miquelon',
 'Montserrat',
 'Anguilla',
 'Solomon Islands',
 'Western Sahara',
 'MS Zaandam',
 'Wallis and Futuna',
 'Marshall Islands',
 'Samoa',
 'Micronesia',
 'Vanuatu']

In [9]:
len(countries)

663

-----------------------

# get the indices of each nation in the list

In [10]:
def get_country_indexes(countrylist):
    '''get the indexes where the countries are cited in the soup.
    This is done because we have no better insight of where to look at.
    So we use theese indexes and then parse their data in the next function'''
    indexes = {}
    for i in countrylist:
        indexes[i] = 'Notfound'

    countries_data = get_data(soup) 

    for i in countrylist:
        j=0
        while indexes[i] != 'NotFound' and j <= len(countries_data):
            if countries_data[j].string == i:
                indexes[i] = j
                break
            else:
                j+=1
    return indexes

In [11]:
get_country_indexes(countries[0:3])

{'USA': 153, 'India': 172, 'Brazil': 191}

## do the same for the world!

In [12]:
%%time
def get_world_index():
    j=0
    x=get_data(soup)
    while x[j].string != 'World':
        j+=1
    else:
        return j

world_index = get_world_index()

Wall time: 26 ms

--------------

## found the indices, now find the list!

first code the fucmtion to replace the missing population

In [13]:
 def get_pops(soup):
    pops = {}
    for i in get_data(soup):
        j = i.find('a', class_= '')
        if j != None:
            countryname = re.findall('population/(.+)-population/',str(j))
            #print(countryname[0],j.string)
            #number = int(str(j.string).replace(',',''))
            pops[countryname[0]] = j.string
    if 'us' in pops.keys(): 
        pops['usa'] = pops['us']
    return pops

In [14]:
pops=  get_pops(soup)

then code the function to get a country

In [15]:
def get_one_country_index(soup, country):
    j=0
    x=get_data(soup) #depreciated
    #x=soup
    while x[j].string != str(country):
        j+=1
    else:
        index = j
    
    
    return index

In [16]:
get_one_country_index(soup, 'Argentina')

362

In [17]:
def get_country_data(soup , index):
    x=soup 
    x=get_data(soup) #depreciated
    data = x[index:index+15]
    
    
    data = [i.string for i in data] #.lstrip('+') #put every number as a string
    
    if data[0].lower() in get_pops(soup).keys():
        data[-2] =pops[data[0].string.lower()] #put the info about the total  population

    
#     newdata=[]
#     for i in data[1:-1]:
#         if  i != None and i != 'N/A':
#             number=''
#             for j in i:
#                 if j in '0123456789':
#                     number+=j
#             newdata.append(number)
#         else:
#             newdata.append('NA')
#     data[1:-1] = newdata
    data[1:-1] = ['NA' if i == None or i ==  'N/A' or i.strip() == '' else i for i in data[1:-1]]
    data[1:-1] = [float(i.replace(',','')) if i != 'NA' else i for i in data[1:-1]] #I don't merge these two just in case some strange data appears
    
    #data[1:-1] = [ int(float(i.replace(',',''))) if i != None and i != 'N/A' and i!= ''  else 'NA' for i in data[1:-1]] # put every number as an int, and replace the missing vals with na



    return data

In [18]:
get_country_data(soup,world_index)

['World',
 117515398.0,
 73922.0,
 2606830.0,
 1739.0,
 93033040.0,
 71933.0,
 21875528.0,
 89642.0,
 15076.0,
 334.4,
 'NA',
 'NA',
 'NA',
 'All']

In [19]:
example = get_country_data(soup, 362)

In [20]:
example

['Argentina',
 2149636.0,
 'NA',
 52880.0,
 'NA',
 1945816.0,
 'NA',
 150940.0,
 3467.0,
 47268.0,
 1163.0,
 7720598.0,
 169766.0,
 45478006.0,
 'South America']

# make the df

In [21]:
world_index = get_world_index()
world_index

134

In [22]:
countries = get_country_names(soup)
indexes =  get_country_indexes(countries)

In [23]:
pops = get_pops(soup)

In [24]:
countries

['USA',
 'India',
 'Brazil',
 'Russia',
 'UK',
 'France',
 'Spain',
 'Italy',
 'Turkey',
 'Germany',
 'Colombia',
 'Argentina',
 'Mexico',
 'Poland',
 'Iran',
 'South Africa',
 'Ukraine',
 'Indonesia',
 'Peru',
 'Czechia',
 'Netherlands',
 'Canada',
 'Chile',
 'Romania',
 'Portugal',
 'Israel',
 'Belgium',
 'Iraq',
 'Sweden',
 'Philippines',
 'Pakistan',
 'Switzerland',
 'Bangladesh',
 'Morocco',
 'Serbia',
 'Austria',
 'Hungary',
 'Japan',
 'Jordan',
 'UAE',
 'Lebanon',
 'Saudi Arabia',
 'Panama',
 'Slovakia',
 'Malaysia',
 'Belarus',
 'Ecuador',
 'Nepal',
 'Georgia',
 'Bulgaria',
 'Bolivia',
 'Croatia',
 'Dominican Republic',
 'Tunisia',
 'Azerbaijan',
 'Ireland',
 'Kazakhstan',
 'Denmark',
 'Costa Rica',
 'Greece',
 'Lithuania',
 'Kuwait',
 'Palestine',
 'Slovenia',
 'Moldova',
 'Egypt',
 'Guatemala',
 'Armenia',
 'Honduras',
 'Paraguay',
 'Qatar',
 'Ethiopia',
 'Nigeria',
 'Oman',
 'Venezuela',
 'Myanmar',
 'Libya',
 'Bosnia and Herzegovina',
 'Bahrain',
 'Algeria',
 'Albania',
 'Kenya',
 'North Macedonia',
 'S. Korea',
 'Latvia',
 'Kyrgyzstan',
 'Ghana',
 'Sri Lanka',
 'Zambia',
 'Uzbekistan',
 'Montenegro',
 'Estonia',
 'Norway',
 'Uruguay',
 'Finland',
 'Mozambique',
 'El Salvador',
 'Singapore',
 'Luxembourg',
 'Afghanistan',
 'Cuba',
 'Uganda',
 'Namibia',
 'Cyprus',
 'Zimbabwe',
 'Senegal',
 'Cameroon',
 'Ivory Coast',
 'Malawi',
 'Botswana',
 'Australia',
 'Sudan',
 'DRC',
 'Thailand',
 'Jamaica',
 'Malta',
 'Angola',
 'Maldives',
 'Madagascar',
 'Rwanda',
 'French Polynesia',
 'Mayotte',
 'Mauritania',
 'Eswatini',
 'French Guiana',
 'Guinea',
 'Syria',
 'Cabo Verde',
 'Gabon',
 'Tajikistan',
 'Réunion',
 'Haiti',
 'Belize',
 'Burkina Faso',
 'Hong Kong',
 'Andorra',
 'Lesotho',
 'Guadeloupe',
 'Congo',
 'Suriname',
 'Guyana',
 'South Sudan',
 'Bahamas',
 'Mali',
 'Somalia',
 'Aruba',
 'Trinidad and Tobago',
 'Togo',
 'Martinique',
 'Nicaragua',
 'Equatorial Guinea',
 'Benin',
 'Djibouti',
 'Iceland',
 'CAR',
 'Niger',
 'Curaçao',
 'Gambia',
 'Gibraltar',
 'Chad',
 'Channel Islands',
 'San Marino',
 'Sierra Leone',
 'Saint Lucia',
 'Comoros',
 'Mongolia',
 'Guinea-Bissau',
 'Barbados',
 'Seychelles',
 'Eritrea',
 'Liechtenstein',
 'Vietnam',
 'Yemen',
 'New Zealand',
 'Burundi',
 'Turks and Caicos',
 'Sint Maarten',
 'Liberia',
 'Monaco',
 'Sao Tome and Principe',
 'Papua New Guinea',
 'St. Vincent Grenadines',
 'Saint Martin',
 'Cambodia',
 'Taiwan',
 'Bhutan',
 'Antigua and Barbuda',
 'Isle of Man',
 'Bermuda',
 'Diamond Princess',
 'Faeroe Islands',
 'Mauritius',
 'St. Barth',
 'Caribbean Netherlands',
 'Tanzania',
 'Cayman Islands',
 'Brunei ',
 'British Virgin Islands',
 'Grenada',
 'Dominica',
 'Timor-Leste',
 'New Caledonia',
 'Fiji',
 'Falkland Islands',
 'Macao',
 'Laos',
 'Saint Kitts and Nevis',
 'Greenland',
 'Vatican City',
 'Saint Pierre Miquelon',
 'Montserrat',
 'Anguilla',
 'Solomon Islands',
 'Wallis and Futuna',
 'Western Sahara',
 'MS Zaandam',
 'Marshall Islands',
 'Samoa',
 'Vanuatu',
 'Micronesia',
 'China',
 'China',
 'USA',
 'India',
 'Brazil',
 'Russia',
 'UK',
 'France',
 'Spain',
 'Italy',
 'Turkey',
 'Germany',
 'Colombia',
 'Argentina',
 'Mexico',
 'Poland',
 'Iran',
 'South Africa',
 'Ukraine',
 'Indonesia',
 'Peru',
 'Czechia',
 'Netherlands',
 'Canada',
 'Chile',
 'Romania',
 'Portugal',
 'Israel',
 'Belgium',
 'Iraq',
 'Sweden',
 'Philippines',
 'Pakistan',
 'Switzerland',
 'Bangladesh',
 'Morocco',
 'Serbia',
 'Austria',
 'Hungary',
 'Japan',
 'Jordan',
 'UAE',
 'Lebanon',
 'Saudi Arabia',
 'Panama',
 'Slovakia',
 'Malaysia',
 'Belarus',
 'Ecuador',
 'Nepal',
 'Georgia',
 'Bulgaria',
 'Bolivia',
 'Croatia',
 'Dominican Republic',
 'Tunisia',
 'Azerbaijan',
 'Ireland',
 'Kazakhstan',
 'Denmark',
 'Costa Rica',
 'Greece',
 'Lithuania',
 'Kuwait',
 'Palestine',
 'Slovenia',
 'Moldova',
 'Egypt',
 'Guatemala',
 'Armenia',
 'Honduras',
 'Paraguay',
 'Qatar',
 'Ethiopia',
 'Nigeria',
 'Oman',
 'Venezuela',
 'Myanmar',
 'Libya',
 'Bosnia and Herzegovina',
 'Bahrain',
 'Algeria',
 'Albania',
 'Kenya',
 'North Macedonia',
 'S. Korea',
 'Latvia',
 'Kyrgyzstan',
 'Ghana',
 'Sri Lanka',
 'Zambia',
 'Uzbekistan',
 'Montenegro',
 'Estonia',
 'Norway',
 'Uruguay',
 'Mozambique',
 'Finland',
 'El Salvador',
 'Singapore',
 'Luxembourg',
 'Afghanistan',
 'Cuba',
 'Uganda',
 'Namibia',
 'Cyprus',
 'Zimbabwe',
 'Senegal',
 'Cameroon',
 'Ivory Coast',
 'Malawi',
 'Botswana',
 'Australia',
 'Sudan',
 'DRC',
 'Thailand',
 'Jamaica',
 'Malta',
 'Angola',
 'Maldives',
 'Madagascar',
 'Rwanda',
 'French Polynesia',
 'Mayotte',
 'Mauritania',
 'Eswatini',
 'French Guiana',
 'Guinea',
 'Syria',
 'Cabo Verde',
 'Gabon',
 'Tajikistan',
 'Réunion',
 'Haiti',
 'Belize',
 'Burkina Faso',
 'Hong Kong',
 'Andorra',
 'Lesotho',
 'Guadeloupe',
 'Congo',
 'Suriname',
 'Guyana',
 'South Sudan',
 'Bahamas',
 'Mali',
 'Somalia',
 'Aruba',
 'Trinidad and Tobago',
 'Togo',
 'Martinique',
 'Nicaragua',
 'Benin',
 'Equatorial Guinea',
 'Djibouti',
 'Iceland',
 'CAR',
 'Niger',
 'Curaçao',
 'Gambia',
 'Gibraltar',
 'Chad',
 'Channel Islands',
 'San Marino',
 'Sierra Leone',
 'Saint Lucia',
 'Comoros',
 'Guinea-Bissau',
 'Barbados',
 'Mongolia',
 'Seychelles',
 'Eritrea',
 'Liechtenstein',
 'Vietnam',
 'Yemen',
 'New Zealand',
 'Burundi',
 'Turks and Caicos',
 'Sint Maarten',
 'Liberia',
 'Monaco',
 'Sao Tome and Principe',
 'St. Vincent Grenadines',
 'Papua New Guinea',
 'Saint Martin',
 'Cambodia',
 'Taiwan',
 'Bhutan',
 'Antigua and Barbuda',
 'Isle of Man',
 'Bermuda',
 'Diamond Princess',
 'Faeroe Islands',
 'Mauritius',
 'St. Barth',
 'Caribbean Netherlands',
 'Tanzania',
 'Cayman Islands',
 'Brunei ',
 'British Virgin Islands',
 'Grenada',
 'Dominica',
 'Timor-Leste',
 'New Caledonia',
 'Fiji',
 'Falkland Islands',
 'Macao',
 'Laos',
 'Saint Kitts and Nevis',
 'Greenland',
 'Vatican City',
 'Saint Pierre Miquelon',
 'Montserrat',
 'Anguilla',
 'Solomon Islands',
 'Western Sahara',
 'Wallis and Futuna',
 'MS Zaandam',
 'Marshall Islands',
 'Samoa',
 'Micronesia',
 'Vanuatu',
 'China',
 'USA',
 'India',
 'Brazil',
 'Russia',
 'UK',
 'France',
 'Spain',
 'Italy',
 'Turkey',
 'Germany',
 'Colombia',
 'Argentina',
 'Mexico',
 'Poland',
 'Iran',
 'South Africa',
 'Ukraine',
 'Indonesia',
 'Peru',
 'Czechia',
 'Netherlands',
 'Canada',
 'Chile',
 'Romania',
 'Portugal',
 'Israel',
 'Belgium',
 'Iraq',
 'Sweden',
 'Philippines',
 'Pakistan',
 'Switzerland',
 'Bangladesh',
 'Morocco',
 'Serbia',
 'Austria',
 'Hungary',
 'Japan',
 'Jordan',
 'UAE',
 'Lebanon',
 'Saudi Arabia',
 'Panama',
 'Slovakia',
 'Malaysia',
 'Belarus',
 'Ecuador',
 'Nepal',
 'Georgia',
 'Bulgaria',
 'Bolivia',
 'Croatia',
 'Dominican Republic',
 'Tunisia',
 'Azerbaijan',
 'Ireland',
 'Kazakhstan',
 'Denmark',
 'Costa Rica',
 'Greece',
 'Lithuania',
 'Kuwait',
 'Slovenia',
 'Moldova',
 'Palestine',
 'Egypt',
 'Guatemala',
 'Armenia',
 'Honduras',
 'Paraguay',
 'Qatar',
 'Ethiopia',
 'Nigeria',
 'Oman',
 'Myanmar',
 'Venezuela',
 'Libya',
 'Bosnia and Herzegovina',
 'Bahrain',
 'Algeria',
 'Albania',
 'Kenya',
 'North Macedonia',
 'S. Korea',
 'Latvia',
 'Kyrgyzstan',
 'Ghana',
 'Sri Lanka',
 'Zambia',
 'Uzbekistan',
 'Montenegro',
 'Norway',
 'Estonia',
 'Uruguay',
 'Mozambique',
 'Finland',
 'El Salvador',
 'Singapore',
 'Luxembourg',
 'Afghanistan',
 'Cuba',
 'Uganda',
 'Namibia',
 'Cyprus',
 'Zimbabwe',
 'Cameroon',
 'Senegal',
 'Ivory Coast',
 'Malawi',
 'Botswana',
 'Australia',
 'Sudan',
 'DRC',
 'Thailand',
 'Jamaica',
 'Malta',
 'Angola',
 'Maldives',
 'Madagascar',
 'Rwanda',
 'French Polynesia',
 'Mayotte',
 'Mauritania',
 'Eswatini',
 'French Guiana',
 'Guinea',
 'Syria',
 'Cabo Verde',
 'Gabon',
 'Tajikistan',
 'Réunion',
 'Haiti',
 'Belize',
 'Burkina Faso',
 'Hong Kong',
 'Andorra',
 'Lesotho',
 'Guadeloupe',
 'Congo',
 'Suriname',
 'Guyana',
 'South Sudan',
 'Bahamas',
 'Mali',
 'Aruba',
 'Somalia',
 'Trinidad and Tobago',
 'Togo',
 'Martinique',
 'Nicaragua',
 'Benin',
 'Equatorial Guinea',
 'Djibouti',
 'Iceland',
 'CAR',
 'Niger',
 'Curaçao',
 'Gambia',
 'Gibraltar',
 'Chad',
 'Channel Islands',
 'San Marino',
 'Sierra Leone',
 'Saint Lucia',
 'Comoros',
 'Guinea-Bissau',
 'Barbados',
 'Mongolia',
 'Seychelles',
 'Eritrea',
 'Liechtenstein',
 'Vietnam',
 'Yemen',
 'New Zealand',
 'Burundi',
 'Turks and Caicos',
 'Sint Maarten',
 'Liberia',
 'Monaco',
 'Sao Tome and Principe',
 'St. Vincent Grenadines',
 'Saint Martin',
 'Papua New Guinea',
 'Taiwan',
 'Cambodia',
 'Bhutan',
 'Antigua and Barbuda',
 'Bermuda',
 'Diamond Princess',
 'Isle of Man',
 'Faeroe Islands',
 'Mauritius',
 'St. Barth',
 'Caribbean Netherlands',
 'Tanzania',
 'Cayman Islands',
 'Brunei ',
 'British Virgin Islands',
 'Grenada',
 'Dominica',
 'Timor-Leste',
 'Fiji',
 'New Caledonia',
 'Falkland Islands',
 'Macao',
 'Laos',
 'Saint Kitts and Nevis',
 'Greenland',
 'Vatican City',
 'Saint Pierre Miquelon',
 'Montserrat',
 'Anguilla',
 'Solomon Islands',
 'Western Sahara',
 'MS Zaandam',
 'Wallis and Futuna',
 'Marshall Islands',
 'Samoa',
 'Micronesia',
 'Vanuatu']

In [25]:
pops

{'us': '332,325,610',
 'india': '1,389,234,581',
 'brazil': '213,588,678',
 'russia': '145,977,217',
 'uk': '68,129,139',
 'france': '65,372,120',
 'spain': '46,767,152',
 'italy': '60,401,031',
 'turkey': '84,956,188',
 'germany': '83,966,763',
 'colombia': '51,251,703',
 'argentina': '45,478,006',
 'mexico': '129,854,012',
 'poland': '37,818,271',
 'iran': '84,723,260',
 'south-africa': '59,816,708',
 'ukraine': '43,553,756',
 'indonesia': '275,490,587',
 'peru': '33,283,687',
 'czech-republic': '10,722,547',
 'netherlands': '17,160,756',
 'canada': '37,967,395',
 'chile': '19,227,901',
 'romania': '19,149,746',
 'portugal': '10,176,366',
 'belgium': '11,624,025',
 'iraq': '40,832,575',
 'sweden': '10,142,180',
 'philippines': '110,571,603',
 'pakistan': '223,796,108',
 'switzerland': '8,697,732',
 'bangladesh': '165,805,536',
 'morocco': '37,207,897',
 'serbia': '8,713,279',
 'austria': '9,041,426',
 'hungary': '9,643,570',
 'japan': '126,211,526',
 'jordan': '10,272,040',
 'united-arab-emirates': '9,971,608',
 'lebanon': '6,804,518',
 'saudi-arabia': '35,181,661',
 'panama': '4,360,839',
 'slovakia': '5,461,449',
 'malaysia': '32,647,699',
 'belarus': '9,447,199',
 'ecuador': '17,824,828',
 'nepal': '29,491,862',
 'georgia': '3,983,930',
 'bulgaria': '6,912,588',
 'bolivia': '11,781,142',
 'croatia': '4,087,922',
 'dominican-republic': '10,921,909',
 'tunisia': '11,902,725',
 'azerbaijan': '10,201,374',
 'ireland': '4,975,285',
 'kazakhstan': '18,929,342',
 'denmark': '5,806,120',
 'costa-rica': '5,125,775',
 'greece': '10,388,190',
 'lithuania': '2,696,184',
 'kuwait': '4,313,432',
 'state-of-palestine': '5,181,536',
 'slovenia': '2,079,133',
 'moldova': '4,027,550',
 'egypt': '103,641,488',
 'guatemala': '18,140,040',
 'armenia': '2,967,025',
 'honduras': '10,011,450',
 'paraguay': '7,192,070',
 'ethiopia': '116,885,985',
 'nigeria': '209,588,670',
 'oman': '5,194,270',
 'venezuela': '28,380,814',
 'myanmar': '54,658,316',
 'libya': '6,934,740',
 'bosnia-and-herzegovina': '3,266,837',
 'bahrain': '1,741,286',
 'algeria': '44,387,503',
 'albania': '2,875,649',
 'kenya': '54,572,056',
 'macedonia': '2,083,316',
 'south-korea': '51,299,326',
 'latvia': '1,871,882',
 'kyrgyzstan': '6,597,178',
 'ghana': '31,511,718',
 'sri-lanka': '21,474,491',
 'zambia': '18,730,918',
 'uzbekistan': '33,798,429',
 'montenegro': '628,120',
 'estonia': '1,327,144',
 'norway': '5,450,108',
 'uruguay': '3,481,944',
 'finland': '5,546,598',
 'mozambique': '31,845,546',
 'el-salvador': '6,508,520',
 'singapore': '5,881,673',
 'luxembourg': '632,884',
 'afghanistan': '39,520,907',
 'cuba': '11,321,890',
 'uganda': '46,712,588',
 'namibia': '2,572,079',
 'cyprus': '1,213,346',
 'zimbabwe': '15,009,772',
 'senegal': '17,041,545',
 'cameroon': '26,991,917',
 'cote-d-ivoire': '26,819,239',
 'malawi': '19,463,468',
 'botswana': '2,383,759',
 'australia': '25,700,990',
 'sudan': '44,540,939',
 'democratic-republic-of-the-congo': '91,393,931',
 'thailand': '69,919,538',
 'jamaica': '2,969,982',
 'malta': '442,346',
 'angola': '33,554,078',
 'maldives': '546,995',
 'madagascar': '28,171,349',
 'rwanda': '13,168,963',
 'french-polynesia': '282,015',
 'mayotte': '277,260',
 'mauritania': '4,732,097',
 'swaziland': '1,168,334',
 'french-guiana': '303,905',
 'guinea': '13,372,968',
 'syria': '17,787,729',
 'cabo-verde': '560,093',
 'gabon': '2,261,210',
 'tajikistan': '9,682,441',
 'reunion': '899,664',
 'haiti': '11,496,983',
 'belize': '402,518',
 'burkina-faso': '21,289,665',
 'china-hong-kong-sar': '7,538,394',
 'andorra': '77,349',
 'lesotho': '2,153,813',
 'guadeloupe': '400,171',
 'congo': '5,609,785',
 'suriname': '590,209',
 'guyana': '789,140',
 'south-sudan': '11,282,923',
 'bahamas': '395,801',
 'mali': '20,643,738',
 'somalia': '16,192,052',
 'aruba': '107,075',
 'trinidad-and-tobago': '1,402,581',
 'togo': '8,409,803',
 'martinique': '375,066',
 'nicaragua': '6,678,119',
 'equatorial-guinea': '1,433,965',
 'benin': '12,337,400',
 'djibouti': '997,751',
 'iceland': '342,752',
 'central-african-republic': '4,886,678',
 'niger': '24,794,492',
 'curacao': '164,551',
 'gambia': '2,462,419',
 'gibraltar': '33,684',
 'chad': '16,743,380',
 'channel-islands': '174,954',
 'san-marino': '33,980',
 'sierra-leone': '8,086,753',
 'saint-lucia': '184,199',
 'comoros': '882,129',
 'mongolia': '3,314,093',
 'guinea-bissau': '1,999,420',
 'barbados': '287,615',
 'seychelles': '98,762',
 'eritrea': '3,579,746',
 'liechtenstein': '38,203',
 'viet-nam': '97,934,643',
 'yemen': '30,270,072',
 'burundi': '12,129,209',
 'turks-and-caicos-islands': '39,073',
 'sint-maarten': '43,207',
 'liberia': '5,137,985',
 'monaco': '39,432',
 'sao-tome-and-principe': '221,915',
 'papua-new-guinea': '9,061,792',
 'saint-vincent-and-the-grenadines': '111,180',
 'saint-martin': '39,113',
 'cambodia': '16,876,064',
 'taiwan': '23,846,210',
 'bhutan': '777,385',
 'antigua-and-barbuda': '98,481',
 'isle-of-man': '85,340',
 'bermuda': '62,121',
 'faeroe-islands': '48,990',
 'mauritius': '1,273,209',
 'saint-barthelemy': '9,898',
 'caribbean-netherlands': '26,389',
 'tanzania': '60,880,517',
 'cayman-islands': '66,247',
 'brunei-darussalam': '440,329',
 'british-virgin-islands': '30,368',
 'grenada': '112,879',
 'dominica': '72,108',
 'timor-leste': '1,335,449',
 'new-caledonia': '287,365',
 'fiji': '900,870',
 'falkland-islands-malvinas': '3,548',
 'china-macao-sar': '655,346',
 'laos': '7,347,217',
 'saint-kitts-and-nevis': '53,455',
 'greenland': '56,837',
 'holy-see': '802',
 'saint-pierre-and-miquelon': '5,775',
 'montserrat': '4,994',
 'anguilla': '15,094',
 'solomon-islands': '698,257',
 'wallis-and-futuna-islands': '11,104',
 'western-sahara': '607,254',
 'marshall-islands': '59,462',
 'samoa': '199,312',
 'vanuatu': '311,994',
 'micronesia': '115,843',
 'usa': '332,325,610'}

In [26]:
get_country_data(soup,indexes['USA'])

['USA',
 29696250.0,
 'NA',
 537838.0,
 'NA',
 20336656.0,
 'NA',
 8821756.0,
 13111.0,
 89359.0,
 1618.0,
 369210234.0,
 1110989.0,
 332325610.0,
 'North America']

In [27]:
import pandas as pd

In [28]:
stats = pd.DataFrame(get_country_data(soup,world_index), columns=['World'])
stats

          World
0         World
1   1.17515e+08
2         73922
3   2.60683e+06
4          1739
5    9.3033e+07
6         71933
7   2.18755e+07
8         89642
9         15076
10        334.4
11           NA
12           NA
13           NA
14          All

for i in countries:
    print(get_country_data(soup,indexes[i]))

In [29]:
for i in countries[0:3]:
    print(get_country_data(soup,indexes[i]))

['USA', 29696250.0, 'NA', 537838.0, 'NA', 20336656.0, 'NA', 8821756.0, 13111.0, 89359.0, 1618.0, 369210234.0, 1110989.0, 332325610.0, 'North America']
['India', 11229398.0, 127.0, 157890.0, 'NA', 10882798.0, 1918.0, 188710.0, 8944.0, 8083.0, 114.0, 221968271.0, 159777.0, 1389234581.0, 'Asia']
['Brazil', 11019344.0, 'NA', 265500.0, 'NA', 9757178.0, 'NA', 996666.0, 8318.0, 51591.0, 1243.0, 28600000.0, 133902.0, 213588678.0, 'South America']

In [30]:
def df_top_countries(n):
    '''get the top n countries in terms of total cases'''
    
    cols = ['Country','Total Cases','New Cases','Total Deaths','New Deaths',
    'Total Recovered','New Recovered','Active Cases','Serious/Critical','TotalCases/1Mpop',
    'Deaths/1Mpop','Total Tests','Tests/1Mpop','Total pop','Region']
    
    stats = pd.DataFrame(get_country_data(soup,world_index), columns=['World'])
    
    for i in countries[0:n]:
    #print(get_country_data(soup,indexes[i]))
        stats[i] = get_country_data(soup,indexes[i])
    
    stats = stats.transpose()
    stats.columns = cols
    stats.set_index('Country',inplace=True)
    
    
    for i in stats.columns[0:-1]:
        stats[i] = stats[i].apply(lambda x : '{:,}'.format(float(x)) if x != 'NA' else x)
    
    return stats

In [31]:
df_top = df_top_countries(10)

In [32]:
df_top

,Total Cases,New Cases,Total Deaths,New Deaths,Total Recovered,New Recovered,Active Cases,Serious/Critical,TotalCases/1Mpop,Deaths/1Mpop,Total Tests,Tests/1Mpop,Total pop,Region
Country,,,,,,,,,,,,,,
World,"117,515,398.0","73,922.0","2,606,830.0","1,739.0","93,033,040.0","71,933.0","21,875,528.0","89,642.0","15,076.0",334.4,NA,NA,NA,All
USA,"29,696,250.0",NA,"537,838.0",NA,"20,336,656.0",NA,"8,821,756.0","13,111.0","89,359.0","1,618.0","369,210,234.0","1,110,989.0","332,325,610.0",North America
India,"11,229,398.0",127.0,"157,890.0",NA,"10,882,798.0","1,918.0","188,710.0","8,944.0","8,083.0",114.0,"221,968,271.0","159,777.0","1,389,234,581.0",Asia
Brazil,"11,019,344.0",NA,"265,500.0",NA,"9,757,178.0",NA,"996,666.0","8,318.0","51,591.0","1,243.0","28,600,000.0","133,902.0","213,588,678.0",South America
Russia,"4,333,029.0","10,253.0","89,473.0",379.0,"3,922,246.0","10,322.0","321,310.0","2,300.0","29,683.0",613.0,"113,500,000.0","777,519.0","145,977,217.0",Europe
UK,"4,218,520.0",NA,"124,501.0",NA,"3,199,565.0",NA,"894,454.0","1,542.0","61,919.0","1,827.0","94,197,029.0","1,382,625.0","68,129,139.0",Europe
France,"3,904,233.0",NA,"88,574.0",NA,"265,295.0",NA,"3,550,364.0","3,743.0","59,723.0","1,355.0","54,979,855.0","841,029.0","65,372,120.0",Europe
Spain,"3,149,012.0",NA,"71,138.0",NA,"2,744,664.0",NA,"333,210.0","2,571.0","67,334.0","1,521.0","39,313,189.0","840,615.0","46,767,152.0",Europe
Italy,"3,067,486.0",NA,"99,785.0",NA,"2,494,839.0",NA,"472,862.0","2,605.0","50,785.0","1,652.0","42,342,845.0","701,029.0","60,401,031.0",Europe
Turkey,"2,780,417.0",NA,"29,030.0",NA,"2,623,924.0",NA,"127,463.0","1,261.0","32,728.0",342.0,"34,122,851.0","401,652.0","84,956,188.0",Asia
Germany,"2,508,655.0",NA,"72,532.0",NA,"2,310,900.0","6,600.0","125,223.0","2,848.0","29,877.0",864.0,"45,114,160.0","537,286.0","83,966,763.0",Europe

In [33]:
def styler(df):
    
    return df.style\
.applymap(lambda x: 'background-color: indianred' if x =='NA' else  'background-color: snow', \
                                        subset = df.columns[0:-1])\
.applymap(lambda x : 'background-color: palegreen'if x != 'NA' else 'background-color: maroon' , subset = df.columns[0])\
.applymap(lambda x : 'background-color: lightgreen' if x == 'Asia' else
          'background-color: skyblue' if x == 'North America' or x== 'South America'  else
          'background-color: mediumslateblue' if x == 'Europe' else
          'background-color: pink' if x == 'Africa' else x
          , subset = df.columns[-1])

In [34]:
styler(df_top)

In [39]:
get_one_country_index(soup , country='Argentina')

362

In [44]:
indexes

{'USA': 153,
 'India': 172,
 'Brazil': 191,
 'Russia': 210,
 'UK': 229,
 'France': 248,
 'Spain': 267,
 'Italy': 286,
 'Turkey': 305,
 'Germany': 324,
 'Colombia': 343,
 'Argentina': 362,
 'Mexico': 381,
 'Poland': 400,
 'Iran': 419,
 'South Africa': 438,
 'Ukraine': 457,
 'Indonesia': 476,
 'Peru': 495,
 'Czechia': 514,
 'Netherlands': 533,
 'Canada': 552,
 'Chile': 571,
 'Romania': 590,
 'Portugal': 609,
 'Israel': 628,
 'Belgium': 647,
 'Iraq': 666,
 'Sweden': 685,
 'Philippines': 704,
 'Pakistan': 723,
 'Switzerland': 742,
 'Bangladesh': 761,
 'Morocco': 780,
 'Serbia': 799,
 'Austria': 818,
 'Hungary': 837,
 'Japan': 856,
 'Jordan': 875,
 'UAE': 894,
 'Lebanon': 913,
 'Saudi Arabia': 932,
 'Panama': 951,
 'Slovakia': 970,
 'Malaysia': 989,
 'Belarus': 1008,
 'Ecuador': 1027,
 'Nepal': 1046,
 'Georgia': 1065,
 'Bulgaria': 1084,
 'Bolivia': 1103,
 'Croatia': 1122,
 'Dominican Republic': 1141,
 'Tunisia': 1160,
 'Azerbaijan': 1179,
 'Ireland': 1198,
 'Kazakhstan': 1217,
 'Denmark': 1236,
 'Costa Rica': 1255,
 'Greece': 1274,
 'Lithuania': 1293,
 'Kuwait': 1312,
 'Palestine': 1331,
 'Slovenia': 1350,
 'Moldova': 1369,
 'Egypt': 1388,
 'Guatemala': 1407,
 'Armenia': 1426,
 'Honduras': 1445,
 'Paraguay': 1464,
 'Qatar': 1483,
 'Ethiopia': 1502,
 'Nigeria': 1521,
 'Oman': 1540,
 'Venezuela': 1559,
 'Myanmar': 1578,
 'Libya': 1597,
 'Bosnia and Herzegovina': 1616,
 'Bahrain': 1635,
 'Algeria': 1654,
 'Albania': 1673,
 'Kenya': 1692,
 'North Macedonia': 1711,
 'S. Korea': 1730,
 'Latvia': 1749,
 'Kyrgyzstan': 1768,
 'Ghana': 1787,
 'Sri Lanka': 1806,
 'Zambia': 1825,
 'Uzbekistan': 1844,
 'Montenegro': 1863,
 'Estonia': 1882,
 'Norway': 1901,
 'Uruguay': 1920,
 'Finland': 1939,
 'Mozambique': 1958,
 'El Salvador': 1977,
 'Singapore': 1996,
 'Luxembourg': 2015,
 'Afghanistan': 2034,
 'Cuba': 2053,
 'Uganda': 2072,
 'Namibia': 2091,
 'Cyprus': 2110,
 'Zimbabwe': 2129,
 'Senegal': 2148,
 'Cameroon': 2167,
 'Ivory Coast': 2186,
 'Malawi': 2205,
 'Botswana': 2224,
 'Australia': 2243,
 'Sudan': 2262,
 'DRC': 2281,
 'Thailand': 2300,
 'Jamaica': 2319,
 'Malta': 2338,
 'Angola': 2357,
 'Maldives': 2376,
 'Madagascar': 2395,
 'Rwanda': 2414,
 'French Polynesia': 2433,
 'Mayotte': 2452,
 'Mauritania': 2471,
 'Eswatini': 2490,
 'French Guiana': 2509,
 'Guinea': 2528,
 'Syria': 2547,
 'Cabo Verde': 2566,
 'Gabon': 2585,
 'Tajikistan': 2604,
 'Réunion': 2623,
 'Haiti': 2642,
 'Belize': 2661,
 'Burkina Faso': 2680,
 'Hong Kong': 2699,
 'Andorra': 2718,
 'Lesotho': 2737,
 'Guadeloupe': 2756,
 'Congo': 2775,
 'Suriname': 2794,
 'Guyana': 2813,
 'South Sudan': 2832,
 'Bahamas': 2851,
 'Mali': 2870,
 'Somalia': 2889,
 'Aruba': 2908,
 'Trinidad and Tobago': 2927,
 'Togo': 2946,
 'Martinique': 2965,
 'Nicaragua': 2984,
 'Equatorial Guinea': 3003,
 'Benin': 3022,
 'Djibouti': 3041,
 'Iceland': 3060,
 'CAR': 3079,
 'Niger': 3098,
 'Curaçao': 3117,
 'Gambia': 3136,
 'Gibraltar': 3155,
 'Chad': 3174,
 'Channel Islands': 3193,
 'San Marino': 3212,
 'Sierra Leone': 3231,
 'Saint Lucia': 3250,
 'Comoros': 3269,
 'Mongolia': 3288,
 'Guinea-Bissau': 3307,
 'Barbados': 3326,
 'Seychelles': 3345,
 'Eritrea': 3364,
 'Liechtenstein': 3383,
 'Vietnam': 3402,
 'Yemen': 3421,
 'New Zealand': 3440,
 'Burundi': 3459,
 'Turks and Caicos': 3478,
 'Sint Maarten': 3497,
 'Liberia': 3516,
 'Monaco': 3535,
 'Sao Tome and Principe': 3554,
 'Papua New Guinea': 3573,
 'St. Vincent Grenadines': 3592,
 'Saint Martin': 3611,
 'Cambodia': 3630,
 'Taiwan': 3649,
 'Bhutan': 3668,
 'Antigua and Barbuda': 3687,
 'Isle of Man': 3706,
 'Bermuda': 3725,
 'Diamond Princess': 3744,
 'Faeroe Islands': 3763,
 'Mauritius': 3782,
 'St. Barth': 3801,
 'Caribbean Netherlands': 3820,
 'Tanzania': 3839,
 'Cayman Islands': 3858,
 'Brunei ': 3877,
 'British Virgin Islands': 3896,
 'Grenada': 3915,
 'Dominica': 3934,
 'Timor-Leste': 3953,
 'New Caledonia': 3972,
 'Fiji': 3991,
 'Falkland Islands': 4010,
 'Macao': 4029,
 'Laos': 4048,
 'Saint Kitts and Nevis': 4067,
 'Greenland': 4086,
 'Vatican City': 4105,
 'Saint Pierre Miquelon': 4124,
 'Montserrat': 4143,
 'Anguilla': 4162,
 'Solomon Islands': 4181,
 'Wallis and Futuna': 4200,
 'Western Sahara': 4219,
 'MS Zaandam': 4238,
 'Marshall Islands': 4257,
 'Samoa': 4276,
 'Vanuatu': 4295,
 'Micronesia': 4314,
 'China': 4333}

In [67]:
newlist = list(indexes.keys())
newlist.sort()

In [68]:
newlist

['Afghanistan',
 'Albania',
 'Algeria',
 'Andorra',
 'Angola',
 'Anguilla',
 'Antigua and Barbuda',
 'Argentina',
 'Armenia',
 'Aruba',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bermuda',
 'Bhutan',
 'Bolivia',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'British Virgin Islands',
 'Brunei ',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'CAR',
 'Cabo Verde',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Caribbean Netherlands',
 'Cayman Islands',
 'Chad',
 'Channel Islands',
 'Chile',
 'China',
 'Colombia',
 'Comoros',
 'Congo',
 'Costa Rica',
 'Croatia',
 'Cuba',
 'Curaçao',
 'Cyprus',
 'Czechia',
 'DRC',
 'Denmark',
 'Diamond Princess',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Eswatini',
 'Ethiopia',
 'Faeroe Islands',
 'Falkland Islands',
 'Fiji',
 'Finland',
 'France',
 'French Guiana',
 'French Polynesia',
 'Gabon',
 'Gambia',
 'Georgia',
 'Germany',
 'Ghana',
 'Gibraltar',
 'Greece',
 'Greenland',
 'Grenada',
 'Guadeloupe',
 'Guatemala',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Honduras',
 'Hong Kong',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Iran',
 'Iraq',
 'Ireland',
 'Isle of Man',
 'Israel',
 'Italy',
 'Ivory Coast',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kuwait',
 'Kyrgyzstan',
 'Laos',
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Liechtenstein',
 'Lithuania',
 'Luxembourg',
 'MS Zaandam',
 'Macao',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Marshall Islands',
 'Martinique',
 'Mauritania',
 'Mauritius',
 'Mayotte',
 'Mexico',
 'Micronesia',
 'Moldova',
 'Monaco',
 'Mongolia',
 'Montenegro',
 'Montserrat',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nepal',
 'Netherlands',
 'New Caledonia',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'North Macedonia',
 'Norway',
 'Oman',
 'Pakistan',
 'Palestine',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Qatar',
 'Romania',
 'Russia',
 'Rwanda',
 'Réunion',
 'S. Korea',
 'Saint Kitts and Nevis',
 'Saint Lucia',
 'Saint Martin',
 'Saint Pierre Miquelon',
 'Samoa',
 'San Marino',
 'Sao Tome and Principe',
 'Saudi Arabia',
 'Senegal',
 'Serbia',
 'Seychelles',
 'Sierra Leone',
 'Singapore',
 'Sint Maarten',
 'Slovakia',
 'Slovenia',
 'Solomon Islands',
 'Somalia',
 'South Africa',
 'South Sudan',
 'Spain',
 'Sri Lanka',
 'St. Barth',
 'St. Vincent Grenadines',
 'Sudan',
 'Suriname',
 'Sweden',
 'Switzerland',
 'Syria',
 'Taiwan',
 'Tajikistan',
 'Tanzania',
 'Thailand',
 'Timor-Leste',
 'Togo',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Turks and Caicos',
 'UAE',
 'UK',
 'USA',
 'Uganda',
 'Ukraine',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Vatican City',
 'Venezuela',
 'Vietnam',
 'Wallis and Futuna',
 'Western Sahara',
 'Yemen',
 'Zambia',
 'Zimbabwe']

In [70]:
def dataframe_1_country(country):
    df = pd.DataFrame(get_country_data(soup,indexes[country]), columns=[country])
    cols = ['Country','Total Cases','New Cases','Total Deaths','New Deaths',
    'Total Recovered','New Recovered','Active Cases','Serious/Critical','TotalCases/1Mpop',
    'Deaths/1Mpop','Total Tests','Tests/1Mpop','Total pop','Region']
    df.index = cols
    return df

In [73]:
arg = dataframe_1_country('Argentina')
arg

                      Argentina
Country               Argentina
Total Cases         2.14964e+06
New Cases                    NA
Total Deaths              52880
New Deaths                   NA
Total Recovered     1.94582e+06
New Recovered                NA
Active Cases             150940
Serious/Critical           3467
TotalCases/1Mpop          47268
Deaths/1Mpop               1163
Total Tests          7.7206e+06
Tests/1Mpop              169766
Total pop            4.5478e+07
Region            South America

In [72]:
import seaborn as sns

In [ ]:
datas